project:
  type: book
  output-dir: docs

book:
  title: "World Reference Base for Soil Resources"
  author: "Lauren O'Brien"
  date: "2022-07-26"
  isbn: 979-8-9862451-1-9
  language: en
  page-navigation: true
  cover-image: images/cover.png
  chapters:
    - index.qmd
    - foreword.qmd
    - preface.qmd
    - acknowledgements.qmd
    - list-of-acronyms.qmd
    - chapter-01.qmd
    - chapter-02.qmd
    - chapter-03.qmd
    - chapter-04.qmd
    - chapter-05.qmd
    - chapter-06.qmd
    - chapter-07.qmd
    - annex-01-field-guide.qmd
    - annex-02-analytical-procedures.qmd
    - annex-03-horizon-layer-designations.qmd
    - annex-04-soil-description-sheet.qmd
    - annex-05-database-setup.qmd
    - annex-06-rsg-colours.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    citations-hover: true
    footnotes-hover: true
    number-sections: true
    number-depth: 3
    date-modified: last-modified
    logo: images/cover.png
    appendix-style: none
    css: styles.css

editor: visual

# global knitr options
knitr:
  opts_chunk:
    comment: "#>"
    collapse: true
    fig.align: 'center'
    echo: false
    message: false
    warning: false
    fig.show: 'hold'
    results: 'hold'
