project:
  type: book

book:
  title: "World Reference Base for Soil Resources"
  author: "Lauren O'Brien"
  date: "2022-07-26"
  chapters:
    - index.qmd
    - foreword.qmd
    - preface.qmd
    - acknowledgements.qmd
    - list-of-acronyms.qmd
    - chapter-01.qmd
    - chapter-02.qmd
    - chapter-03.qmd
    - chapter-04.qmd
    - chapter-04-01-histosols.qmd
    - chapter-04-02-anthrosols.qmd
    - chapter-04-03-technosols.qmd
    - chapter-04-04-cryosols.qmd
    - chapter-04-05-leptosols.qmd
    - chapter-04-06-solonetz.qmd
    - chapter-04-07-vertisols.qmd
    - chapter-04-08-solonchaks.qmd
    - chapter-04-09-gleysols.qmd
    - chapter-04-10-andosols.qmd
    - chapter-04-11-podzols.qmd
    - chapter-04-12-plinthosols.qmd
    - chapter-04-13-planosols.qmd
    - chapter-04-14-stagnosols.qmd
    - chapter-04-15-nitisols.qmd
    - chapter-04-16-ferralsols.qmd
    - chapter-04-17-chernozems.qmd
    - chapter-04-18-kastanozems.qmd
    - chapter-04-19-phaeozems.qmd
    - chapter-04-20-umbrisols.qmd
    - chapter-04-21-durisols.qmd
    - chapter-04-22-gypsisols.qmd
    - chapter-04-23-calcisols.qmd
    - chapter-04-24-retisols.qmd
    - chapter-04-25-acrisols.qmd
    - chapter-04-26-lixisols.qmd
    - chapter-04-27-alisols.qmd
    - chapter-04-28-luvisols.qmd
    - chapter-04-29-cambisols.qmd
    - chapter-04-30-fluvisols.qmd
    - chapter-04-31-arenosols.qmd
    - chapter-05.qmd
    - chapter-06.qmd
    - chapter-07.qmd
  appendices:
    - annex-01-field-guide.qmd
    - annex-02-analytical-procedures.qmd
    - annex-03-horizon-layer-designations.qmd
    - annex-04-soil-description-sheet.qmd
    - annex-05-database-setup.qmd
    - annex-06-rsg-colours.qmd


#bibliography: references.bib

format:
  html:
    theme: cosmo
    citations-hover: true
    footnotes-hover: true
    page-navigation: true
    number-depth: 3
    date-modified: last-modified

editor: visual

# global knitr options
knitr:
  opts_chunk:
    comment: "#>"
    collapse: true
    out.width: '85%'
    fig.align: 'center'
    echo: false
    fig.show: 'hold'
    results: 'hold'
