project:
  type: book
  output-dir: docs

book:
  title: "World Reference Base for Soil Resources"
  author: "IUSS Working Group WRB"
  contributor: "Lauren O'Brien"
  date: "2022-07-22"
  isbn: 979-8-9862451-1-9
  language: en
  license: https://creativecommons.org/licenses/by/4.0/legalcode
  page-navigation: true
  publisher: "International Union of Soil Sciences (IUSS)"
  publisher-place: "Vienna, Austria"
  cover-image: images/cover.png
  cover-image-alt: 'An image of the cover of the World Reference Base for Soil Resources, 4th edition, showing pictures of soils and landscapes from around the world.'
  output-file: "WRB-Soil-4e"
  site-url: https://obrl-soil.github.io/wrbsoil2022/
  repo-url: https://github.com/obrl-soil/wrbsoil2022
  repo-branch: main
  reader-mode: true
  search: true
  sharing:
    - twitter
    - linkedin
  image: images/cover.png
  chapters:
    - index.qmd
    - foreword.qmd
    - preface.qmd
    - acknowledgements.qmd
    - list-of-acronyms.qmd
    - chapter-01.qmd
    - chapter-02.qmd
    - chapter-03.qmd
    - chapter-04.qmd
    - chapter-05.qmd
    - chapter-06.qmd
    - chapter-07.qmd
    - annex-01-field-guide.qmd
    - annex-02-analytical-procedures.qmd
    - annex-03-horizon-layer-designations.qmd
    - annex-04-soil-description-sheet.qmd
    - annex-05-database-setup.qmd
    - annex-06-rsg-colours.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    citations-hover: true
    footnotes-hover: true
    number-sections: true
    number-depth: 3
    date-modified: last-modified
    logo: images/cover.png
    appendix-style: none
    css: styles.css
    mermaid:
      theme: neutral
  epub:
    epub-cover-image: images/cover.png

editor: visual

# global knitr options
knitr:
  opts_chunk:
    comment: "#>"
    collapse: true
    fig.align: 'center'
    echo: false
    message: false
    warning: false
    fig.show: 'hold'
    results: 'hold'
