project:
  type: book

book:
  title: "wrbsoil2022"
  author: "Lauren O'Brien"
  date: "26/07/2022"
  chapters:
    - verso.qmd
    - foreword.qmd
    - preface.qmd
    - acknowledgements.qmd
    - list-of-acronyms.qmd
    - chapter-01.qmd
    - chapter-02.qmd
    - chapter-03.qmd
    - chapter-04.qmd
    - chapter-04-01-histosols.qmd
    - chapter-04-02-anthrosols.qmd
    - chapter-04-03-technosols.qmd
    - chapter-04-04-cryosols.qmd
    - chapter-04-05-leptosols.qmd
    - chapter-04-06-solonetz.qmd
    - chapter-04-07-vertisols.qmd



bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

