# Acknowledgements {.unnumbered}

The lead author of the 4th edition of the WRB is Peter Schad (Technical University of Munich, Germany).

The fundamental decisions have been made by the members of the WRB Board: Lúcia Anjos (Brazil), Jaume Boixadera Llobet (Spain), Seppe Deckers (Belgium), Stefaan Dondeyne (Belgium), Einar Eberhardt (Germany), Maria Gerasimova (Russia), Ben Harms (Australia), Cezary Kabała (Poland), Stephan Mantel (The Netherlands), Erika Michéli (Hungary), Curtis Monger (USA), Rosa Poch Claret (Spain), Peter Schad (Germany), Karl Stahr (Germany), Cornie van Huyssteen (South Africa). Vincent Buness (Germany) and Margaretha Rau (Germany) served as secretaries of the WRB Board.

The draft of the Field Guide (Annex 1) and of the Soil Description Sheet (Annex 4) were written by Vincent Buness, Margaretha Rau and Peter Schad and the draft of the Guidance on database set-up (Annex 5) by Einar Eberhardt. The figures, if not assigned otherwise, were made by Vincent Buness.

The current fourth edition received contributions from many scientists, among them are: Erhan Akça (Türkiye), Ólafur Arnalds (Iceland), David Badía Villas (Spain), Alma Barajas Alcalá (Mexico), Albrecht Bauriegel (Germany), Frank Berding (The Netherlands), Maria Bronnikova (Russia), Wolfgang Burghardt (Germany), Przemysław Charzynski (Poland), José Coelho (Brazil), Fernanda Cordeiro (Brazil), Edoardo Costantini (Italy), Jaime de Almeida (Brazil), Ademir Fontana (Brazil), Jérȏme Juilleret (France/Luxembourg), Nikolay Khitrov (Russia), Aleš Kučera (Czech Republic), Eva Lehndorff (Germany), Jota Jota Lelis (Brazil), João Herbert Moreira Viana (Brazil), Freddy Nachtergaele (Belgium), Otmar Nestroy (Austria), Tibor Novák (Hungary), Luis Daniel Olivares Martínez (Mexico), Thilo Rennert (Germany), Blaž Repe (Slovenia), Nuria Roca Pascual (Spain), Thorsten Ruf (Germany/Luxembourg), Alessandro SamuelRosa (Brazil), Tobias Sprafke (Germany/Switzerland), Marcin Świtoniak (Poland), Wenceslau Teixeira (Brazil), Łukasz Uzarowicz (Poland), Karen Vancampenhout (Belgium), Andreas Wild (Germany).
