# Cambisols {#key-cambisols}

::: grid
::: g-col-4
Other soils having:

1.  a *cambic horizon*
    a.  a\. starting ≤ 50 cm from the mineral soil surface; *and*
    b.  having its lower limit ≥ 25 cm from the mineral soil surface; *or*
2.  an *anthraquic*, *hydragric*, *irragric*, *plaggic*, *pretic* or *terric horizon*; *or*
3.  a *fragic*, *thionic* or *vertic horizon* starting ≤ 100 cm from the mineral soil surface; *or*
4.  a *tsitelic horizon* with a texture class of sandy loam or finer, starting ≤ 50 cm from the mineral soil surface; *or*
5.  one or more layers with *andic* or *vitric properties* with a combined thickness of ≥ 15 cm within 100 cm of the soil surface.
:::

::: g-col-8
| Principal Qualifiers                                      | Supplementary Qualifiers        |
|-----------------------------------------------------------|---------------------------------|
| Fragic                                                    | Arenic/ Clayic/ Loamic/ Siltic  |
| Thionic                                                   | Geoabruptic                     |
| Hydragric/ Anthraquic/ Irragric/ Plaggic/ Pretic/ Terric  | Aeolic                          |
| Tsitelic                                                  | Alcalic                         |
| Vertic                                                    | Aric                            |
| Andic                                                     | Biocrustic                      |
| Vitric                                                    | Protocalcic                     |
| Leptic                                                    | Carbonic                        |
| Histic                                                    | Cohesic                         |
| Gleyic                                                    | Columnic                        |
| Stagnic                                                   | Densic                          |
| Solimovic                                                 | Drainic                         |
| Fluvic                                                    | Escalic                         |
| Sideralic                                                 | Ferric                          |
| Rhodic/ Chromic/ Xanthic                                  | Folic                           |
| Skeletic                                                  | Fractic                         |
| Yermic/ Takyric                                           | Gelic                           |
| Gypsiric                                                  | Gelistagnic                     |
| Dolomitic/ Calcaric                                       | Protogypsic                     |
| Dystric/ Eutric                                           | Humic/ Ochric                   |
|                                                           | Isopteric                       |
|                                                           | Laxic                           |
|                                                           | Limonic                         |
|                                                           | Litholinic                      |
|                                                           | Magnesic                        |
|                                                           | Nechic                          |
|                                                           | Novic                           |
|                                                           | Ornithic                        |
|                                                           | Oxyaquic                        |
|                                                           | Panpaic/ Raptic                 |
|                                                           | Pyric                           |
|                                                           | Salic                           |
|                                                           | Saprolithic                     |
|                                                           | Sodic                           |
|                                                           | Protospodic                     |
|                                                           | Sulfidic                        |
|                                                           | Technic/ Kalaic                 |
|                                                           | Tephric                         |
|                                                           | Toxic                           |
|                                                           | Transportic                     |
|                                                           | Turbic                          |
:::
:::
