# Vertisols {#key-vertisols}

::: grid
::: g-col-4
Other soils having:

1.  a *vertic horizon* starting ≤ 100 cm from the mineral soil surface; *and*

2.  ≥ 30% clay between the mineral soil surface and the *vertic horizon* throughout; *and*

3.  *shrink-swell cracks* that start:

    a.  at the mineral soil surface; *or*
    b.  at the base of a plough layer; *or*
    c.  directly below a layer with strong granular structure or strong angular or subangular blocky structure with an aggregate size of ≤ 1 cm (self-mulching surface); *or*
    d.  directly below a surface crust; *and* \
        \
        extend to the *vertic horizon*.
:::

::: g-col-8
| Principal Qualifiers             | Supplementary Qualifiers    |
|----------------------------------|-----------------------------|
| Salic                            | Alcalic/ Endodystric        |
| Sodic                            | Aric                        |
| Leptic                           | Chernic/ Mollic             |
| Petroduric/ Duric                | Dolomitic/ Calcaric         |
| Gypsic                           | Drainic                     |
| Petrocalcic                      | Hypereutric                 |
| Calcic                           | Epic/ Endic                 |
| Hydragric/ Anthraquic/ Irragric  | Ferric                      |
| Pellic                           | Fractic                     |
| Chromic                          | Gilgaic                     |
| Haplic                           | Gleyic                      |
|                                  | Grumic/ Mazic/ Pelocrustic  |
|                                  | Gypsiric                    |
|                                  | Humic/ Ochric               |
|                                  | Magnesic                    |
|                                  | Mesotrophic                 |
|                                  | Novic                       |
|                                  | Oxyaquic                    |
|                                  | Pyric                       |
|                                  | Raptic                      |
|                                  | Skeletic                    |
|                                  | Stagnic                     |
|                                  | Sulfidic                    |
|                                  | Technic/ Kalaic             |
|                                  | Takyric                     |
|                                  | Thionic                     |
|                                  | Toxic                       |
:::
:::
