# Acrisols {#key-acrisols}

::: grid
::: g-col-4
Other soils having:

1.  an *argic horizon* starting ≤ 100 cm from the mineral soil surface; *and*
2.  a CEC (by 1 *M* NH~4~OAc, pH 7) of \< 24 cmol~c~ kg^-1^ clay in some subhorizon of the *argic horizon* within 150 cm of the mineral soil surface; *and*
3.  exchangeable Al \> exchangeable (Ca+Mg+K+Na)[^chapter-04-25-acrisols-1] in half or more of:
    a.  the depth range between 50 and 100 cm of the mineral soil surface; *or*
    b.  the lower half of the mineral soil above a limiting layer starting ≤ 100 cm from the mineral soil surface, whichever is shallower.
:::

::: g-col-8
| Principal Qualifiers                   | Supplementary Qualifiers        |
|----------------------------------------|---------------------------------|
| Abruptic                               | Arenic/ Clayic/ Loamic/ Siltic  |
| Fragic                                 | Andic                           |
| Leptic                                 | Aric                            |
| Hydragric/ Anthraquic/ Pretic/ Terric  | Neocambic/ Neobrunic            |
| Gleyic                                 | Cohesic                         |
| Stagnic                                | Cutanic                         |
| Ferralic                               | Densic                          |
| Rhodic/ Chromic/ Xanthic               | Differentic                     |
| Nudiargic                              | Hyperdystric/ Epieutric         |
| Lamellic                               | Epic/ Endic                     |
| Albic                                  | Geric                           |
| Ferric                                 | Gibbsic                         |
| Skeletic                               | Humic/ Ochric                   |
| Haplic                                 | Magnesic                        |
|                                        | Nechic                          |
|                                        | Nitic                           |
|                                        | Novic                           |
|                                        | Oxyaquic                        |
|                                        | Posic                           |
|                                        | Profondic                       |
|                                        | Pyric                           |
|                                        | Raptic                          |
|                                        | Saprolithic                     |
|                                        | Sodic                           |
|                                        | Solimovic                       |
|                                        | Sombric                         |
|                                        | Technic/ Kalaic                 |
|                                        | Toxic                           |
|                                        | Transportic                     |
|                                        | Vitric                          |
:::
:::

[^chapter-04-25-acrisols-1]: Exchangeable cations are given in cmol~c~ kg^-1^. If these data are not available, pH values may be used according to Annex 2 (Chapter 9.13).
