# Calcisols {#key-calcisols .unnumbered}

::: grid
::: g-col-4
Other soils having:

1.  a *calcic* or *petrocalcic horizon* starting ≤ 100 cm from the mineral soil surface; *and*
2.  no *argic horizon* starting above or at the upper limit of the *calcic* or *petrocalcic horizon* unless the *argic horizon* contains secondary carbonates, throughout.
:::

::: g-col-8
| Principal Qualifiers | Supplementary Qualifiers       |
|----------------------|--------------------------------|
| Petric               | Arenic/ Clayic/ Loamic/ Siltic |
| Leptic               | Abruptic                       |
| Gleyic               | Aeolic                         |
| Stagnic              | Aric                           |
| Lixic/ Luvic         | Biocrustic                     |
| Cambic               | Hypercalcic                    |
| Coarsic              | Densic                         |
| Fractic              | Epic/ Endic                    |
| Skeletic             | Fluvic                         |
| Yermic/ Takyric      | Gelic                          |
| Gypsiric             | Protogypsic                    |
| Haplic               | Humic/ Ochric                  |
|                      | Isopteric                      |
|                      | Magnesic                       |
|                      | Naramic                        |
|                      | Novic                          |
|                      | Panpaic/ Raptic                |
|                      | Pyric                          |
|                      | Rhodic/ Chromic                |
|                      | Salic                          |
|                      | Sodic                          |
|                      | Solimovic                      |
|                      | Technic                        |
|                      | Toxic/ Kalaic                  |
|                      | Transportic                    |
|                      | Turbic                         |
|                      | Vertic                         |
:::
:::
