# Leptosols {#key-leptosols}

::: grid
::: g-col-4
Other soils having:

1.  one of the following:
    a.  *continuous rock* starting ≤ 25 cm from the soil surface; *or*
    b.  \< 20% (by volume, related to the whole soil) fine earth[^chapter-04-05-leptosols-1], averaged over a depth of 75 cm from the soil surface or to *continuous rock*, whichever is shallower; *and*
2.  no *chernic*, *duric*, *petrocalcic*, *petroduric*, *petrogypsic*, *petroplinthic*, *pisoplinthic* or *spodic horizon*.
:::

::: g-col-8
| Principal Qualifiers     | Supplementary Qualifiers        |
|--------------------------|---------------------------------|
| Nudilithic/ Lithic       | Arenic/ Clayic/ Loamic/ Siltic  |
| Coarsic                  | Aeolic                          |
| Skeletic                 | Aric                            |
| Subaquatic/ Tidalic      | Biocrustic                      |
| Histic                   | Protocalcic                     |
| Andic                    | Drainic                         |
| Rendzic/ Mollic/ Umbric  | Fluvic                          |
| Gypsic                   | Gelic                           |
| Calcic                   | Gleyic                          |
| Cambic/ Brunic           | Humic/ Ochric                   |
| Yermic/ Takyric          | Isolatic                        |
| Folic                    | Lapiadic                        |
| Gypsiric                 | Magnesic                        |
| Dolomitic/ Calcaric      | Nechic                          |
| Dystric/ Eutric          | Novic                           |
|                          | Ornithic                        |
|                          | Oxyaquic                        |
|                          | Panpaic/ Raptic                 |
|                          | Placic                          |
|                          | Protic                          |
|                          | Pyric                           |
|                          | Salic                           |
|                          | Sodic                           |
|                          | Protospodic                     |
|                          | Solimovic                       |
|                          | Stagnic                         |
|                          | Sulfidic                        |
|                          | Technic/ Kalaic                 |
|                          | Tephric                         |
|                          | Toxic                           |
|                          | Transportic                     |
|                          | Turbic                          |
|                          | Protovertic                     |
|                          | Vitric                          |
:::
:::

[^chapter-04-05-leptosols-1]: The volume not occupied by fine earth is occupied by coarse fragments or pores.
