# Gleysols {#key-gleysols}

::: grid
::: g-col-4
Other soils having one or more of the following:

1.  a layer, ≥ 25 cm thick and starting ≤ 40 cm from the mineral soil surface, that has
    a.  *gleyic properties* throughout; *and*
    b.  *reducing conditions* in some parts of every sublayer; *or*
2.  both of the following:
    a.  a *mollic* or *umbric horizon*, \> 40 cm thick, that has *reducing conditions* in some parts of every sublayer, from 40 cm below the mineral soil surface to the lower limit of the *mollic* or *umbric horizon*; *and*
    b.  directly underneath the *mollic/umbric horizon*, a layer, ≥ 10 cm thick, that has its lower limit ≥ 65 cm below the mineral soil surface, and that has:
        i.  *gleyic properties* throughout; *and*
        ii. *reducing conditions* in some parts of every sublayer; *or*
3.  permanent saturation by water starting ≤ 40 cm from the mineral soil surface.
:::

::: g-col-8
| Principal Qualifiers                                              | Supplementary Qualifiers        |
|------------------------------------|------------------------------------|
| Thionic                                                           | Acric/ Lixic/ Alic/ Luvic       |
| Reductic                                                          | Alcalic                         |
| Subaquatic/ Tidalic                                               | Abruptic                        |
| Hydragric/ Anthraquic/ Irragric/ Hortic/ Plaggic/ Pretic/ Terric  | Arenicolic                      |
| Histic                                                            | Arenic/ Clayic/ Loamic/ Siltic  |
| Andic                                                             | Aric                            |
| Vitric                                                            | Drainic                         |
| Chernic/ Mollic/ Umbric                                           | Ferralic/ Sideralic             |
| Pisoplinthic/ Plinthic                                            | Folic                           |
| Stagnic                                                           | Fractic                         |
| Oxyaquic                                                          | Gelic                           |
| Oxygleyic/ Reductigleyic                                          | Humic/ Ochric                   |
| Gypsic                                                            | Inclinic                        |
| Calcic/ Wapnic                                                    | Laxic                           |
| Spodic                                                            | Limnic                          |
| Fluvic                                                            | Limonic                         |
| Gypsiric                                                          | Magnesic                        |
| Dolomitic/ Calcaric                                               | Mulmic                          |
| Dystric/ Eutric                                                   | Nechic                          |
|                                                                   | Novic                           |
|                                                                   | Placic                          |
|                                                                   | Pyric                           |
|                                                                   | Raptic                          |
|                                                                   | Relocatic                       |
|                                                                   | Salic                           |
|                                                                   | Skeletic                        |
|                                                                   | Sodic                           |
|                                                                   | Solimovic                       |
|                                                                   | Sulfidic                        |
|                                                                   | Takyric                         |
|                                                                   | Technic/ Kalaic                 |
|                                                                   | Tephric                         |
|                                                                   | Toxic                           |
|                                                                   | Transportic                     |
|                                                                   | Turbic                          |
|                                                                   | Uterquic                        |
|                                                                   | Vertic                          |
:::
:::
