# Technosols[^chapter-04-03-technosols-1] {#key-technosols}

[^chapter-04-03-technosols-1]: Technosols may bury other soils, which can be mentioned behind the Technosol classification using the word 'over' in between (see Chapter 2.4). Alternatively, buried diagnostic horizons or buried layers with a diagnostic property can be indicated with the Thapto- specifier followed by a qualifier. The soil material above a geomembrane or *technic hard material* may also be characterized by qualifiers. If the thickness or depth criteria of these qualifiers are not met, the Supra- specifier can be used (see Chapter 2.3.2).

::: grid
::: g-col-4
Other soils:

1.  with all of the following:
    a.  one or both of the following:
        i.  having ≥ 20% (by volume, weighted average, related to the whole soil) *artefacts* in the upper 100 cm from the soil surface or to a limiting layer, whichever is shallower; *or*
        ii. having a layer, ≥ 10 cm thick and starting ≤ 50 cm from the soil surface, with ≥ 80% (by volume, related to the whole soil) artefacts; *and*
    b.  not having a layer containing *artefacts* that qualifies as an *argic*, *duric*, *ferralic*, *ferric*, *fragic*, *hydragric*, *natric*, *nitic*, *petrocalcic*, *petroduric*, *petrogypsic*, *petroplinthic*, *pisoplinthic*, *plinthic*, *spodic* or *vertic* horizon starting ≤ 100 cm from the soil surface, unless buried; *and*
    c.  not having a limiting layer, starting ≤ 10 cm from the soil surface; *or*
2.  having a continuous, very slowly permeable to impermeable, constructed geomembrane of any thickness or *technic hard material* starting ≤ 100 cm from the soil surface.
:::

::: g-col-8
| Principal Qualifiers | Supplementary Qualifiers                              |
|------------------------------------|------------------------------------|
| Ekranic/ Thyric      | Arenic/ Clayic/ Loamic/ Siltic                        |
| Linic                | Geoabruptic                                           |
| Urbic                | Alcalic/ Dystric/ Eutric                              |
| Spolic               | Anthraquic/ Irragric/ Hortic/ Plaggic/ Pretic/ Terric |
| Garbic               | Archaic                                               |
| Cryic                | Calcic                                                |
| Isolatic             | Cambic                                                |
| Leptic               | Carbonic                                              |
| Subaquatic/ Tidalic  | Chernic/ Mollic/ Umbric                               |
| Reductic             | Densic                                                |
| Coarsic              | Dolomitic/ Calcaric                                   |
| Gleyic               | Drainic                                               |
| Stagnic              | Ferritic                                              |
| Andic                | Fluvic                                                |
|                      | Folic/ Histic                                         |
|                      | Fractic                                               |
|                      | Gelic                                                 |
|                      | Gypsic                                                |
|                      | Gypsiric                                              |
|                      | Humic/ Ochric                                         |
|                      | Hyperartefactic                                       |
|                      | Immissic                                              |
|                      | Laxic                                                 |
|                      | Lignic                                                |
|                      | Limnic                                                |
|                      | Magnesic                                              |
|                      | Novic                                                 |
|                      | Oxyaquic                                              |
|                      | Panpaic/ Raptic                                       |
|                      | Pyric                                                 |
|                      | Relocatic                                             |
|                      | Salic                                                 |
|                      | Sideralic                                             |
|                      | Skeletic                                              |
|                      | Sodic                                                 |
|                      | Solimovic                                             |
|                      | Protospodic                                           |
|                      | Sulfidic                                              |
|                      | Tephric                                               |
|                      | Thionic                                               |
|                      | Toxic                                                 |
|                      | Transportic                                           |
|                      | Vitric                                                |
:::
:::
