# Cryosols {#key-cryosols .unnumbered}

::: grid
::: g-col-4
Other soils having:

1.  a *cryic horizon* starting ≤ 100 cm from the soil surface; *or*

2.  a *cryic horizon* starting ≤ 200 cm from the soil surface *and*\
    evidence of cryogenic alteration (cryoturbation, frost heave, cryogenic sorting, thermal cracking, ice segregation, patterned ground, etc.) in some layer within 100 cm of the soil surface.
:::

::: g-col-8
| Principal Qualifiers                       | Supplementary Qualifiers       |
|------------------------------------------|------------------------------|
| Glacic                                     | Arenic/ Clayic/ Loamic/ Siltic |
| Turbic                                     | Abruptic                       |
| Subaquatic/ Tidalic/ Reductaquic/ Oxyaquic | Albic                          |
| Leptic                                     | Alcalic/ Dystric/ Eutric       |
| Protic                                     | Biocrustic                     |
| Histic                                     | Dolomitic/ Calcaric            |
| Andic                                      | Drainic                        |
| Mollic/ Umbric                             | Epic/ Endic/ Dorsic            |
| Natric                                     | Evapocrustic/ Puffic           |
| Salic                                      | Fluvic                         |
| Spodic                                     | Folic                          |
| Alic/ Luvic                                | Gypsiric                       |
| Calcic/ Wapnic                             | Humic/ Ochric                  |
| Yermic                                     | Limnic                         |
| Cambic                                     | Magnesic                       |
| Coarsic                                    | Nechic                         |
| Skeletic                                   | Novic                          |
| Haplic                                     | Ornithic                       |
|                                            | Pyric                          |
|                                            | Raptic                         |
|                                            | Sodic                          |
|                                            | Sulfidic                       |
|                                            | Technic/ Kalaic                |
|                                            | Tephric                        |
|                                            | Thixotropic                    |
|                                            | Toxic                          |
|                                            | Transportic                    |
|                                            | Vitric                         |
:::
:::
