# References

Asiamah, R.D. 2000. Plinthite and conditions for its hardening in agricultural soils in Ghana. Kwame Nkrumah University of Science and Technology, Kumasi, Ghana. (Thesis)

Broll, G., Brauckmann, H.-J., Overesch, M., Junge, B., Erber, C., Milbert, G., Baize, D. & Nachtergaele, F. 2006. Topsoil characterization -- recommendations for revision and expansion of the FAO-Draft (1998) with emphasis on humus forms and biological features. Journal of Plant Nutrition and Soil Science 169 (3): 453-461.

de Almeida, J.A., Lunardi Neto, A. & Vidal-Torrado, P. 2015. Sombric horizon: Five decades without evolution (Review). Scientia Agricola, doi:10.1590/0103-9016-2014-0111.

FAO. 1988. Soil map of the world. Revised legend, by FAO--UNESCO--ISRIC. World Soil Resources Report No. 60. Rome.

FAO. 1994. World Reference Base for Soil Resources, by ISSS--ISRIC--FAO. Draft. Rome/Wageningen, Netherlands.

FAO. 1998. World Reference Base for Soil Resources, by ISSS--ISRIC--FAO. World Soil Resources Report No. 84. Rome.

FAO. 2001. Lecture notes on the major soils of the world (with CD-ROM), by P. Driessen, J. Deckers, O. Spaargaren & F, Nachtergaele, eds. World Soil Resources Report No. 94. Rome.

FAO--UNESCO. 1971--1981. Soil map of the world 1:5 000 000. 10 Volumes. Paris, UNESCO.

Fieldes, M. & Perrott, K.W. 1966. The nature of allophane soils: 3. Rapid field and laboratory test for allophane. N. Z. J. Sci., 9: 623--629.

Fox, C.A., Tarnocai, C. & Broll, G. 2010. New A Horizon Protocols for Topsoil Characterization in Canada. 19th World Congress of Soil Science Proceedings, Symposium 1.4.2.

Graefe, U., Baritz, R., Broll, G., Kolb, E., Milbert, G. & Wachendorf, C. 2012. Adapting humus form classification to WRB principles. EUROSOIL 2012, Book of Abstracts, p. 954.

Hewitt, A.E. 1992. New Zealand soil classification. DSIR Land Resources Scientific Report 19. Lower Hutt.

Ito, T., Shoji, S., Shirato, Y. & Ono, E. 1991. Differentiation of a spodic horizon from a buried A horizon. Soil Sci. Soc. Am. J., 55: 438--442.

IUSS Working Group WRB. 2006. World Reference Base for Soil Resources 2006. World Soil Resources Report No. 103, FAO, Rome.

IUSS Working Group WRB. 2007. World Reference Base for Soil Resources 2006, First Update 2007. FAO, Rome.

IUSS Working Group WRB. 2010. Guidelines for constructing small-scale map legends using the WRB. FAO, Rome.

Jabiol, B., Zanella, A., Ponge, J.-F., Sartori, G., Englisch, M., van Delft, B., de Waal, R. & Le Bayon, R.C. 2013. A proposal for including humus forms in the World Reference Base for Soil Resources (WRBFAO). Geoderma, 192: 286-294.

Juilleret, J., de Azevedo, A.C., Santos, R.A., dos Santos, J.C., Pedron, F. de A., Dondeyne, S. 2018. Where are we with whole regolith pedology? A comparative study from Brazil. South African Journal of Plant and Soil 35, 251--261. https://doi.org/10.1080/02571862.2017.1411537.

Juilleret, J., Dondeyne, S., Vancampenhout, K., Deckers, J., Hissler, C. 2016. Mind the gap: A classification system for integrating the subsolum into soil surveys. Geoderma 264, 332--339. https://doi.org/10.1016/j.geoderma.2015.08.031.

Kabała, C., Galka, B., Labaz, B., Anjos, L. & Cavassani, R. 2018. Towards more simple and coherent chemical criteria in a classification of anthropogenic soils: A comparison of phosphorus tests for diagnostic horizons and properties. Geoderma, 320: 1-11.

Krogh, L. & Greve, M.H. 1999. Evaluation of World Reference Base for Soil Resources and FAO Soil Map of the World using nationwide grid soil data from Denmark. Soil Use & Man., 15(3):157--166.

Miller, B & Juilleret, J. 2020. The colluvium and alluvium problem: Historical review and current state of definitions. Earth-Science Reviews, 209:103316.

Munsell Soil Color Charts. Munsell Color Co. Inc. Baltimore 18, Maryland 21218, USA.

Nachtergaele, F. 2005. The "soils" to be classified in the World Reference Base for Soil Resources. Euras. Soil Sci., 38(Suppl. 1): 13--19.

Prietzel, J. & Wiesmeier, M. 2019. A concept to optimize the accuracy of soil surface area and SOC stock quantification in mountainous landscapes. Geoderma 356:113922.

Shoji, S., Nanzyo, M., Dahlgren, R.A. & Quantin, P. 1996. Evaluation and proposed revisions of criteria for Andosols in the World Reference Base for Soil Resources. Soil Sci., 161(9): 604--615.

Soil Survey Staff. 1999. Soil taxonomy. A basic system of soil classification for making and interpreting soil surveys. 2nd Edition. Agric. Handbook 436. Washington, DC, Natural Resources Conservation Service, United States Department of Agriculture.

Soil Survey Staff. 2014. Keys to soil taxonomy. 12th Edition. Washington, DC, United States Department of Agriculture, Natural Resources Conservation Service.

Sokolov, I.A. 1997. Soil Formation and Exogenesis. Moscow. 241pp. \[in Russian\].

Takahashi, T., Nanzyo, M. & Shoji, S. 2004. Proposed revisions to the diagnostic criteria for andic and vitric horizons and qualifiers of Andosols in the World Reference Base for Soil Resources. Soil Sci. Plant Nutr., 50 (3): 431--437.

Uzarowicz, L., Zagorski, Z., Mendak, E., Bartminski, P., Szara, E., Kondras, M., Oktaba, L, Turek, A. & Rogozinski, R. 2017. Technogenic soils (Technosols) developed from fly ash and bottom ash from thermal power stations combusting bituminous coal and lignite. Part I. Properties, classification, and indications of early pedognesis. Catena 157: 75-89.

Varghese, T. & Byju, G. 1993. Laterite soils. Their distribution, characteristics, classification and management. Technical Monograph 1. Thirivananthapuram, Sri Lanka, State Committee on Science, Technology and Environment.

Zanella, A., Ponge, J.-F., Jabiol, B., Sartori, G., Kolb, E., Le Bayon, R.-C., Gobat, J.-M., Aubert, M., De Waal, R., Van Delft, B., Vacca, A., Serra, G., Chersich, S., Andreetta, A., Kolli, R., Brun, J.J., Cools, N., Englisch, M., Hager, H., Katzensteiner, K., Brêthes, A., De Nicola, C., Testi, A., Bernier, N., Graefe, U., Wolf, U., Juilleret, J., Garlato, A., Obber, S., Galvan, P., Zampedri, R., Frizzera, L., Tomasi, M., Banas, D., Bureau, F., Tatti, D., Salmon, S., Menardi, R., Fontanella, F., Carraro, V., Pizzeghello, D., Concheri, G., Squartini, A., Cattaneo, D., Scattolin, L., Nardi, S., Nicolini, G., Viola, F. 2018. Humusica 1, article 5: Terrestrial humus systems and forms --- Keys of classification of humus systems and forms. Appl. Soil Ecol. 122, 75--86.
