# Arenosols[^chapter-04-31-arenosols-1] {#key-arenosols .unnumbered}

[^chapter-04-31-arenosols-1]: Arenosols may bury other soils, which can be mentioned behind the Arenosol classification using the word 'over' in between (see Chapter 2.4). Alternatively, buried diagnostic horizons or buried layers with a diagnostic property can be indicated with the Thapto- specifier followed by a qualifier. Arenosols may have diagnostic horizons at depths of \> 100 cm. These can be indicated with the Bathy- specifier followed by a qualifier, e.g. Bathyacric (\> 100 cm), Bathyspodic (\> 200 cm).

::: grid
::: g-col-4
Other soils having within 100 cm of the mineral soil surface:

1.  a weighted average texture class of loamy sand or sand; *and*
2.  layers of finer texture, if present, with a combined thickness of \< 15 cm; *and*
3.  layers with ≥ 40% (by volume, related to the whole soil) coarse fragments, if present, with a combined thickness of \< 15 cm.
:::

::: g-col-8
| Principal Qualifiers | Supplementary Qualifiers       |
|----------------------|--------------------------------|
| Tidalic              | Geoabruptic                    |
| Aeolic               | Alcalic                        |
| Solimovic            | Arenicolic                     |
| Tephric              | Aric                           |
| Tsitelic             | Biocrustic                     |
| Brunic               | Protocalcic                    |
| Protic               | Carbonic                       |
| Gleyic               | Cordic                         |
| Sideralic            | Folic                          |
| Yermic               | Gelic                          |
| Transportic          | Protogypsic                    |
| Relocatic            | Humic/ Ochric                  |
| Gypsiric             | Hydrophobic                    |
| Dolomitic/ Calcaric  | Isopteric                      |
| Dystric/ Eutric      | Lamellic/ Protoargic           |
|                      | Limonic                        |
|                      | Nechic                         |
|                      | Novic                          |
|                      | Ornithic                       |
|                      | Oxyaquic                       |
|                      | Placic                         |
|                      | Panpaic/ Raptic                |
|                      | Pyric                          |
|                      | Rhodic/ Chromic/ Rubic/ Claric |
|                      | Salic                          |
|                      | Sodic                          |
|                      | Bathyspodic                    |
|                      | Protospodic                    |
|                      | Stagnic                        |
|                      | Sulfidic                       |
|                      | Technic/ Kalaic                |
|                      | Toxic                          |
|                      | Turbic                         |
:::
:::
