# Andosols[^chapter-04-10-andosols-1] {#key-andosols}

[^chapter-04-10-andosols-1]: Andosols may bury other soils, which can be mentioned behind the Andosol classification using the word 'over' in between (see Chapter 2.4). Alternatively, buried diagnostic horizons or buried layers with a diagnostic property can be indicated with the Thapto- specifier followed by a qualifier.

::: grid
::: g-col-4
Other soils having:

1.  one or more layers with *andic* or *vitric properties* with a combined thickness of:

    a.  ≥ 30 cm, within 100 cm of the soil surface and starting ≤ 25 cm from the soil surface; *or*
    b.  ≥ 60% of the entire thickness of the soil, if a limiting layer starts \> 25 and ≤ 50 cm from the soil surface; *and*

2.  no *argic*, *ferralic*, *petroplinthic*, *pisoplinthic*, *plinthic* or *spodic horizon* starting ≤ 100 cm of the soil surface, unless buried deeper than 50 cm from the mineral soil surface.
:::

::: g-col-8
| Principal Qualifiers     | Supplementary Qualifiers        |
|--------------------------|---------------------------------|
| Aluandic/ Silandic       | Arenic/ Clayic/ Loamic/ Siltic  |
| Vitric                   | Protoandic                      |
| Leptic                   | Aric                            |
| Hydragric/ Anthraquic    | Dolomitic/ Calcaric             |
| Gleyic                   | Drainic                         |
| Hydric                   | Eutrosilic/ Acroxic             |
| Histic                   | Fluvic                          |
| Chernic/ Mollic/ Umbric  | Folic                           |
| Petroduric/ Duric        | Fragic                          |
| Gypsic                   | Gelic                           |
| Calcic                   | Humic                           |
| Tephric                  | Mulimic                         |
| Aeolic                   | Nechic                          |
| Skeletic                 | Novic                           |
| Dystric/ Eutric          | Oxyaquic                        |
|                          | Panpaic                         |
|                          | Placic                          |
|                          | Posic                           |
|                          | Pyric                           |
|                          | Reductic                        |
|                          | Sideralic                       |
|                          | Sodic                           |
|                          | Solimovic                       |
|                          | Protospodic                     |
|                          | Technic/ Kalaic                 |
|                          | Thixotropic                     |
|                          | Toxic                           |
|                          | Transportic                     |
|                          | Turbic                          |
:::
:::
