# Solonchaks {#key-solonchaks .unnumbered}

::: grid
::: g-col-4
Other soils having:

1.  a *salic horizon* starting ≤ 50 cm from the soil surface; *and*
2.  no *thionic horizon* starting ≤ 50 cm from the soil surface; *and*
3.  not permanently submerged by water and not located below the line affected by tidal water (i.e. not located below the line of mean high water springs).
:::

::: g-col-8
| Principal Qualifiers | Supplementary Qualifiers        |
|----------------------|---------------------------------|
| Petrosalic           | Arenic/ Clayic/ Loamic/ Siltic  |
| Gleyic               | Aceric                          |
| Stagnic              | Aeolic                          |
| Sodic                | Alcalic                         |
| Petrogypsic          | Biocrustic                      |
| Gypsic               | Carbonatic/ Chloridic/ Sulfatic |
| Petrocalcic          | Densic                          |
| Calcic               | Dolomitic/ Calcaric             |
| Leptic               | Drainic                         |
| Mollic               | Duric                           |
| Fluvic               | Evapocrustic/ Puffic            |
| Yermic/ Takyric      | Folic/ Histic                   |
| Haplic               | Fractic                         |
|                      | Gelic                           |
|                      | Gypsiric                        |
|                      | Humic/ Ochric                   |
|                      | Magnesic                        |
|                      | Novic                           |
|                      | Oxyaquic                        |
|                      | Pyric                           |
|                      | Panpaic/ Raptic                 |
|                      | Hypersalic                      |
|                      | Skeletic                        |
|                      | Solimovic                       |
|                      | Sulfidic                        |
|                      | Technic/ Kalaic                 |
|                      | Endothionic                     |
|                      | Toxic                           |
|                      | Transportic                     |
|                      | Turbic                          |
|                      | Vertic                          |
:::
:::
