# Chernozems {#key-chernozems .unnumbered}

::: grid
::: g-col-4
Other soils having:

1.  a *chernic horizon*; *and*
2.  starting ≤ 50 cm below the lower limit of the *mollic*[^chapter-04-17-chernozems-1] *horizon* and, if present, above a *petrocalcic horizon*, a layer with *protocalcic properties*, ≥ 5 cm thick, or a *calcic horizon*; *and*
3.  a base saturation (by 1 *M* NH~4~OAc, pH 7)[^chapter-04-17-chernozems-2] of ≥ 50% from the mineral soil surface to the layer with *protocalcic properties* or to the *calcic horizon*, throughout.
:::

::: g-col-8
| Principal Qualifiers | Supplementary Qualifiers       |
|----------------------|--------------------------------|
| Petroduric/ Duric    | Arenic/ Clayic/ Loamic/ Siltic |
| Petrocalcic          | Andic                          |
| Leptic               | Aric                           |
| Hortic               | Densic                         |
| Gleyic               | Fluvic                         |
| Vertic               | Fractic                        |
| Greyzemic            | Humic                          |
| Luvic                | Novic                          |
| Calcic               | Oxyaquic                       |
| Cambic               | Pachic                         |
| Skeletic             | Pyric                          |
| Vermic               | Raptic                         |
| Tonguic              | Salic                          |
| Haplic               | Sodic                          |
|                      | Solimovic                      |
|                      | Sombric                        |
|                      | Stagnic                        |
|                      | Technic/ Kalaic                |
|                      | Tephric                        |
|                      | Transportic                    |
|                      | Turbic                         |
|                      | Vitric                         |
:::
:::

[^chapter-04-17-chernozems-1]: Any *chernic horizon* also meets the criteria of a *mollic horizon*. The *mollic horizon* may extend below the *chernic horizon*.

[^chapter-04-17-chernozems-2]: If the data for base saturation are not available, pH values may be used according to Annex 2 (Chapter 9.13).
