# Lixisols {#key-lixisols .unnumbered}

::: grid
::: g-col-4
Other soils having:

1.  an *argic horizon* starting ≤ 100 cm from the mineral soil surface; *and*

2.  a CEC (by 1 *M* NH~4~OAc, pH 7) of \< 24 cmol~c~ kg-1 clay in some subhorizon of the *argic horizon* within 150 cm of the mineral soil surface.
:::

::: g-col-8
| Principal Qualifiers                  | Supplementary Qualifiers       |
|---------------------------------------|--------------------------------|
| Abruptic                              | Arenic/ Clayic/ Loamic/ Siltic |
| Fragic                                | Andic                          |
| Petrocalcic                           | Aric                           |
| Leptic                                | Neocambic/ Neobrunic           |
| Hydragric/ Anthraquic/ Pretic/ Terric | Cohesic                        |
| Gleyic                                | Columnic                       |
| Stagnic                               | Cutanic                        |
| Ferralic                              | Densic                         |
| Rhodic/ Chromic/ Xanthic              | Differentic                    |
| Nudiargic                             | Epidystric/ Hypereutric        |
| Lamellic                              | Epic/ Endic                    |
| Albic                                 | Fractic                        |
| Ferric                                | Geric                          |
| Gypsic                                | Gibbsic                        |
| Calcic                                | Humic/ Ochric                  |
| Yermic/ Takyric                       | Magnesic                       |
| Skeletic                              | Nechic                         |
| Haplic                                | Nitic                          |
|                                       | Novic                          |
|                                       | Oxyaquic                       |
|                                       | Profondic                      |
|                                       | Pyric                          |
|                                       | Raptic                         |
|                                       | Saprolithic                    |
|                                       | Sodic                          |
|                                       | Solimovic                      |
|                                       | Technic/ Kalaic                |
|                                       | Toxic                          |
|                                       | Transportic                    |
|                                       | Vitric                         |
:::
:::
