# Diagnostic horizons, properties and materials {#sec-ch03}

::: callout-important
Before using the diagnostic horizons, properties and materials, please read the ['Rules for naming soils'](chapter-02.qmd#sec-ch02) (Chapter 2)
:::

Throughout the following text, references to the RSGs defined in [Chapter 4](chapter-04.qmd) and to the diagnostics listed elsewhere in this Chapter are shown in *italics*.

## Diagnostic horizons {#sec-diagh}

**Diagnostic horizons** are characterized by a combination of attributes that reflect widespread, common results of soil-forming processes. Their features can be observed or measured in the field or the laboratory and require a minimum or maximum expression to qualify as diagnostic. In addition, diagnostic horizons require a certain minimum thickness, thus forming a recognizable layer in the soil.

### Albic horizon {#sec-albich}

#### General description {#sec-albich-desc}

An albic horizon (from Latin *albus*, white) is a light-coloured horizon overlying an [*argic*](#sec-argich), [*natric*](#sec-natrh), [*plinthic*](#sec-plinth) or [*spodic horizon*](#sec-spodh) or forming part of a layer with [*stagnic properties*](#sec-stagnp). It has low contents of Fe and Mn (depleted from both oxidized and reduced forms) and of organic matter, and at least one of these substances has previously been present and was lost due to clay migration, podzolization, and/or redox processes caused by water stagnation.

#### Diagnostic criteria {#sec-albich-diag}

An albic horizon consists of [*mineral material*](#sec-minm) and

1.  consists of [*claric material*](#sec-claricm);\
    ***and***
2.  one or both of the following:
    a.  overlies an [*argic*](#sec-argich), [*natric*](#sec-natrh), [*plinthic*](#sec-plinth) or [*spodic horizon*](#sec-spodh); ***or***
    b.  forms part of a layer with [*stagnic properties*](#sec-stagnp);\
        ***and***
3.  has a thickness of ≥ 1 cm.

#### Additional information {#sec-albich-info}

Albic horizons are normally overlain by humus-enriched surface layers but may also be at the mineral soil surface as a result of erosion or artificial removal of the surface layer. Many albic horizons represent a strong expression of eluviation and are therefore called eluvial horizons. In sandy materials, albic horizons can reach considerable thickness, up to several metres, especially in humid tropical regions, and underlying diagnostic horizons may be hard to establish. Albic horizons generally have a weakly expressed soil aggregate structure, a single grain structure or a massive structure. Albic horizons are widely depleted from Fe, both the oxidized and the reduced forms, and typically do not show red colours when applying α,α-dipyridyl solution.

#### Relationships with some other diagnostics {#sec-albich-reln}

While the albic horizon is the result of soil-forming processes, the [*claric material*](#sec-claricm) is only defined by colour criteria, and layers with [*claric material*](#sec-claricm) may or may not have undergone soil-forming processes. The definition of the albic horizon uses the [*argic*](#sec-argich), [*natric*](#sec-natrh), [*plinthic*](#sec-plinth) or [*spodic horizon*](#sec-spodh) or the [*stagnic properties*](#sec-stagnp) as criterion. The definitions of the [*spodic horizon*](#sec-spodh) and of the [retic](#sec-reticp)and [*stagnic properties*](#sec-stagnp), in turn, use the [*claric material*](#sec-claricm) as criterion.

Many albic horizons that were formed by stagnant water do not show active [*reducing conditions*](#sec-reducc).

### Anthraquic horizon {#sec-anthh}

#### General description {#sec-anthh-desc}

An anthraquic horizon (from Greek *anthropos*, human being, and Latin *aqua*, water) is a surface horizon that results from wet-field cultivation and comprises a *puddled layer* and a *plough pan*.

#### Diagnostic criteria {#sec-anthh-diag}

An anthraquic horizon is a surface horizon consisting of [*mineral material*](#sec-minm) and has:

1.  a puddled layer with the following Munsell colours, moist, in ≥ 80% of its exposed area:
    a.  a hue of 7.5YR or yellower, a value of ≤ 4 and a chroma of ≤ 2; ***or***
    b.  a hue of GY, B or BG and a value of ≤ 4;\
        ***and***
2.  a plough pan underlying the puddled layer, with all of the following:
    a.  one or both of the following:
        i.  a platy structure in ≥ 25% of its volume; ***or***
        ii. a massive structure in ≥ 25% of its volume;\
            ***and***
    b.  a bulk density higher by ≥ 10% (relative) than that of the puddled layer;\
        ***and***
    c.  oximorphic features, in ≥ 5% of its exposed area, that:
        i.  are predominantly on biopore walls and, if soil aggregates are present, predominantly on or adjacent to aggregate surfaces; ***and***
        ii. have a Munsell colour hue ≥ 2.5 units redder and a chroma ≥ 1 unit higher, moist, than the surrounding material;\
            ***and***
3.  a thickness of ≥ 15 cm.

#### Field identification {#sec-anthh-flid}

An anthraquic horizon shows evidence of reduction and oxidation owing to flooding for part of the year. When not flooded, it is very dispersible and has a loose packing of sorted small soil aggregates. The plough pan is compact, has a platy or massive structure and a very low infiltration rate. It has a reduced matrix and yellowish-brown, brown or reddish-brown oximorphic features along cracks and root channels due to oxygen release from plant roots.

#### Relationships with some other diagnostics {#sec-anthh-reln}

After a long time of wet-field cultivation, a [*hydragric horizon*](#sec-hydrh) develops under the anthraquic horizon.

### Argic horizon {#sec-argich}

#### General description {#sec-argich-desc}

An argic horizon (from Latin *argilla*, white clay) is a subsurface horizon with a distinctly higher clay content than the overlying horizon. The textural differentiation may be caused by:

-   an illuvial accumulation of clay mineral
-   predominant pedogenic formation of clay minerals in the subsoil
-   destruction of clay minerals in the overlying horizon
-   selective surface erosion of clay minerals
-   upward movement of coarser particles due to swelling and shrinking
-   biological activity, or
-   a combination of two or more of these different processes.

Iron (hydr)oxides are often accumulated or formed together with clay minerals, giving the argic horizon a redder hue and/or a higher chroma.

A clay-richer stratum overlain by a clay-poorer stratum may resemble an argic horizon. However, a textural difference due only to a [*lithic discontinuity*](#sec-lithd) does not qualify as an argic horizon. In some soils, we may have both: a clay-poorer stratum overlying a clay-richer stratum and additionally a textural differentiation caused by soil-forming processes.

#### Diagnostic criteria {#sec-argich-diag}

An argic horizon consists of [*mineral material*](#sec-minm) and:

1.  has a texture class of loamy sand or finer and ≥ 8% clay;\
    ***and***
2.  one or both of the following:
    a.  has an overlying coarser-textured layer with all of the following:
        i.  the coarser-textured layer is not separated from the argic horizon by a [*lithic discontinuity*](#sec-lithd); ***and***
        ii. if the coarser-textured layer directly overlies the argic horizon, its lowermost sublayer does not form part of a plough layer; ***and***
        iii. if the coarser-textured layer does not directly overlie the argic horizon, the transitional horizon between the coarser-textured layer and the argic horizon has a thickness of ≤ 15 cm; ***and***
        iv. if the coarser-textured layer has \< 15% clay, the argic horizon has ≥ 6% (absolute) more clay; ***and***
        v.  if the coarser-textured layer has ≥ 15 and \< 50% clay, the ratio of clay in the argic horizon to that of the coarser-textured layer is ≥ 1.4; ***and***
        vi. if the coarser-textured layer has ≥ 50% clay, the argic horizon has ≥ 20% (absolute) more clay;\
            ***or***
    b.  has evidence of illuvial clay in one or more of the following forms:
        i.  clay bridges connecting ≥ 15% of the sand grains; ***or***
        ii. clay coatings covering ≥ 15% of the surfaces of soil aggregates, coarse fragments and/or biopore walls; ***or***
        iii. in thin sections, oriented clay bodies that constitute ≥ 1% of the section and and that have not been transported laterally after they had been formed; ***or***
        iv. a ratio of fine clay to total clay in the argic horizon greater by ≥ 1.2 times than the ratio in the overlying coarser-textured layer;\
            ***and***
3.  both of the following:
    a.  does not form part of a [*natric horizon*](#sec-natrh); ***and***
    b.  does not form part of a [*spodic horizon*](#sec-spodh), unless illuvial clay is evidenced by one or more of the diagnostic criteria listed under 2.b;\
        ***and***
4.  has a thickness of one-tenth or more of the thickness of the overlying [*mineral material*](#sec-minm), if present, and one of the following:
    a.  ≥ 7.5 cm (if composed of lamellae: combined thickness within 50 cm of the upper limit of the uppermost lamella) if the argic horizon has a texture class of sandy loam or finer; ***or***
    b.  ≥ 15 cm (if composed of lamellae: combined thickness within 50 cm of the upper limit of the uppermost lamella).

#### Field identification {#sec-argich-flid}

Textural differentiation and the evidence of clay illuviation are the main features of argic horizons. The recognition of clay coatings and clay bridges is explained in Annex 1 ([Chapter 8.4.23](annex-01-field-guide.qmd#sec-a1-coats)).

In shrink-swell soils, clay coatings at soil aggregate surfaces are easily confused with pressure faces (stress cutans). Pressure faces do not differ in colour from the original aggregate and do not occur on coarse fragments and biopore walls.

#### Additional information {#sec-argich-info}

The illuvial character of an argic horizon can best be established using thin sections. Diagnostic illuvial argic horizons show areas with oriented clay bodies that constitute on average ≥ 1% of the entire cross-section. Other tests involved are particle-size distribution analysis to determine the increase in clay content over a specified depth, and the fine clay/total clay ratio. In illuvial argic horizons, the fine clay to total clay ratio is larger than in the overlying horizons, due to preferential transport of fine clay particles.

If the soil shows a lithic discontinuity directly over the argic horizon, or if the surface horizon has been removed by erosion, or if a plough layer directly overlies the argic horizon, then the illuvial nature must be clearly established (diagnostic criterion 2.b).

The argic horizon may be subdivided into several lamellae with coarser-textured layers in between.

#### Relationships with some other diagnostics {#sec-argich-reln}

Argic horizons are normally situated below eluvial horizons i.e. horizons from which clay minerals have been removed, commonly together with oxides and some organic matter. Although initially formed as a subsurface horizon, argic horizons may occur at the mineral soil surface as a result of erosion or removal of the overlying horizons. Afterwards, new sediments may be added.

Some argic horizons fulfil all the diagnostic criteria of the [*ferralic horizon*](#sec-feralh). Ferralsols must have a [*ferralic horizon*](#sec-feralh) and may have an argic horizon as well, which may or may not overlap with the [*ferralic horizon*](#sec-feralh); but if an argic horizon is present, it must have in its upper 30 cm: \< 10% water-dispersible clay or a ΔpH (pH~KCl~ - pH~water~) ≥ 0 or ≥ 1.4% [*soil organic carbon*](#sec-soc).

Argic horizons lack the sodium saturation characteristics of the [*natric horizon*](#sec-natrh).

Argic horizons in freely drained soils of high plateaus and mountains in humid tropical and subtropical regions may occur in association with [*sombric horizons*](#sec-sombrh).

### Calcic horizon {#sec-calch}

#### General description {#sec-calch-desc}

A calcic horizon (from Latin *calx*, lime) is a horizon in which secondary calcium carbonate (CaCO~3~) has accumulated as discontinuous concentrations. The accumulation usually occurs in subsurface layers, or more rarely, in surface horizons. The calcic horizon may contain primary carbonates as well.

#### Diagnostic criteria {#sec-calch-diag}

A calcic horizon:

1.  has a calcium carbonate equivalent of ≥ 15% (related to the fine earth plus accumulations of secondary carbonates of any size and any cementation class);\
    ***and***

2.  one or both of the following:

    a.  meets the diagnostic criteria of [*protocalcic properties*](#sec-protcp); ***or***
    b.  has a calcium carbonate equivalent of ≥ 5% higher (absolute, related to the fine earth plus accumulations of secondary carbonates of any size and any cementation class) than that of an underlying layer and no [*lithic discontinuity*](#sec-lithd) between the two layers; ***and***

3.  does not form part of a [*petrocalcic horizon*](#sec-petroh);\
    ***and***

4.  has a thickness of ≥ 15 cm.

#### Field identification {#sec-calch-flid}

Calcium carbonate can be identified in the field using 1 *M* hydrochloric acid (HCl) solution. The degree of effervescence is an indication of its amount (see Annex 1, [Chapter 8.4.25](annex-01-field-guide.qmd#sec-a1-carbs)).

Secondary carbonates are visible as usually discrete permanent accumulations (see Annex 1, [Chapter 8.4.25](annex-01-field-guide.qmd#sec-a1-carbs)). In the calcic horizon, they are predominantly non-cemented or less than moderately cemented. However, discontinuous accumulations, which are moderately or more cemented, may also occur.

Other possible indications of a calcic horizon are:

-   white, pinkish to reddish, or grey colours (if not overlapping horizons rich in organic carbon)
-   a low porosity (interaggregate porosity is usually less than in the horizon directly above, and possibly also less than in the horizon directly below).

When sampling, please make sure that the sample includes the accumulations of secondary carbonates in order to obtain the laboratory data for criteria 1 and 2.b.

#### Additional information {#sec-calch-info}

The determination of carbonates in the laboratory (Annex 2, [Chapter 9.9](annex-02-analytical-procedures.qmd#sec-a2-carbs)) uses an acid and measures the evolved CO~2~. It may stem from various carbonates, but the carbonate content is calculated as if it were only from calcium carbonate. This is called the **calcium carbonate equivalent**.

Determination of the amount of calcium carbonate (by mass) and the changes of calcium carbonate content within the soil profile are the main analytical criteria for establishing the presence of a calcic horizon. [*Lithic discontinuities*](#sec-lithd) and any change of water permeability may favour the formation of secondary carbonates. Determination of pH~water~ enables distinction between accumulations with a basic (*calcic*) character (pH 8-8.7) due to the dominance of CaCO~3~, and those with an ultrabasic (*non-calcic*) character (pH \> 8.7) because of the presence of Na~2~CO~3~ and/or MgCO~3~.

In addition, the analysis of thin sections may reveal the presence of calcium carbonate pedofeatures (e.g. nodules, pendents) or evidence of silicate epigenesis (calcite pseudomorphs after primary minerals), besides evidences of removal of carbonates in layers above or below the calcic horizon.

If the accumulation of soft carbonates is such that all or most of the soil structure and/or rock structure disappears and continuous concentrations of calcium carbonate prevail, the Hypercalcic qualifier is used.

#### Relationships with some other diagnostics {#sec-calch-reln}

When calcic horizons become continuously cemented with a cementation class of at least moderately cemented, transition takes place to the [*petrocalcic horizon*](#sec-petroh), the expression of which may be massive or platy. A calcic horizon and a [*petrocalcic horizon*](#sec-petroh) may overlie each other.

Accumulations of secondary carbonates, not qualifying for a calcic horizon, may fulfil the diagnostic criteria of [*protocalcic properties*](#sec-protcp), which are fulfilled by most calcic horizons as well. [*Calcaric material*](#sec-calcam) includes primary carbonates.

In dry regions and in the presence of sulfate-bearing soil or groundwater solutions, calcic horizons occur associated with [*gypsic horizons*](#sec-gypsih). Calcic and [*gypsic horizons*](#sec-gypsih) typically (but not always) occupy different positions in the soil profile because gypsum is more soluble than calcium carbonate, and they can normally be distinguished clearly from each other by a difference in crystal morphology. Gypsum crystals tend to be needle-shaped, usually visible to the naked eye, whereas pedogenic calcium carbonate crystals are much finer in size.

### Cambic horizon {#sec-cambh}

#### General description {#sec-cambh-desc}

A cambic horizon (from Latin *cambire*, to change) is a subsurface horizon showing evidence of soil formation that ranges from weak to relatively strong. The cambic horizon shows soil aggregate structure at least in half of the volume of the fine earth. If the underlying layer has the same parent material, the cambic horizon usually shows higher oxide and/or clay contents than this underlying layer and/or evidence of removal of carbonates and/or gypsum. The soil formation in a cambic horizon can also be established by contrast with one of the overlying mineral horizons that are generally richer in organic matter and therefore have a darker and/or less intense colour.

#### Diagnostic criteria {#sec-cambh-diag}

A cambic horizon consists of [*mineral material*](#sec-minm) and:

1.  has a texture class of
    a.  sandy loam or finer; ***or***
    b.  very fine sand or loamy very fine sand;\
        ***and***
2.  has soil aggregate structure in ≥ 50% (by volume);\
    ***and***
3.  shows evidence of soil formation in one or more of the following:
    a.  compared to the directly underlying layer, not separated from the cambic horizon by a [*lithic discontinuity*](#sec-lithd), one or more of the following:
        i.  if the underlying layer has a Munsell colour hue of 5YR or redder, a hue ≥ 2.5 units yellower, else a hue ≥ 2.5 units redder, all moist and in ≥ 90% of its exposed area; ***or***
        ii. a Munsell colour chroma ≥ 1 unit higher, moist and in ≥ 90% of its exposed area; ***or***
        iii. a clay content ≥ 4% (absolute) higher;\
             ***or***
    b.  compared to an overlying mineral layer, ≥ 5 cm thick and not separated from the cambic horizon by a [*lithic discontinuity*](#sec-lithd), one or more of the following:
        i.  a Munsell colour hue ≥ 2.5 units redder, moist and in ≥ 90% of its exposed area; ***or***
        ii. a Munsell colour value ≥ 1 unit higher, moist and in ≥ 90% of its exposed area; ***or***
        iii. a Munsell colour chroma ≥ 1 unit higher, moist and in ≥ 90% of its exposed area;\
             ***or***
    c.  compared to the directly underlying layer, not showing *gleyic properties* and not forming part of a *calcic* or *gypsic horizon*, evidence of removal of carbonates or gypsum by one or more of the following:
        i.  ≥ 5% (absolute) less calcium carbonate equivalent or ≥ 5% (absolute) less gypsum and no [*lithic discontinuity*](#sec-lithd) between this underlying layer and the cambic horizon; ***or***
        ii. [*protocalcic properties*](#sec-protcp) or [*protogypsic properties*](#sec-protgp) in the underlying layer but not in the cambic horizon;\
            ***or***
    d.  all of the following:
        i.  Fe~dith~ ≥ 0.1%; ***and***
        ii. a ratio between Fe~ox~ and Fe~dith~ of ≥ 0.1; ***and***
        iii. a Munsell colour hue of 2.5YR to 2.5Y and a chroma of \> 3, all moist and in ≥ 90% of its exposed area;\
             ***and***
4.  does not form part of a plough layer, does not form part of an [*albic*](#sec-albich), [*anthraquic*](#sec-anthh), [*argic*](#sec-argich), [*calcic*](#sec-calch), [*duric*](#sec-durich), [*ferralic*](#sec-feralh), [*fragic*](#sec-fragh), [*gypsic*](#sec-gypsih), [*hortic*](#sec-hortih), [*hydragric*](#sec-hydrh), [*irragric*](#sec-iragh), [*limonic*](#sec-limnh), [*mollic*](#sec-mollh), [*natric*](#sec-natrh), [*nitic*](#sec-nitich), [*petrocalcic*](#sec-petroh), [*petroduric*](#sec-petdh), [*petrogypsic*](#sec-petrgh), [*petroplinthic*](#sec-petplh), [*pisoplinthic*](#sec-pisoph), [*plaggic*](#sec-plaggh), [*plinthic*](#sec-plinth), [*pretic*](#sec-preth), [*salic*](#sec-salich), [*sombric*](#sec-sombrh), [*spodic*](#sec-spodh), [*umbric*](#sec-umbrich), [*terric*](#sec-terich), [*tsitelic*](#sec-tsith) or [*vertic horizon*](#sec-verth) and does not from part of a layer with [*andic properties*](#sec-andip);\
    ***and***
5.  has a thickness of ≥ 15 cm.

#### Additional characteristics {#sec-cambh-info}

In many cambic horizons, Fe oxides are formed, which give the horizon a redder hue and a higher chroma. However, if the parent material has much hematite, the formation of goethite in cooler and humid conditions usually makes it yellower.

Dissolution of carbonates or gypsum is a widespread feature of cambic horizons in both humid and semi-arid environments. In many cases, this may be proven by a lesser carbonate or gypsum content compared to the underlying layer. However, in some soils, especially in arid and semi-arid areas, this lesser content is not evident. In these soils, the presence of [protocalcic](#sec-protcp) or [*protogypsic properties*](#sec-protgp) in the underlying layer is a proof that carbonates or gypsum have been dissolved in the horizon above. On the other hand, such accumulations may also be caused by ascending groundwater in soils with [*gleyic properties*](#sec-gleyicp), and [*gleyic properties*](#sec-gleyicp) have to be excluded in the underlying layer for this comparison.

#### Relationships with some other diagnostics {#sec-cambh-reln}

The cambic horizon can be considered the predecessor of many other diagnostic horizons, all of which have specific properties that are not or only weakly expressed in the cambic horizon -- such as illuvial or residual accumulations, removal of substances other than carbonates or gypsum, accumulation of soluble components, or the development of specific soil structure like wedge-shaped aggregates.

Cambic horizons in freely drained soils of high plateaus and mountains in humid tropical and subtropical regions may occur in association with [*sombric horizons*](#sec-sombrh). The ratio between Fe~ox~ and Fe~dith~ differentiates the cambic horizon from the [*tsitelic horizon*](#sec-tsith) (higher ratio). The [*plinthic*](#sec-plinth) and the [*petroplinthic horizon*](#sec-petplh) have usually much higher Fe~dith~ contents.

### Chernic horizon {#sec-chernh}

#### General description {#sec-chernh-desc}

A chernic horizon (from Russian *chorniy*, black) is a relatively thick, well-structured, very dark-coloured surface horizon, with a high base saturation, a high animal activity and a moderate to high content of organic matter.

#### Diagnostic criteria {#sec-chernh-diag}

A chernic horizon is a surface horizon consisting of [*mineral material*](#sec-minm) and has:

1.  ≥ 50% (by volume, weighted average, related to the whole soil) of fine earth and does not consist of [*mulmic material*](#sec-mulm); ***and***
2.  single or in combination, in ≥ 90% (by volume):
    a.  granular structure; ***or***
    b.  subangular blocky structure with an average aggregate size of ≤ 2 cm; ***or***
    c.  cloddy structure or other structural elements created by agricultural practices;\
        ***and***
3.  ≥ 1% [*soil organic carbon*](#sec-soc);\
    ***and***
4.  one of the following:
    a.  in ≥ 90% of the exposed area of the entire horizon or of the subhorizons below any plough layer, a Munsell colour value of ≤ 3 moist, and ≤ 5 dry, and a chroma of ≤ 2 moist;\
        ***or***
    b.  all of the following:
        i.  ≥ 15 and \< 40% calcium carbonate equivalent; ***and***
        ii. in ≥ 90% of the exposed area of the entire horizon or of the subhorizons below any plough layer, a Munsell colour value of ≤ 3 and a chroma of ≤ 2, both moist; ***and***
        iii. ≥ 1.5% [*soil organic carbon*](#sec-soc);\
             ***or***
    c.  all of the following:
        i.  ≥ 40% calcium carbonate equivalent and/or a texture class of loamy sand or coarser; ***and***
        ii. in ≥ 90% of the exposed area of the entire horizon or of the subhorizons below any plough layer, a Munsell colour value of ≤ 5 and a chroma of ≤ 2, both moist; ***and***
        iii. ≥ 2.5% [*soil organic carbon*](#sec-soc);\
             ***and***
5.  if a layer is present that corresponds to the parent material of the chernic horizon and that has a Munsell colour value of ≤ 4, moist, ≥ 1% (absolute) more [*soil organic carbon*](#sec-soc) than this layer;\
    ***and***
6.  a base saturation (by 1 *M* NH~4~OAc, pH 7) of ≥ 50%;\
    ***and***
7.  a thickness of ≥ 30 cm.

#### Field identification {#sec-chernh-flid}

A chernic horizon may easily be identified by its blackish colour, caused by the accumulation of organic matter, its well-developed granular or subangular blocky structure, an indication of high base saturation (e.g. pH~water~ \> 6), and its thickness.

#### Relationships with some other diagnostics

The chernic horizon is a special case of the [*mollic horizon*](#sec-mollh) with a higher content of [*soil organic carbon*](#sec-soc), a lower chroma, generally better developed soil structure, a minimum content of fine earth and a greater minimum thickness. The upper limit of the content of [*soil organic carbon*](#sec-soc) is 20%, which is the lower limit for [*organic material*](#sec-orgm).

### Cohesic horizon {#sec-cohesh}

#### General description {#sec-cohesh-desc}

A cohesic horizon (from Latin *cohaerere*, to stick together) is a subsurface horizon with a massive structure or a subangular blocky structure. It is poor in organic matter and iron oxides, normally contains quartz, and the clay fraction is dominated by kaolinite. It is typical for old landscapes of the tropics with a seasonal climate.

#### Diagnostic criteria {#sec-cohesh-diag}

A cohesic horizon consists of [*mineral material*](#sec-minm) and:

1.  has \< 0.5% [*soil organic carbon*](#sec-soc); ***and***
2.  has ≥ 15% clay; ***and***
3.  has a CEC (by 1 *M* NH~4~OAc, pH 7) of \< 24 cmol~c~ kg^-1^ clay; ***and***
4.  has, single or in combination, a massive structure or a subangular blocky structure; ***and***
5.  is not cemented; ***and***
6.  has, when dry, a rupture-resistance class of at least hard; ***and***
7.  has a thickness of ≥ 10 cm.

#### Field identification {#sec-cohesh-flid}

Cohesic horizons are very resistant to penetration of knife or hammer and have a rupture-resistance class of hard to extremely hard when dry, becoming friable or firm when moist.

#### Additional information {#sec-cohesh-info}

Cohesic horizons have a porosity low enough to restrict root penetration, but drainage is usually not restricted. The low porosity is attributed to parallel orientation of kaolinite crystals and infilling of voids by clay particles. Usually, they have a bulk density higher than the over- and underlying layers. They are typically found directly below a surface horizon.

Many soils with the cohesic horizon have the Caráter coeso in the Brazilian system and have an apedal B horizon in the South African system. Cohesic horizons may also occur in paleosols.

#### Relationships with some other diagnostics {#sec-cohesh-reln}

Cohesic horizons may coincide with [ferralic](#sec-feralh) or, less widespread, with [*argic horizons*](#sec-argich). They differ strongly from [*nitic horizons*](#sec-nitich). Some cohesic horizons show active or relict [*stagnic properties*](#sec-stagnp) or overlie a [*plinthic*](#sec-plinth), [*pisoplinthic*](#sec-pisoph) or [*petroplinthic horizon*](#sec-petroh).

### Cryic horizon {#sec-cryich}

#### General description {#sec-cryich-desc}

A cryic horizon (from Greek *kryos*, cold, ice) is a perennially frozen soil horizon in [*mineral*](#sec-minm) or [*organic material*](#sec-orgm).

#### Diagnostic criteria {#sec-cryich-diag}

A cryic horizon has:

1.  continuously for ≥ 2 consecutive years one of the following:
    a.  massive ice, cementation by ice or readily visible ice crystals; ***or***
    b.  a soil temperature of \< 0 °C and insufficient water to form readily visible ice crystals;\
        ***and***
2.  a thickness of ≥ 5 cm.

#### Field identification {#sec-cryich-flid}

Cryic horizons occur in areas with permafrost and most of them show evidence of perennial ice segregation. Many of them are overlain by horizons with evidence of cryogenic alteration (mixed soil material, disrupted soil horizons, involutions, organic intrusions, frost heave, separation of coarse fragments from fine earth, cracks). Patterned surface features (earth hummocks, frost mounds, stone circles, stripes, nets and polygons) are common. To identify cryogenic alteration, a soil profile should intersect different elements of patterned ground, if present, or be wider than 2 m.

Soils that contain saline water do not freeze at 0 °C. In order to develop a cryic horizon, such soils must be cold enough to freeze.

#### Additional information {#sec-cryich-info}

Permafrost is defined as follows: layer of soil or rock, at some depth beneath the surface, in which the temperature has been continuously below 0 °C for at least some years. It exists where summer heating fails to reach the base of the layer of frozen ground (Arctic Climatology and Meteorology Glossary, National Snow and Ice Data Center, Boulder, USA).

Engineers distinguish between *warm* and *cold* permafrost. *Warm* permafrost has a temperature \> -2 °C and has to be considered unstable. *Cold* permafrost has a temperature of ≤ -2 °C and can be used more safely for construction purposes provided the temperature remains under control.

#### Relationships with some other diagnostics {#sec-cryich-reln}

Cryic horizons may fulfil the diagnostic criteria of [*histic*](#sec-histih), [*folic*](#sec-folich) or [*spodic horizons*](#sec-spodh) and may occur in association with [*salic*](#sec-salich), [*calcic*](#sec-calch), [*mollic*](#sec-mollh) or [*umbric horizons*](#sec-umbrich). In cold arid regions, [*yermic properties*](#sec-yermicp) may be present.

### Duric horizon {#sec-durich}

#### General description {#sec-durich-desc}

A duric horizon (from Latin *durus*, hard) is a subsurface horizon showing nodules or concretions (durinodes), cemented by silica (SiO~2~), presumably in the form of opal and microcrystalline silica. Many durinodes have carbonate coatings. It may also contain fragments of a broken-up [*petroduric horizon*](#sec-petdh).

#### Diagnostic criteria {#sec-durich-diag}

A duric horizon consists of [*mineral material*](#sec-minm) and has:

1.  ≥ 10% (by volume, related to the whole soil) of nodules or concretions (durinodes) and/or of fragments of a broken-up [*petroduric horizon*](#sec-petdh) with all of the following:
    a.  have ≥ 1% (by exposed area of the nodules or concretions) accumulation of visible secondary silica; ***and***
    b.  when air-dry, \< 50% (by volume) slake in 1 *M* HCl, even after prolonged soaking, ***and***
    c.  when air-dry, ≥ 50% (by volume) slake in hot concentrated KOH or hot concentrated NaOH, at least if alternating with 1 M HCl; ***and***
    d.  are cemented, at least partially by secondary silica, with a cementation class of at least weakly cemented, both before and after treatment with acid; ***and***
    e.  have a diameter of ≥ 1 cm; ***and***
2.  a thickness of ≥ 10 cm.

#### Field identification {#sec-durich-flid}

The identification of secondary silica is described in Annex 1 ([Chapter 8.4.27](annex-02-field-guide.qmd#sec-a1-silica)). The durinodes are usually hard (high penetration resistance). Many durinodes are brittle when moist, both before and after treatment with acid.

#### Additional information {#sec-durich-info}

Dry durinodes do not slake appreciably in water, but prolonged soaking can result in the breaking-off of very thin platelets and some slaking. In cross-section, most durinodes are roughly concentric, and concentric stringers of opal may be visible under a hand lens.

If both silica and carbonates are present as cementing agents, the durinodes will only slake if hot concentrated KOH or NaOH (to dissolve the silica) are alternated with HCl (to dissolve the carbonates). If carbonates are absent, KOH or NaOH alone will be able to slake the durinodes.

#### Relationships with some other diagnostics {#sec-durich-reln}

In arid regions, duric horizons occur in association with [*gypsic*](#sec-gypsih), [*petrogypsic*](#sec-petrgh), [*calcic*](#sec-calch) and [*petrocalcic horizons*](#sec-petroh). A horizon continuously cemented by silica is a [*petroduric horizon*](#sec-petdh).

### Ferralic horizon {#sec-feralh}

#### General description {#sec-feralh-desc}

A ferralic horizon (from Latin *ferrum*, iron, and *alumen*, alum) is a subsurface horizon resulting from long and intense weathering. The clay fraction is dominated by low-activity clays and contains various amounts of resistant minerals such as (hydr-)oxides of Fe, Al, Mn and Ti. There may be a marked residual accumulation of quartz in the silt or sand fractions.

#### Diagnostic criteria {#sec-feralh-diag}

A ferralic horizon consists of [*mineral material*](#sec-minm) and:

1.  has a texture class of sandy loam or finer and ≥ 8% clay; and
2.  has \< 80% (by volume, related to the whole soil) coarse fragments, [*pisoplinthic*](#sec-pisoph) concretions or nodules or remnants of a [*petroplinthic horizon*](#sec-petplh); and
3.  has a CEC (by 1 *M* NH~4~OAc, pH 7) of \< 16 cmol~c~ kg^-1^ clay; and
4.  has \< 10% (by grain count) easily weatherable minerals in the 0.05--0.2 mm fraction; and
5.  does not have [*andic*](#sec-andip) or [*vitric properties*](#sec-vitricp); and
6.  6\. has a thickness of ≥ 30 cm.

#### Field identification {#sec-feralh-flid}

Ferralic horizons are associated with old and stable landforms. The macrostructure is moderate to weak but typical ferralic horizons have a strong microaggregation.

Ferralic horizons rich in Fe oxides (especially rich in hematite) have usually a friable rupture-resistance class, moist. Disrupted dry soil material flows like flour between the fingers. Lumps of ferralic horizons are usually relatively light in mass because of the low bulk density. Many ferralic horizons give a hollow sound when tapped, indicating high porosity. In some ferralic horizons, the high porosity is the result of termite activity. Generally, the voids between the microaggregates provide a high porosity.

If the ferralic horizon has less hematite and a more yellowish colour, it typically shows a higher bulk density and a lower porosity. It is massive or has a weak subangular blocky structure and a firm rupture-resistance class, moist.

Indicators of clay illuviation such as clay coatings are generally absent or rare, as are pressure faces and other stress features. Boundaries of a ferralic horizon are normally gradual to diffuse, and little variation in colour or particle-size distribution within the horizon can be detected.

#### Additional information {#sec-feralh-info}

As an alternative to the weatherable minerals requirement, a total reserve of bases (TRB = exchangeable plus mineral calcium \[Ca\], magnesium \[Mg\], potassium \[K\] and sodium \[Na\]) of \< 25 cmol~c~ kg^-1^ soil may be indicative.

Ferralic horizons normally have \< 10% water-dispersible clay. Occasionally they may have more waterdispersible clay, but if so, they have a ΔpH (pH~KCl~ - pH~water~) ≥ 0 or a relatively high content of organic carbon.

Examples of easily weatherable minerals are all 2:1 phyllosilicates, chlorites, sepiolites, palygorskites, allophanes, 1:1 trioctahedral phyllosilicates (serpentines), feldspars, feldspathoids, ferromagnesian minerals, glass, zeolites, dolomite and apatite. The intent of the term weatherable minerals is to include those minerals that are unstable in humid climates compared with other minerals, such as quartz and 1:1 clay minerals, but that are more resistant to weathering than calcite @soilsurveystaff1999.

In thin sections, ferralic horizons have generally an undifferentiated b-fabric due to the isotropic behaviour of Fe oxides. The groundmass has commonly a granular microstructure, with a porosity composed by packing pores and star-like vughs, besides channels and chambers due to a strong bioturbation.

#### Relationships with some other diagnostics {#sec-feralh-reln}

Some [*argic horizons*](#sec-argich) fulfil all the diagnostic criteria of the ferralic horizon.

Al~ox~, Fe~ox~, Si~ox~ in ferralic horizons are very low, which sets them apart from the [*nitic horizons*](#sec-nitich) and layers with [*andic*](#sec-andip) or [*vitric properties*](#sec-vitricp).

Some [*cambic horizons*](#sec-cambh) have a low CEC; however, the amount of weatherable minerals or the TRB is too high for a ferralic horizon. Such horizons represent an advanced stage of weathering and a transition to the ferralic horizon.

Ferralic horizons in freely drained soils of high plateaus and mountains in humid tropical and subtropical regions may occur in association with [*sombric horizons*](#sec-sombrh).

Due to redox processes, ferralic horizons may develop into [*plinthic horizons*](#sec-plinth). Most [*plinthic horizons*](#sec-plinth) also fulfil the diagnostic criteria of ferralic horizons.

### Ferric horizon {#sec-ferich}

#### General description {#sec-ferich-desc}

A ferric horizon (from Latin *ferrum*, iron) has formed by redox processes, usually caused by stagnant water, which may be active or relict, and shows redoximorphic features. The segregation of Fe (or Fe and Mn) has advanced to such an extent that oximorphic features (coarse masses or discrete concretions and/or nodules) have formed inside soil aggregates, and the matrix between them is largely depleted of Fe and Mn. They do not necessarily have enhanced Fe (or Fe and Mn) contents, but Fe (or Fe and Mn) are concentrated in the oximorphic features. Generally, such segregation leads to poor aggregation of the soil particles in Fe- and Mn-depleted zones and a compaction of the horizon. It mainly occurs in old landscapes.

#### Diagnostic criteria {#sec-ferich-diag}

A ferric horizon consists of [*mineral material*](#sec-minm) and:

1.  consists of one or more subhorizons with one or both of the following:
    a.  ≥ 15% of its exposed area occupied by coarse (\> 20 mm, average length of the greatest dimension) masses inside soil aggregates that are black or have a Munsell colour hue redder than 7.5YR and a chroma of ≥ 5, both moist; ***or***
    b.  ≥ 5% of its exposed area (related to the fine earth plus concretions and/or nodules of any size and cementation class) occupied by concretions and/or nodules with a cementation class of at least weakly cemented, a reddish and/or blackish colour and a diameter of \> 2 mm; ***and***
2.  does not form part of a [*petroplinthic*](#sec-petroh), [*pisoplinthic*](#sec-pisoph) or [*plinthic horizon*](#sec-plinth); ***and***
3.  has a thickness of ≥ 15 cm.

#### Relationships with some other diagnostics {#sec-ferich-reln}

In tropical or subtropical regions, ferric horizons may grade laterally into [*plinthic horizons*](#sec-plinth). In [*plinthic horizons*](#sec-plinth), the amount of oximorphic features reaches ≥ 15% (by exposed area). Additionally, in [*plinthic horizons*](#sec-plinth), a certain content of Fe~dith~ is exceeded and/or it changes irreversibly to a continuously cemented layer on exposure to repeated drying and wetting with free access of oxygen. If the amount of concretions and/or nodules with a cementation class of at least moderately cemented reaches ≥ 40% (by exposed area), it is a [*pisoplinthic horizon*](#sec-pisoph).

### Folic horizon {#sec-folich}

#### General description {#sec-folich-desc}

A folic horizon (from Latin *folium*, leaf) consists of well-aerated [*organic material*](#sec-orgm). It develops at the soil surface. In places, it may be covered by [*mineral material*](#sec-minm). Folic horizons predominantly occur in cool climate or at high elevation.

#### Diagnostic criteria {#sec-folich-diag}

A folic horizon consists of [*organic material*](#sec-orgm) and:

1.  is saturated with water for \< 30 consecutive days in most years and is not drained; ***and***

2.  has a thickness of ≥ 10 cm.

#### Relationships with some other diagnostics {#sec-folich-reln}

The folic horizon has characteristics similar to the [*histic horizon*](#sec-histih). However, the [*histic horizon*](#sec-histih) forms while saturated with water consecutively for at least 30 days in most years, which causes a completely different vegetation and therefore a different character of the [*organic material*](#sec-orgm).

The [*organic material*](#sec-orgm) sets the folic horizon apart from [*chernic*](#sec-chernh), [*mollic*](#sec-mollh) or [*umbric horizons*](#sec-umbrich), which consist of [*mineral material*](#sec-minm). Folic horizons may show [*andic*](#sec-andip) or [*vitric properties*](#sec-vitricp).

### Fragic horizon {#sec-fragh}

#### General description {#sec-fragh-desc}

A fragic horizon (from Latin *fragilis*, fragile) is a natural, predominantly non-cemented subsurface horizon with large soil aggregates and a porosity pattern such that roots and percolating water penetrate the soil only in between these aggregates. The natural character excludes plough pans and surface traffic pans.

#### Diagnostic criteria {#sec-fragh-diag}

A fragic horizon consists of [*mineral material*](#sec-minm) and:

1.  ≥ 60% (by volume) consist, single or in combination, of prismatic, columnar, angular or subangular blocky soil aggregates that are without coarse roots and that have an average horizontal spacing (aggregate centre to aggregate centre) of ≥ 10 cm; ***and***
2.  shows evidence of soil formation as defined in criterion 3 of the [*cambic horizon*](#sec-cambh), at least on the faces of the soil aggregates; ***and***
3.  the soil material in between the soil aggregates and ≥ 50% of the volume of the aggregated soil are not cemented; ***and***
4.  the non-cemented parts do not cement upon repeated drying and wetting; ***and***
5.  the non-cemented aggregated parts have a brittle manner of failure and a rupture-resistance class, moist, of at least firm; ***and***
6.  has \< 0.5% [*soil organic carbon*](#sec-soc); ***and***
7.  does not show effervescence after adding a 1 *M* HCl solution; ***and***
8.  has a thickness of ≥ 15 cm.

#### Field identification {#sec-fragh-flid}

A fragic horizon has a prismatic and/or blocky structure. In some fragic horizons, the soil aggregates have a high bulk density. In others, the inner parts of the aggregates may have a relatively high total porosity but, as a result of a dense outer rim, there is no continuity between the pores within and outside the aggregates. Between the prisms or the angular blocks, a weaker aggregate structure or a massive structure and mostly also a lighter soil colour is found. The result is a closed box system with ≥ 60% of the soil volume that cannot be explored by roots and is not percolated by water. Possible reasons for the dense outer rim are: clay coatings, swelling and shrinking, or the pressure of the roots growing only vertically.

It is essential that the required soil volume is inspected from both vertical and horizontal sections; horizontal sections often reveal a polygonal pattern. Three or four such polygons (or a cut up to 1 m^2^) are sufficient to test the volumetric basis for the definition of the fragic horizon.

Fragic horizons are commonly loamy, but loamy sand and clay textures are not excluded. In the latter case, the clay mineralogy is dominantly kaolinitic.

The aggregates have commonly a penetration resistance ≥ 4 MPa at field capacity.

The fragic horizon has little faunal activity, except occasionally between the aggregates.

#### Relationships with some other diagnostics {#sec-fragh-reln}

A fragic horizon may underlie (but not necessarily directly) an [*albic*](#sec-albich), [*cambic*](#sec-cambh), [*spodic*](#sec-spodh) or [*argic horizon*](#sec-argich), unless the soil has been truncated. It can overlap partly or completely with an [*argic horizon*](#sec-argich), and if so, the fragic horizon may show [*retic properties*](#sec-reticp) or [*albeluvic glossae*](#sec-albgl). Many fragic horizons have [*reducing conditions*](#sec-reducc) and [*stagnic properties*](#sec-stagnp).

Contrary to fragic horizons, [*plinthic horizons*](#sec-plinth) will cement upon repeated drying and wetting. Contrary to fragic horizons, many other root-restricting horizons are cemented.

### Gypsic horizon {#sec-gypsih}

#### General description {#sec-gypsih-desc}

A gypsic horizon (from Greek *gypsos*, gypsum) is a non-cemented horizon containing accumulations of secondary gypsum (CaSO~4~·2H~2~O) in various forms. It may be a surface or a subsurface horizon.

#### Diagnostic criteria {#sec-gypsih-diag}

A gypsic horizon consists of [*mineral material*](#sec-minm) and:

1.  has ≥ 5% gypsum (related to the fine earth plus accumulations of secondary gypsum of any size and any cementation class); ***and***
2.  has one or both of the following:
    a.  meets the diagnostic criteria of [*protogypsic properties*](#sec-protgp); ***or***
    b.  a gypsum content of ≥ 5% higher (absolute, related to the fine earth plus accumulations of secondary gypsum of any size and any cementation class) than that of an underlying layer and no [*lithic discontinuity*](#sec-lithd) between the two layers; ***and***
3.  has a product of thickness (in centimetres) times gypsum content (percentage, by mass) of ≥ 150; ***and***
4.  does not form part of a [*petrogypsic horizon*](#sec-petrgh); ***and***
5.  has a thickness of ≥ 15 cm.

#### Field identification {#sec-gypsih-flid}

How to recognize secondary gypsum is described in Annex 1 ([Chapter 8.4.26](annex-01-field-guide.qmd#sec-a1-gypsum)). The accumulation may be in distinct form or flour-like. The latter gives the gypsic horizon a massive structure.

Gypsum crystals may be visually mistaken for quartz. Gypsum is soft and can easily be scratched with a knife or broken between thumbnail and forefinger. Quartz is hard and cannot be broken except by hammering.

#### Additional information {#sec-gypsih-info}

The recommended procedure to determine gypsum in the laboratory (Annex 2, [Chapter 9.10](annex-02-analytical-procedures.qmd#sec-a2-gypsum)) also extracts anhydrite, which is considered to be mainly primary.

Thin section analysis is helpful to establish the presence of secondary gypsum, as individual gypsic pedofeatures or as generalized accumulations in the groundmass.

If the accumulation of gypsum becomes such that all or most of the soil structure and/or rock structure disappears and continuous concentrations of gypsum prevail, the Hypergypsic qualifier is used.

#### Relationships with some other diagnostics {#sec-gypsih-reln}

When gypsic horizons become continuously cemented, transition takes place to the [*petrogypsic horizon*](#sec-petrgh), the expression of which may be as massive or platy structures. A gypsic horizon and a [*petrogypsic horizon*](#sec-petrgh) may overlie each other. Accumulations of secondary gypsum, not qualifying for a gypsic horizon, may fulfil the diagnostic criteria of [*protogypsic properties*](#sec-protgp), which are fulfilled by most gypsic horizons as well. [*Gypsiric material*](#sec-gyspicm) includes primary gypsum.

In dry regions, gypsic horizons may be associated with [*calcic*](#sec-calch) and/or [*salic horizons*](#sec-salich). [*Calcic*](#sec-calch) and gypsic horizons usually occupy distinct positions in the soil profile as the solubility of calcium carbonate is less than that of gypsum. They can normally be distinguished clearly from each other by the morphology (see [*calcic horizon*](#sec-calch)). [*Salic*](#sec-salich) and gypsic horizons also occupy different positions in the profile due to different solubilities.

### Histic horizon {#sec-histih}

#### General description {#sec-histih-desc}

A histic horizon (from Greek *histos*, tissue) consists of poorly aerated [*organic material*](#sec-orgm). It develops at the soil surface. In places, it may be covered by [*mineral material*](#sec-minm).

#### Diagnostic criteria {#sec-histih-diag}

A histic horizon consists of [*organic material*](#sec-orgm) and:

1.  is saturated with water for ≥ 30 consecutive days in most years or is drained; ***and***
2.  has a thickness of ≥ 10 cm,

#### Relationships with some other diagnostics {#sec-histih-reln}

Histic horizons have characteristics similar to the [*folic horizon*](#sec-folich). However, the [*folic horizon*](#sec-folich) is consecutively saturated with water for less than thirty days in most years, which causes a completely different vegetation and therefore a different character of the [*organic material*](#sec-orgm). Histic horizons may show [*andic*](#sec-andip) or [*vitric properties*](#sec-vitricp).

### Hortic horizon {#sec-hortih}

#### General description {#sec-hortih-desc}

A hortic horizon (from Latin *hortus*, garden) is a mineral surface horizon created by the human activities of deep cultivation, intensive fertilization and/or long-continued application of human and animal wastes and other organic residues (e.g. manures, kitchen refuse, compost and night soil).

#### Diagnostic criteria {#sec-hortih-diag}

A hortic horizon is a surface horizon consisting of [*mineral material*](#sec-minm) and has:

1.  a Munsell colour value and chroma of ≤ 3, moist; ***and***
2.  ≥ 1% [*soil organic carbon*](#sec-soc); ***and***
3.  ≥ 120 mg kg^-1^ P in the Mehlich-3 extract in the upper 20 cm; ***and***
4.  a base saturation (by 1 *M* NH~4~OAc, pH 7) of ≥ 50%; *and*
5.  ≥ 25% (by exposed area, weighted average) of animal pores, coprolites or other traces of soil animal activity; ***and***
6.  a thickness of ≥ 20 cm.

#### Field identification {#sec-hortih-flid}

The hortic horizon is thoroughly mixed. Potsherds and other artefacts are common, although often abraded. Tillage marks or evidence of mixing of the soil can be present.

#### Additional information {#sec-hortih-info}

120 mg kg^-1^ P in the Mehlich-3 extract roughly correspond to 43.6 mg kg^-1^ P or 100 mg kg^-1^ P~2~O~5~ in the Olsen extract [@kabala2018], which was the requirement in former editions of WRB.

#### Relationships with some other diagnostics {#sec-hortih-reln}

Some hortic horizons may also fulfil the diagnostic criteria of a [*pretic*](#sec-preth), [*terric*](#sec-terich), [*mollic*](#sec-mollh) or [*chernic horizon*](#sec-chernh).

### Hydragric horizon {#sec-hydrh}

#### General description {#sec-hydrh-desc}

A hydragric horizon (from Greek *hydor*, water, and Latin *ager*, field) is a subsurface horizon that results from wet-field cultivation.

#### Diagnostic criteria {#sec-hydrh-diag}

A hydragric horizon consists of [*mineral material*](#sec-minm) and:

1.  is overlain by an anthraquic horizon; ***and***
2.  consists of one or more subhorizons and each of them has one or more of the following:
    a.  reductimorphic features with a Munsell colour value of ≥ 4 and a chroma of ≤ 2, both moist, around biopore walls; ***or***
    b.  ≥ 15% (by exposed area) oximorphic features that:
        i.  are predominantly inside soil aggregates; ***and***
        ii. have a Munsell colour hue ≥ 2.5 units redder and a chroma ≥ 1 unit higher, moist, than the surrounding material; ***or***
    c.  ≥ 15% (by exposed area) oximorphic features that:
        i.  are predominantly on biopore walls and, if soil aggregates are present, predominantly on or adjacent to aggregate surfaces; ***and***
        ii. have a Munsell colour hue ≥ 2.5 units redder and a chroma ≥ 1 unit higher, moist, than the surrounding material; ***or***
    d.  Fe~dith~ ≥ 1.5 times and/or Mn~dith~ ≥ 3 times that of the weighted average of the puddled layer of the overlying anthraquic horizon; ***and***
3.  has a thickness of ≥ 10 cm.

#### Field identification {#sec-hydrh-flid}

The hydragric horizon occurs below the plough pan of an [*anthraquic horizon*](#sec-anthh). The features listed as part of diagnostic criterion 2 rarely occur altogether in the same subhorizon but are commonly distributed over several subhorizons. Major subhorizons have reductimorphic features in pores with a Munsell colour hue of 2.5Y or yellower and a chroma of ≤ 2, both moist, and/or concentrations of Fe and/or Mn oxides inside soil aggregates as a result of oxidizing conditions. It usually shows grey coatings on soil aggregate surfaces, consisting of clay, fine silt and organic matter.

#### Additional information {#sec-hydrh-info}

Reduced manganese and/or iron move down slowly through the plough pan of the overlying [*anthraquic horizon*](#sec-anthh) into the hydragric horizon; the mangenese tending to move further than the iron. Within the hydragric horizon, manganese and iron migrate further into the interiors of the soil aggregates where they are oxidized. In the lower part, subhorizons may be influenced by groundwater.

#### Relationships with some other diagnostics {#sec-hydrh-reln}

The hydragric horizon underlies an [*anthraquic horizon*](#sec-anthh).

### Irragric horizon {#sec-iragh}

#### General description {#sec-iragh-desc}

An irragric horizon (from Latin irrigare, to irrigate, and ager, field) is a [*mineral*](#sec-minm) surface horizon that builds up gradually through continuous application of irrigation water with substantial amounts of sediments, often including artefacts and a significant amount of organic matter.

#### Diagnostic criteria {#sec-iragh-diag}

An irragric horizon is a surface horizon consisting of [*mineral material*](#sec-minm) and:

1.  has, single or in combination, in ≥ 90% (by volume):
    a.  soil aggregate structure; ***or***
    b.  cloddy structure or other structural elements created by agricultural practices; ***and***
2.  has one or both of the following:
    a.  a clay content ≥ 10% (relative) and ≥ 3% (absolute) higher than that of the layer directly buried by the irragric horizon; ***or***
    b.  a fine clay content ≥ 10% (relative) and ≥ 3% (absolute) higher than that of the layer directly buried by the irragric horizon; ***and***
3.  has differences in medium sand contents, fine sand contents, very fine sand contents, silt contents, clay contents and carbonate contents of \< 20% (relative) or \< 4% (absolute) between subhorizons; ***and***
4.  has both of the following:
    a.  ≥ 0.3% [*soil organic carbon*](#sec-soc); ***and***

    b.  a weighted average of ≥ 0.5% [*soil organic carbon*](#sec-soc); ***and***
5.  has ≥ 25% (by exposed area, weighted average) of animal pores, coprolites or other traces of soil animal activity; ***and***
6.  shows evidence that the land surface has been raised; ***and***
7.  has a thickness of ≥ 20 cm.

#### Field identification {#sec-iragh-flid}

Soils with an irragric horizon show evidence of surface raising, which may be inferred from either field observations or from historical records. The irragric horizon shows evidence of considerable animal activity. The lower boundary is clear; and irrigation deposits or buried soils may be present below.

#### Relationships with some other diagnostics {#sec-iragh-reln}

Due to continuous ploughing, irragric horizons lack the continuous stratification of [*fluvic material*](#sec-fluvicm). Some irragric horizons may also qualify as [*mollic*](#sec-mollh) or [*umbric horizons*](#sec-umbrich), depending on their base saturation.

### Limonic horizon {#sec-limnh}

#### General description {#sec-limnh-desc}

A limonic horizon (from Greek *leimon*, meadow) develops in layers with [*gleyic properties*](#sec-gleyicp) and oximorphic features. Reduced Fe and/or Mn move upwards with ascending groundwater, are oxidized and accumulate to such an extent that at least some parts of the accumulation zones are cemented. It is traditionally called bog iron.

#### Diagnostic criteria {#sec-limnh-diag}

A limonic horizon:

1.  has ≥ 50% (by exposed area) oximorphic features that are
    a.  black, surrounded by lighter-coloured material, ***or***
    b.  have a Munsell colour hue ≥ 2.5 units redder and a chroma ≥ 1 unit higher, moist, than the surrounding material ***or***
    c.  have a Munsell colour hue ≥ 2.5 units redder and a chroma ≥ 1 unit higher, moist, than the matrix of the directly underlying layer; ***and***
2.  the oximorphic features are one or both of the following:
    a.  predominantly on (former) biopore walls and, if soil aggregates are or were present, predominantly on or adjacent to (former) aggregate surfaces; ***or***
    b.  underlain by a layer with ≥ 95% (by exposed area) reductimorphic features that have the following Munsell colours, moist:
        i.  a hue of N, 10Y, GY, G, BG, B or PB; ***or***

        ii. a hue of 2.5Y or 5Y and a chroma of ≤ 2; ***and***
3.  is cemented with a cementation class of at least moderately cemented in ≥ 25% (by volume); ***and***
4.  has ≥ 2.5% Fe~dith~ + Mn~dith~, including both the cemented and the non-cemented parts; ***and***
5.  has a thickness of ≥ 2.5 cm.

#### Field identification {#sec-limnh-flid}

Limonic horizons show the typical characteristics of layers with [*gleyic properties*](#sec-gleyicp) and oximorphic features. In addition, they are at least partially cemented.

#### Relationships with some other diagnostics {#sec-limnh-reln}

Limonic horizons develop in layers with [*gleyic properties*](#sec-gleyicp) and oximorphic features. The process of groundwater ascent may be active or relict. Limonic horizons differ from [*tsitelic horizons*](#sec-tsith), which are noncemented and, if fine-textured, have a low bulk density. Limonic horizons, especially if with Mn oxides, may resemble [*spodic horizons*](#sec-spodh), but typically lack the Al translocation required for [*spodic horizons*](#sec-spodh).

### Mollic horizon {#sec-mollh}

#### General description {#sec-mollh-desc}

A mollic horizon (from Latin *mollis*, soft) is a relatively thick, dark-coloured surface horizon with a high base saturation and a moderate to high content of organic matter.

#### Diagnostic criteria {#sec-mollh-diag}

A mollic horizon is a surface horizon consisting of [*mineral material*](#sec-minm) and has:

1.  single or in combination, in ≥ 50% (by volume):
    a.  soil aggregate structure with an average aggregate size of ≤ 10 cm; ***or***
    b.  cloddy structure or other structural elements created by agricultural practices; ***and***
2.  ≥ 0.6% [*soil organic carbon*](#sec-soc); ***and***
3.  one of the following:
    a.  in ≥ 90% of the exposed area of the entire horizon or of the subhorizons below any plough layer, a Munsell colour value of ≤ 3 moist, and ≤ 5 dry, and a chroma of ≤ 3 moist; ***or***
    b.  all of the following:
        i.  a sum of calcium carbonate equivalent and gypsum of ≥ 15 and \< 40%; ***and***

        ii. in ≥ 90% of the exposed area of the entire horizon or of the subhorizons below any plough layer, a Munsell colour value of ≤ 3 and a chroma of ≤ 3, both moist; ***and***

        iii. ≥ 1% [*soil organic carbon*](#sec-soc); ***or***
    c.  all of the following:
        i.  a sum of calcium carbonate equivalent and gypsum of ≥ 40% and/or a texture class of loamy sand or coarser; ***and***

        ii. in ≥ 90% of the exposed area of the entire horizon or of the subhorizons below any plough layer, a Munsell colour value of ≤ 5 and a chroma of ≤ 3, both moist; ***and***

        iii. ≥ 2.5% [*soil organic carbon*](#sec-soc); ***and***
4.  if a layer is present that corresponds to the parent material of the mollic horizon and that has a Munsell colour value of ≤ 4, moist, ≥ 0.6% (absolute) more [*soil organic carbon*](#sec-soc) than this layer; ***and***
5.  a base saturation (by 1 *M* NH~4~OAc, pH 7) of ≥ 50% on a weighted average; ***and***
6.  a thickness of one of the following:
    a.  ≥ 10 cm if directly overlying [*continuous rock*](#sec-contr), [*technic hard material*](#sec-techhm) or a [*cryic*](#sec-cryich), [*petrocalcic*](#sec-petroh), [*petroduric*](#sec-petdh), [*petrogypsic*](#sec-petrgh)or [*petroplinthic horizon*](#sec-petplh); ***or***
    b.  ≥ 20 cm.

#### Field identification {#sec-mollh-flid}

A mollic horizon may easily be identified by its dark colour, caused by the accumulation of organic matter, in most cases a well-developed structure (usually a granular or subangular blocky structure), an indication of high base saturation (e.g. pH~water~ \> 6), and its thickness.

#### Relationships with some other diagnostics {#sec-mollh-reln}

The base saturation of ≥ 50% separates the mollic horizon from the [*umbric horizon*](#sec-umbrich), which is otherwise similar. The upper limit of the content of [*soil organic carbon*](#sec-soc) is 20%, which is the lower limit for [*organic material*](#sec-orgm).

A special type of mollic horizon is the [*chernic horizon*](#sec-chernh). It requires a higher content of [*soil organic carbon*](#sec-soc), a lower chroma, a better developed soil structure, a minimum content of fine earth and a greater minimum thickness.

Some [*hortic*](#sec-hortih), [*irragric*](#sec-iragh), [*pretic*](#sec-preth) or [*terric horizons*](#sec-terich) may also qualify as mollic horizons.

### Natric horizon {#sec-natrh}

#### General description {#sec-natrh-desc}

A natric horizon (from Arabic *natroon*, salt) is a dense subsurface horizon with a distinctly higher clay content than in the overlying horizon(s). It has a high content of exchangeable Na and in some cases, a relatively high content of exchangeable Mg.

#### Diagnostic criteria {#sec-natrh-diag}

A natric horizon consists of [*mineral material*](#sec-minm) and:

1.  has a texture class of loamy sand or finer and ≥ 8% clay; ***and***
2.  one or both of the following:
    a.  has an overlying coarser-textured layer with all of the following:
        i.  the coarser-textured layer is not separated from the natric horizon by a [*lithic discontinuity*](#sec-lithd); ***and***
        ii. if the coarser-textured layer directly overlies the natric horizon, its lowermost sublayer does not form part of a plough layer; ***and***
        iii. if the coarser-textured layer does not directly overlie the natric horizon, the transitional horizon between the coarser-textured layer and the natric horizon has a thickness of ≤ 15 cm; ***and***
        iv. if the coarser-textured layer has \< 15% clay, the natric horizon has ≥ 6% (absolute) more clay; ***and***
        v.  if the coarser-textured layer has ≥ 15 and \< 50% clay, the ratio of clay in the natric horizon to that of the coarser-textured layer is ≥ 1.4; ***and***
        vi. if the coarser-textured layer has ≥ 50% clay, the natric horizon has ≥  20% (absolute) more clay; ***or***
    b.  has evidence of illuvial clay in one or more of the following forms:
        i.  clay bridges connecting ≥ 15% of the sand grains; ***or***
        ii. clay coatings covering ≥ 15% of the surfaces of soil aggregates, coarse fragments and/or biopore walls; ***or***
        iii. in thin sections, oriented clay bodies (pure or interlayered with silt layers) that constitute ≥ 1% of the section and that have not been transported laterally after they had been formed; ***or***
        iv. a ratio of fine clay to total clay in the natric horizon greater by ≥ 1.2 times than the ratio in the overlying coarser-textured layer; ***and***
3.  has one or more of the following:
    a.  a columnar or prismatic structure in some part of the horizon; ***or***
    b.  both of the following:
        i.  an angular or subangular blocky structure; ***and***
        ii. penetrations of an overlying coarser-textured layer, in which there are uncoated sand and/or coarse silt grains, extending ≥ 2.5 cm into the natric horizon; ***and***
4.  has one of the following:
    a.  an exchangeable Na percentage (ESP) of ≥ 15 throughout the entire natric horizon or its upper 40 cm, whichever is thinner; ***or***
    b.  both of the following,
        i.  more exchangeable Mg plus Na than Ca plus exchange acidity (buffered at pH 8.2) throughout the entire natric horizon or its upper 40 cm, whichever is thinner; ***and***
        ii. an exchangeable Na percentage (ESP) of ≥ 15 in some subhorizon starting ≤ 50 cm below the upper limit of the natric horizon; ***and***
5.  has a thickness of one-tenth or more of the thickness of the overlying [*mineral material*](#sec-minm), if present, and one of the following:
    a.  ≥ 7.5 cm (if composed of lamellae: combined thickness within 50 cm of the upper limit of the uppermost lamella) if the natric horizon has a texture class of sandy loam or finer; ***or***
    b.  ≥ 15 cm (if composed of lamellae: combined thickness within 50 cm of the upper limit of the uppermost lamella).

#### Field identification {#sec-natrh-flid}

The colour of many natric horizons ranges from brown to black, especially in the upper part, but lighter colours or yellow to red colours may also be found. The structure is usually coarse columnar or coarse prismatic, in places blocky. Rounded tops of the aggregates are characteristic. In many cases, they are covered by a whitish powder coming from the overlying eluvial horizon.

Both colour and structural characteristics depend on the composition of the exchangeable cations and the soluble salt content in the underlying layers. Often, thick and dark-coloured clay coatings occur, especially in the upper part of the horizon. Many natric horizons have poor soil aggregate stability and very low permeability under wet conditions. When dry, the rupture-resistance class of the natric horizon is at least hard. Soil reaction is commonly strongly alkaline with pH~water~ ≥ 8.5.

#### Additional information {#sec-natrh-info}

Another measure to characterize the natric horizon is the sodium adsorption ratio (SAR), which is ≥ 13. The SAR is calculated from soil solution data (Na^+^, Ca^2+^, Mg^2+^ given in mmol~c~/litre): SAR = Na^+^/\[(Ca^2+^ + Mg^2+^)/2\]^0.5^.

In micromorphological studies, natric horizons have a specific fabric. The low structural stability is shown by a pore system with many vesicles and vughs. Pedofeatures consist of layered silt and clay cappings, coatings and infillings; clay intercalations and fragments of clay coatings in the groundmass, due to partial structure collapse.

#### Relationships with some other diagnostics {#sec-natrh-reln}

The surface horizon may be rich in organic matter, have a thickness from a few centimetres to \> 25 cm and may be a [*mollic*](#sec-mollh) or [*chernic horizon*](#sec-chernh). An [*albic horizon*](#sec-albich) may be present between the surface and the natric horizon.

Frequently, a salt-affected layer occurs below the natric horizon. The salt influence may extend into the natric horizon, which then becomes saline as well. Salts present may be chlorides, sulfates or carbonates/bicarbonates.

The high ESP of the humus-illuvial part of the natric horizon separates it from the [*sombric horizon*](#sec-sombrh).

### Nitic horizon {#sec-nitich}

#### General description {#sec-nitich-desc}

A nitic horizon (from Latin *nitidus*, shiny) is a clay-rich subsurface horizon. It has moderately to strongly developed blocky structure breaking to polyhedral or flat-edged elements with many shiny pressure faces.

#### Diagnostic criteria {#sec-nitich-diag}

A nitic horizon consists of [*mineral material*](#sec-minm) and:

1.  has ≥ 30% clay; ***and***
2.  has, single or in combination:
    a.  moderate to strong angular or subangular blocky structure, breaking into polyhedral or flat-edged second-level structure with pressure faces (shiny surfaces) at ≥ 25% of the surfaces of the soil aggregates of the second-level structure; ***or***
    b.  polyhedral structure with pressure faces (shiny surfaces) at ≥ 25% of the surfaces of the soil aggregates; ***and***
3.  has all of the following:
    a.  ≥ 4% Fe~dith~ ('free iron'); ***and***
    b.  ≥ 0.2% Fe~ox~ ('active iron'); ***and***
    c.  a ratio between Fe~ox~ and Fe~dith~ of ≥ 0.05; ***and***
4.  does not form part of a [*plinthic horizon*](#sec-plinth); ***and***
5.  has a thickness of ≥ 30 cm.

#### Field identification {#sec-nitich-flid}

A nitic horizon has ≥ 30% clay but may feel loamy. Little difference in clay content compared to the overlying and the underlying horizon and a gradual or diffuse distinctness of the horizon boundaries are typical. Similarly, there is no abrupt colour difference to the horizons directly above and below. The colours are of low value with a hue often 2.5YR, moist, but sometimes redder or yellower. The structure is moderate to strong blocky, breaking into polyhedral or flat-edged elements showing shiny pressure faces. In addition, clay coatings may be found. Nitic horizons do not show reducing conditions but may show relict oximorphic features, e.g., concretions and nodules of Fe and Mn oxides.

#### Additional information

In many nitic horizons, the CEC (by 1 *M* NH~4~OAc, pH 7) is \< 36 cmol~c~ kg^-1^ clay, or even \< 24 cmol~c~ kg^-1^ clay. The sum of exchangeable bases (by 1 *M* NH~4~OAc, pH 7) plus exchangeable Al (by 1 *M* KCl, unbuffered) is about half of the CEC. The moderate to low CEC reflects the dominance of 1:1 clay minerals (either kaolinite and/or \[meta-\]halloysite). Many nitic horizons have a ratio of water-dispersible clay to total clay of \< 0.1. Through the microscope, the birefringent fabric may be striated. Clay coatings, if present, normally form fine coatings around aggregates or may be incorporated into the matrix.

#### Relationships with some other diagnostics {#sec-nitich-reln}

The nitic horizon may be considered as a strongly expressed [*cambic horizon*](#sec-cambh) with specific properties such as a high amount of oxalate-extractable (active) iron. Nitic horizons may show clay coatings and may satisfy the requirements of an [*argic horizon*](#sec-argich), although the clay content in the nitic horizon is not much higher than in the overlying horizon. Its mineralogy (kaolinitic/\[meta\]halloysitic) sets it apart from most [*vertic horizons*](#sec-verth), which have a dominantly smectitic mineralogy and usually occur in climates with a more pronounced dry season. However, nitic horizons may grade laterally into [*vertic horizons*](#sec-verth) in lower landscape positions. The well-expressed soil structure, the high amount of oxalate-extractable iron, and in some cases, the intermediate CEC in nitic horizons set them apart from [*ferralic horizons*](#sec-feralh). Nitic horizons strongly differ from [*cohesic horizons*](#sec-cohesh), which may also be rich in clay. Nitic horizons in freely drained soils of high plateaus and mountains in humid tropical and subtropical regions may occur in association with [*sombric horizons*](#sec-sombrh).

### Panpaic horizon {#sec-panph}

#### General description {#sec-panph-desc}

A panpaic horizon (from Quechua *p'anpay*, to bury) is a buried mineral surface horizon with a significant amount of organic matter formed before having been buried. It is considered a diagnostic horizon, although the process of burying is a geological process and not a soil-forming process.

#### Diagnostic criteria {#sec-panph-diag}

A panpaic horizon is a buried surface horizon consisting of [*mineral material*](#sec-minm) and has:

1.  ≥ 0.2% [*soil organic carbon*](#sec-soc); ***and***
2.  a content of [*soil organic carbon*](#sec-soc) ≥ 25% (relative) and ≥ 0.2% (absolute) higher than in the overlying layer; ***and***
3.  a [*lithic discontinuity*](#sec-lithd) at its upper limit; ***and***
4.  a thickness of ≥ 5 cm.

#### Relationships with some other diagnostics {#sec-panph-reln}

Some panpaic horizons also meet the criteria of the [*chernic*](#sec-chernh), [*mollic*](#sec-mollh) or [*umbric horizon*](#sec-umbrich). They differ from the [*sombric horizon*](#sec-sombrh) that has no [*lithic discontinuity*](#sec-lithd) at its upper limit. A panpaic horizon may form part of layers of [*fluvic material*](#sec-fluvicm).

### Petrocalcic horizon {#sec-petroh}

#### General description {#sec-petroh-desc}

A petrocalcic horizon (from Greek *petros*, rock, and Latin *calx*, lime) is cemented by calcium carbonate and in some places, by magnesium carbonate as well. It is either massive or platy in nature and has a very high penetration resistance.

#### Diagnostic criteria {#sec-petroh-diag}

A petrocalcic horizon consists of [*mineral material*](#sec-minm) and:

1.  has very strong effervescence after adding a 1 M HCl solution; and
2.  is cemented, at least partially by secondary carbonates, with a cementation class of at least moderately cemented; ***and***
3.  is continuous to the extent that vertical fractures, if present, have an average horizontal spacing of ≥ 10 cm and occupy \< 20% (by volume, related to the whole soil), ***and***
4.  does not have coarse roots except, if present, along the vertical fractures; ***and***
5.  has a thickness of one of the following
    a.  ≥ 1 cm if it is laminar and rests directly on [*continuous rock*](#sec-contr); ***or***
    b.  ≥ 10 cm.

#### Field identification {#sec-petroh-flid}

Petrocalcic horizons occur as non-platy calcrete (either massive or nodular) or as platy calcrete, of which the following types are the most common:

*Lamellar calcrete*: superimposed, separate, petrified layers varying in thickness from a few millimetres to several centimetres. The colour is generally white or pink.

*Petrified lamellar calcrete*: one or several extremely petrified layers, grey or pink in colour. They are generally more cemented than the lamellar calcrete and very massive (no fine lamellar structures, but coarse lamellar structures may be present).

Non-capillary pores in petrocalcic horizons are filled, and the hydraulic conductivity is moderately slow to very slow.

#### Relationships with some other diagnostics {#sec-petroh-reln}

In arid regions, petrocalcic horizons may occur in association with ([*petro-*](#sec-petdh))[*duric horizons*](#sec-durich), into which they may grade laterally. The cementing agent differentiates petrocalcic and ([*petro-*](#sec-petdh))[*duric horizons*](#sec-durich). In petrocalcic horizons, calcium and some magnesium carbonate constitute the main cementing agent while some accessory silica may be present. In ([*petro-*](#sec-petdh))[*duric horizons*](#sec-durich), silica is the main cementing agent, with or without calcium carbonate. Petrocalcic horizons also occur in association with [*gypsic*](#sec-gypsih) or [*petrogypsic horizons*](#sec-petrgh). Horizons with a significant accumulation of secondary carbonates without continuous cementation qualify as [*calcic horizons*](#sec-calch).

### Petroduric horizon {#sec-petdh}

#### General description {#sec-petdh-desc}

A petroduric horizon (from Greek *petros*, rock, and Latin *durus*, hard), also known as duripan (United States) or dorbank (South Africa), is a subsurface horizon, usually reddish or reddish brown in colour, that is cemented mainly by illuvial secondary silica (SiO~2~, presumably opal and microcrystalline forms of silica). Calcium carbonate may be present as a supplementary cementing agent.

#### Diagnostic criteria {#sec-petdh-diag}

A petroduric horizon consists of [*mineral material*](#sec-minm) and:

1.  has ≥ 1% (by exposed area, related to the fine earth plus accumulations of secondary silica of any size and any cementation class) accumulation of visible secondary silica; ***and***
2.  both of the following:
    a.  when air-dry, \< 50% (by volume) slake in 1 *M* HCl, even after prolonged soaking, ***and***
    b.  when air-dry, ≥ 50% (by volume) slake in hot concentrated KOH or hot concentrated NaOH, at least if alternating with 1 M HCl; and
3.  is cemented, at least partially by secondary silica, with a cementation class of at least weakly cemented, both before and after treatment with acid; ***and***
4.  is continuous to the extent that vertical fractures, if present, have an average horizontal spacing of ≥ 10 cm and occupy \< 20% (by volume, related to the whole soil); ***and***
5.  does not have coarse roots except, if present, along the vertical fractures; ***and***
6.  has a thickness of ≥ 1 cm.

#### Field identification {#sec-petdh-flid}

The identification of secondary silica is described in Annex 1 ([Chapter 8.4.27](annex-01-field-quide.qmd#sec-a1-silica)). Effervescence after applying 1 *M* HCl may take place but is mostly not as vigorous as in [*petrocalcic horizons*](#sec-petroh), which appear similar. In very dry environments, the petroduric horizons commonly are platy. In less dry environments, vertical fractures are more common. It has usually a high penetration resistance.

#### Additional information {#sec-petdh-info}

If both silica and carbonates are present as cementing agents, the petroduric horizon will only slake if hot concentrated KOH or NaOH (to dissolve the silica) are alternated with HCl (to dissolve the carbonates). If carbonates are absent, KOH or NaOH alone will be able to slake the petroduric horizon.

#### Relationships with some other diagnostics {#sec-petdh-reln}

In arid climates, petroduric horizons may occur in association with [*petrocalcic horizons*](#sec-petroh), into which they may grade laterally, and/or occur in conjunction with [*calcic*](#sec-calch) or [*gypsic horizons*](#sec-gypsih). Fragments of a petroduric horizon or durinodes constitute a [*duric horizon*](#sec-durich). Petroduric horizons may develop from volcanic ashes and may be overlain by layers with [*andic*](#sec-andicp) or [*vitric properties*](#sec-vitricp).

### Petrogypsic horizon {#sec-petrgh}

#### General description {#sec-petrgh-desc}

A petrogypsic horizon (from Greek petros, rock, and *gypsos*, gypsum) is a cemented horizon containing accumulations of secondary gypsum (CaSO~4~·2H~2~O).

#### Diagnostic criteria {#sec-petrgh-diag}

A petrogypsic horizon consists of [*mineral material*](#sec-minm) and:

1.  1\. has ≥ 40% gypsum (related to the fine earth plus accumulations of secondary gypsum of any size and any cementation class); ***and***
2.  has ≥ 1% (by exposed area) visible secondary gypsum; ***and***
3.  is cemented, at least partially by secondary gypsum, with a cementation class of at least extremely weakly cemented; ***and***
4.  is continuous to the extent that vertical fractures, if present, have an average horizontal spacing of ≥ 10 cm and occupy \< 20% (by volume, related to the whole soil);
5.  does not have coarse roots except, if present, along the vertical fractures; ***and***
6.  has a thickness of ≥ 1 cm.

#### Field identification {#sec-petrgh-flid}

Petrogypsic horizons are cemented, whitish and composed predominantly of gypsum. Old petrogypsic horizons may be capped by a thin, laminar layer of newly precipitated gypsum. How to recognize secondary gypsum is described in Annex 1 ([Chapter 8.4.26](annex-01-field-guide.qmd#sec-a1-gypsum)).

#### Additional information {#sec-petrgh-info}

The recommended procedure to determine gypsum in the laboratory (Annex 2, [Chapter 9.10](annex-02-analytical-procedures.qmd#sec-a2-gypsum)) also extracts anhydrite, which is considered to be mainly primary.

In thin sections, the petrogypsic horizon shows a a groundmass composed of interlocked gypsum crystals with a hypidiotopic or xenotopic fabric, mixed with varying amounts of detrital material.

#### Relationships with some other diagnostics {#sec-petrgh-reln}

As the petrogypsic horizon develops from a [*gypsic horizon*](#sec-gypsih), the two are closely related. Petrogypsic horizons frequently occur in association with ([*petro*-](#sec-petroh))[*calcic horizons*](#sec-calch). Accumulations of calcium carbonate and gypsum usually occupy different positions in the soil profile because the solubility of calcium carbonate is less than that of gypsum. Normally, they can be distinguished clearly from each other by their morphology (see [*calcic horizon*](#sec-calch)).

### Petroplinthic horizon {#sec-petplh}

#### General description {#sec-petplh-desc}

A petroplinthic horizon (from Greek *petros*, rock, and *plinthos*, brick) is a continuous or fractured layer of cemented material, in which Fe (and in some cases also Mn) (hydr-)oxides are an important cement and in which organic matter is either absent or present only in traces. It has formed by continuous cementation of a [*plinthic*](#sec-plinth) or [*pisoplinthic horizon*](#sec-pisoph). Advanced crystallization of the oxides causes a very high penetration resistance. Traditional names for horizons similar to the petroplinthic horizon are 'laterite' or 'ironstone'.

#### Diagnostic criteria {#sec-petplh-diag}

A petroplinthic horizon consists of [*mineral material*](#sec-minm) and:

1.  consists of oximorphic features inside (former) soil aggregates that are at least partially interconnected and have a reddish, yellowish and/or blackish colour; ***and***
2.  has one or both of the following:
    a.  ≥ 2.5% Fe~dith~ in the fine earth; ***or***
    b.  ≥ 10% Fe~dith~ in the oximorphic features; ***and***
3.  has a ratio between Fe~ox~ and Fe~dith~ of \< 0.1 in the fine earth or in the oximorphic features; ***and***
4.  is cemented with a cementation class of at least strongly cemented; ***and***
5.  is continuous to the extent that vertical fractures, if present, have an average horizontal spacing of ≥ 10 cm and occupy \< 20% (by volume, related to the whole soil); ***and***
6.  does not have coarse roots except, if present, along the vertical fractures; ***and***
7.  has a thickness of ≥ 10 cm.

#### Field identification {#sec-petplh-flid}

Petroplinthic horizons are extremely hard (high penetration resistance) and typically rusty brown to yellowish brown. They are either massive or show an interconnected nodular pattern that encloses material with a lower penetration resistance. They may be fractured. Roots are generally found only in vertical fractures. Penetration resistance is ≥ 4.5 MPa in ≥ 50% of the volume of the fine earth. From this value upwards, the rupture resistance will not sink upon wetting [see @asiamah2000].

#### Additional information {#sec-petplh-info}

The ratio between Fe~ox~ and Fe~dith~ has been estimated from data given by Varghese and Byju [-@varghese1993laterite].

#### Relationships with some other diagnostics {#sec-petplh-reln}

Petroplinthic horizons are closely associated with [*plinthic*](#sec-plinth) and [*pisoplinthic horizons*](#sec-pisoph) from which they develop. In some places, [*plinthic horizons*](#sec-plinth) can be traced by following petroplinthic layers that have formed, for example, in road cuts.

The low ratio between Fe~ox~ and Fe~dith~ separates the petroplinthic horizon from cemented [*spodic horizons*](#sec-spodh) (Ortsteinic or Placic qualifiers), which in addition contain mostly a fair amount of organic matter. [*Limonic horizons*](#sec-limnh) also have higher ratios.

### Pisoplinthic horizon {#sec-pisoph}

#### General description {#sec-pisoph-desc}

A pisoplinthic horizon (from Latin *pisum*, pea, and Greek *plinthos*, brick) contains a large amount of concretions and/or nodules that are at least moderately cemented by Fe (and in some cases also by Mn) (*hydr*-)*oxides*. It may also contain fragments of a broken-up [*petroplinthic horizon*](#sec-petplh).

#### Diagnostic criteria {#sec-pisoph-diag}

A pisoplinthic horizon consists of [*mineral material*](#sec-minm) and:

1.  has ≥ 40% of its volume (related to the whole soil) occupied by, single or in combination,
    a.  yellowish, reddish and/or blackish concretions and/or nodules; ***or***
    b.  fragments of a broken-up [*petroplinthic horizon*](#sec-petplh), with a diameter of \> 2 mm and a cementation class of at least moderately cemented; ***and***
2.  does not form part of a [*petroplinthic horizon*](#sec-petplh); ***and***
3.  has a thickness of ≥ 15 cm.

#### Relationships with some other diagnostics {#sec-pisoph-reln}

A pisoplinthic horizon results, when discrete concretions and/or nodules of a [*plinthic horizon*](#sec-plinth) reach a certain percentage and a cementation class of at least moderately cemented. The cementation class and the amount of concretions and/or nodules separate it from the [*ferric horizon*](#sec-ferich). If the concretions and/or nodules are sufficiently interconnected, the pisoplinthic horizon becomes a [*petroplinthic horizon*](#sec-petplh). A pisoplinthic horizon may also be formed by the fracturing of a [*petroplinthic horizon*](#sec-petplh).

### Plaggic horizon {#sec-plaggh}

#### General description {#sec-plaggh-desc}

A plaggic horizon (from Low German *plaggen*, sod) is a black or brown mineral surface horizon that results from human activity. Mostly in nutrient-poor soils in the north-western part of Central Europe from Medieval times until the introduction of mineral fertilizers at the beginning of the 20^th^ century, sod and other topsoil materials were commonly used for bedding livestock. The sods consist of grassy, herbaceous or dwarf-shrub vegetation, its root mats and organic and mineral soil sticking to them. The mixture of sods and excrements was later spread on fields. The material brought in eventually produced an appreciably thickened horizon (in places \> 100 cm thick) that is rich in [*soil organic carbon*](#sec-soc). Base saturation is typically low.

#### Diagnostic criteria {#sec-plaggh-diag}

A plaggic horizon is a surface horizon consisting of [*mineral material*](#sec-minm) and:

1.  has a texture class of sand, loamy sand, sandy loam or loam, or a combination of them; ***and***
2.  one or more of the following:
    a.  contains artefacts, but \< 20% (by volume, related to the whole soil); ***or***
    b.  has ≥ 100 mg kg^-1^ P in the Mehlich-3 extract in the upper 20 cm; ***or***
    c.  has in its lower part spade or hook marks, remnants of a plough layer or other evidence of former agricultural activity; ***and***
3.  has a Munsell colour value of ≤ 4 moist, and ≤ 5 dry, and a chroma of ≤ 4 moist; ***and***
4.  has ≥ 0.6% [*soil organic carbon*](#sec-soc); ***and***
5.  has a base saturation (by 1 *M* NH~4~OAc, pH 7) of \< 50%, unless the soil has been limed or received mineral fertilizers; ***and***
6.  shows evidence that the land surface has been raised; ***and***
7.  has a thickness of ≥ 20 cm.

#### Field identification {#sec-plaggh-flid}

The plaggic horizon has brownish or blackish colours, related to the origin of source materials. It may contain [*artefacts*](#sec-artefm), but less than 20%. Its reaction is mostly slightly to strongly acid. The pH may have risen due to recent liming but seldom reaching a high base saturation. It may show evidence of old agricultural operations in its lower part, such as spade or hook marks as well as old plough layers. Plaggic horizons commonly overlie buried soils although the original surface layers may be mixed with the plaggen. In some cases, ditches have been made in the buried soil as a cultivation mode for soil improvement. The lower boundary is typically clear to abrupt.

#### Additional information {#sec-plaggh-info}

The texture class is in most cases sand or loamy sand. Sandy loam and loam are rare. The [*soil organic carbon*](#sec-soc) may include carbon added with the plaggen. 100 mg kg^-1^ P in the Mehlich-3 extract (same value as for pretic horizons) roughly correspond to 143 mg kg^-1^ P or 327 mg kg^-1^ P~2~O~5~ in 1% citric acid [@kabala2018]. Originally, the plaggic horizon has a low base saturation. If limed or fertilized, this criterion is waived.

#### Relationships with some other diagnostics {#sec-plaggh-reln}

After liming, some plaggic horizons may fulfil the criteria of the [*terric horizon*](#sec-terich), but [*terric horizons*](#sec-terich) usually have a higher animal activity. Some plaggic horizons may contain black carbon and also fulfil the criteria of the [*pretic horizon*](#sec-preth). Some plaggic horizons may also qualify as [*umbric*](#sec-umbrich) or even as [*mollic horizon*](#sec-mollh).

### Plinthic horizon {#sec-plinth}

#### General description {#sec-plinth-desc}

A plinthic horizon (from Greek *plinthos*, brick) is a subsurface horizon that is rich in Fe (in some cases also Mn) (hydr-)oxides and poor in humus. The clay fraction is dominated by kaolinite, together with other products of strong weathering, such as gibbsite. It may contain quartz. The plinthic horizon has formed by redox processes, usually caused by stagnant water, which may be active or relict, and shows redoximorphic features. The plinthic horizon is not continuously cemented. On exposure to repeated drying and wetting with free access to oxygen, the oxides become more crystallized leading to a continuously cemented horizon.

#### Diagnostic criteria {#sec-plinth-diag}

A plinthic horizon consists of [*mineral material*](#sec-minm) and:

1.  has in ≥ 15% of its exposed area (related to the fine earth plus accumulations of oxides of any size and any cementation class) oximorphic features inside (former) soil aggregates that are black or have a redder hue and a higher chroma than the surrounding material; ***and***
2.  one or more of the following:
    a.  has ≥ 2.5% Fe~dith~ in the fine earth; ***or***
    b.  has ≥ 10% Fe~dith~ in the oximorphic features; ***or***
    c.  changes irreversibly to a continuously cemented horizon with a cementation class of at least strongly cemented after repeated drying and wetting; ***and***
3.  has a ratio between Fe~ox~ and Fe~dith~ of \< 0.1 in the fine earth or in the oximorphic features; ***and***
4.  does not form part of a [*petroplinthic*](#sec-petplh) or [*pisoplinthic horizon*](#sec-pisoph); ***and***
5.  has a thickness of ≥ 15 cm.

#### Field identification {#sec-plinth-flic}

A plinthic horizon shows prominent redoximorphic features. In a perennially moist soil, many of the oximorphic features are non-cemented or have a low cementation class and can be cut with a spade.

#### Additional information {#sec-plinth-info}

Micromorphological studies may reveal the extent of impregnation of the soil mass by Fe (hydr-)oxides. In many plinthic horizons, prolonged [*reducing conditions*](#sec-reducc) are not present anymore.

#### Relationships with some other diagnostics {#sec-plinth-reln}

If the concretions and nodules of the plinthic horizon become at least moderately cemented and reach ≥ 40% of the exposed area, the plinthic horizon becomes a [*pisoplinthic horizon*](#sec-pisoph). If the plinthic horizon becomes continuously cemented, the plinthic horizon becomes a [*petroplinthic horizon*](#sec-petplh).

If the oximorphic features do not reach 15% of the exposed area, it may be a [*ferric horizon*](#sec-ferich).

### Pretic horizon {#sec-preth}

#### General description {#sec-preth-desc}

A pretic horizon (from Portuguese *preto*, black) is a mineral surface horizon that results from human activities with the addition of black carbon, especially charcoal. It is characterized by its dark colour, usually the presence of artefacts (ceramic fragments, lithic instruments, bone or shell tools etc.) and high contents of organic carbon, phosphorus, calcium, magnesium and micronutrients (mainly zinc and manganese), usually contrasting with natural soils in the surrounding area. It contains remnants of black carbon, which may be recognized visually or by chemical analyses.

Pretic horizons are for example widespread in the Amazon Basin, where they are the result of pre-Columbian activities and have persisted over many centuries despite the prevailing humid tropical conditions generally causing high organic matter mineralization rates. These soils with a pretic horizon are known as 'Terra Preta de Indio' or 'Amazonian Dark Earths'. They generally have high organic carbon stocks. Many of them are dominated by low-activity clays.

#### Diagnostic criteria {#sec-preth-diag}

A pretic horizon is a surface horizon consisting of [*mineral material*](#sec-minm) and has:

1.  a Munsell colour value of ≤ 4 and a chroma of ≤ 3, both moist; ***and***
2.  ≥ 0.6% [*soil organic carbon*](#sec-soc); ***and***
3.  exchangeable Ca plus Mg (by 1 *M* NH~4~OAc, pH 7) of ≥ 1 cmol~c~ kg^-1^ fine earth; ***and***
4.  ≥ 100 mg kg~-1~ P in the Mehlich-3 extract; ***and***
5.  one or both of the following:
    a.  ≥ 1% (by exposed area, related to the fine earth plus black carbon of any size) visible black carbon; ***or***
    b.  both of the following
        i.  ≥ 0.3% carbon belonging to molecules of black carbon, determined by chemical analyses; ***and***
        ii. a ratio between carbon belonging to molecules of black carbon and total organic carbon of ≥ 0.15, determined by chemical analyses; ***and***
6.  one or more layers with a combined thickness of ≥ 20 cm.

#### Additional information {#sec-preth-info}

Black carbon is an [*artefact*](#sec-artefm) only if it is intentionally manufactured by humans. The minimum [*soil organic carbon*](#sec-soc) content (criterion 2) must be fulfilled without the [*artefacts*](#sec-artefm).

P in the Mehlich-3 extract roughly is the double of the values obtained in the Mehlich-1 extract [@kabala2018], which was the requirement in the 3^rd^ edition of WRB. Additionally, compared to the 3^rd^ edition, the value was increased from 30 to 50 (Mehlich-1) or from 60 to 100 (Mehlich-3) mg kg^-1^.

#### Relationships with some other diagnostics {#sec-preth-reln}

Some pretic horizons may also fulfil the criteria of the [*plaggic horizon*](#sec-plaggh) and, especially in their upper parts, the criteria of the [*hortic horizon*](#sec-hortih). Some pretic horizons may qualify as [*mollic*](#sec-mollh) or [*umbric horizons*](#sec-umbrich). Old charcoal hearths usually fail the P criterion of the pretic horizon. They do not fit into the concept of the pretic horizon, are characterized by the Carbonic and the Pyric qualifier, and many of them are Technosols.

### Protovertic horizon {#sec-protvh}

#### General description {#sec-protvh-desc}

A protovertic horizon (from Greek *proton*, first, and Latin *vertere*, to turn) has swelling and shrinking clay minerals.

#### Diagnostic criteria {#sec-protvh-diag}

A protovertic horizon consists of [*mineral material*](#sec-minm) and has:

1.  ≥ 30% clay; ***and***
2.  one or more of the following:
    a.  wedge-shaped soil aggregates in ≥ 10% (by volume); ***or***
    b.  slickensides on ≥ 5% of the surfaces of soil aggregates; ***or***
    c.  shrink-swell cracks; ***or***
    d.  a coefficient of linear extensibility (COLE) of ≥ 0.06; ***and***
3.  a thickness of ≥ 15 cm.

#### Field identification {#sec-protvh-flid}

Wedge-shaped soil aggregates and slickensides (see Annex 1, Chapter [8.4.10](annex-01-field-guide.qmd#sec-a1-struct) and [8.4.14](annex-01-field-guide.qmd#sec-a1-stress)) may not be immediately evident if the soil is moist. A decision about their presence can sometimes only be made after the soil has dried out. Wedge-shaped aggregates may be a second-level structure of larger angular blocky or prismatic elements, which should be carefully examined to see if wedge-shaped aggregates are present.

#### Relationships with some other diagnostics {#sec-protvh-reln}

If the swelling and shrinking is more prominent (or the layer is thicker) the protovertic horizon grades into a [*vertic horizon*](#sec-verth).

### Salic horizon {#sec-salich}

#### General description {#sec-salich-desc}

A salic horizon (from Latin *sal*, salt) is a surface horizon or a subsurface horizon at a shallow depth that contains high amounts of readily soluble salts, i.e. salts more soluble than gypsum (CaSO~4~·2H~2~O; log Ks = -4.85 at 25 °C).

#### Diagnostic criteria {#sec-salich-diag}

A salic horizon has:

1.  at some time of the year
    a.  if the pH~water~ of the saturation extract is ≥ 8.5, an electrical conductivity of the saturation extract (EC~e~) of ≥ 8 dS m^-1^ measured at 25 °C and a product of thickness (in centimetres) and EC~e~ (in dS m^-1^) of ≥ 240; ***or***
    b.  an electrical conductivity of the saturation extract (EC~e~) of ≥ 15 dS m^-1^ measured at 25 °C and a product of thickness (in centimetres) and EC~e~ (in dS m^-1^) of ≥ 450; ***and***
2.  a thickness of ≥ 15 cm (combined thickness if there are superimposed subhorizons meeting criteria 1.a and 1.b).

#### Field identification {#sec-salich-flid}

Halophytes (e.g. some species of *Salicornia*, *Tamarix* and *Suaeda*) and salt-tolerant crops are first indicators. Salt-affected layers are often puffy. Salts precipitate only after evaporation of most soil moisture; if the soil is moist, salt may not be visible.

Salts may precipitate at the soil surface (external Solonchaks) or at depth (internal Solonchaks). A salt crust, if present, may be part of the salic horizon.

#### Additional information {#sec-salich-info}

In alkaline carbonate soils, an EC~e~ at 25 °C of ≥ 8 dS m^-1^ and a pH~water~ of ≥ 8.5 are very common. Salic horizons may consist of [*organic*](#sec-orgm) or [*mineral material*](#sec-minm).

### Sombric horizon {#sec-sombrh}

#### General description {#sec-sombrh-desc}

A sombric horizon (from French *sombre*, dark) is a dark-coloured subsurface horizon containing more organic matter than the directly overlying horizon. It has no [*lithic discontinuity*](#sec-lithd) at its upper limit and is neither associated with Al nor dispersed by Na.

#### Diagnostic criteria {#sec-sombrh-diag}

A sombric horizon consists of [*mineral material*](#sec-minm) and:

1.  has ≥ 0.2% [*soil organic carbon*](#sec-soc)*;* ***and***
2.  has a content of [*soil organic carbon*](#sec-soc) ≥ 25% (relative) and ≥ 0.2% (absolute) higher than in the overlying layer; ***and***
3.  does not have a [*lithic discontinuity*](#sec-lithd) at its upper limit and does not form part of a natric or spodic horizon; ***and***
4.  has a thickness of ≥ 10 cm.

#### Field identification {#sec-sombrh-flid}

Sombric horizons are found in dark-coloured subsoils, in many cases associated with well-drained soils of high plateaus and mountains in humid tropical and subtropical regions. They resemble buried horizons but, in contrast to many of these, sombric horizons more or less follow the shape of the soil surface. They have a lower Munsell colour value than the directly overlying horizon and commonly a low base saturation.

#### Additional information {#sec-sombrh-info}

There are two important theories about the genesis of sombric horizons [@almeida2015].

First theory: The higher content of organic matter is illuvial, but neither associated with Al nor with Na. In this case, coatings of organic matter at soil aggregate surfaces and pore walls as well as illuvial organic matter in thin sections are found.

Second theory: The higher content of organic matter is residual. A moister climate and a higher plant biomass (e.g. forest) formed thick A horizons. Afterwards, climate became drier, the upper part of the old A horizon underwent an intense mineralization, while the residues of the current vegetation, poorer in biomass (e.g. savanna), form only a thin A horizon. At greater depth, mineralization is slower, and the lower part of the old A horizon is preserved, especially if climate is cool and base saturation low.

#### Relationships with some other diagnostics {#sec-sombrh-reln}

Sombric horizons may coincide with [*argic*](#sec-argich), [*cambic*](#sec-cambh), [*ferralic*](#sec-feralh) or [*nitic horizons*](#sec-nitich). Contrary to [*panpaic horizons*](#sec-panph), sombric horizons have no [*lithic discontinuity*](#sec-lithd) at their upper limit. [*Spodic horizons*](#sec-spodh) are differentiated from sombric horizons by their much higher CEC of the clay fraction. The humus-illuvial part of [*natric horizons*](#sec-natrh) has a higher clay content, a high Na saturation and a specific structure, which separates them from sombric horizons.

### Spodic horizon {#sec-spodh}

#### General description {#sec-spodh-desc}

A spodic horizon (from Greek *spodos*, wood ash) is a subsurface horizon that contains illuvial substances. In most spodic horizons, the appearance of the upper subhorizons is characterized by dark illuvial organic matter and that of the lower subhorizons by intensely coloured illuvial Fe oxides. Some spodic horizons, however, show either little illuviation of Fe or little illuviation of organic matter. In all spodic horizons, illuviated Al can be proven analytically. The illuvial materials are characterized by a high pH-dependent charge, a relatively large surface area and an elevated water retention. An overlying eluvial horizon may intrude with tongues into the spodic horizon.

#### Diagnostic criteria {#sec-spodh-diag}

A spodic horizon consists of [*mineral material*](#sec-minm) and:

1.  has a pH (1:1 in water) of \< 5.9, unless the soil has been limed or fertilized; ***and***
2.  has a subhorizon with an Al~ox~ value that is ≥ 1.5 times that of the lowest Al~ox~ value of all the mineral layers above the spodic horizon; ***and***
3.  has in its uppermost 1 cm one or both of the following:
    a.  ≥ 0.5% [*soil organic carbon*](#sec-soc); ***or***
    b.  a Munsell colour chroma of ≥ 6, moist, in ≥ 90% of its exposed area; ***and***
4.  has one or more subhorizons with the following Munsell colours, moist, in ≥ 90% of their exposed area:
    a.  a hue of 5YR or redder; ***or***
    b.  a hue of 7.5YR and a value of ≤ 5; ***or***
    c.  a hue of 10YR and a value and a chroma of ≤ 2; ***or***
    d.  a hue of 10YR and a chroma of ≥ 6; ***or***
    e.  a colour of 10YR 3/1; ***or***
    f.  a hue of N and a value of ≤ 2; ***and***
5.  one or more of the following:
    a.  is overlain by claric material that is not separated from the spodic horizon by a [*lithic discontinuity*](#sec-lithd) and that overlies the spodic horizon either directly or above a transitional horizon that has a thickness of one-tenth or less of the overlying claric material; ***or***
    b.  ≥ 10% of the sand grains of the horizon show cracked coatings; ***or***
    c.  has a subhorizon that is cemented with a cementation class of at least weakly cemented in ≥ 50% of its horizontal extension; ***or***
    d.  has a subhorizon with an Al~ox~ + ½Fe~ox~ value of ≥ 0.5% that is ≥ 2 times that of the lowest Al~ox~ + ½Fe~ox~ value of all the mineral layers above the spodic horizon; ***and***
6.  does not form part of a [*natric*](#sec-natrh), [*limonic*](#sec-limnh) or [*tsitelic horizon*](#sec-tsith); ***and***
7.  has a thickness of ≥ 2.5 cm.

#### Field identification {#sec-spodh-flid}

Many spodic horizons underly [*claric material*](#sec-claricm) and have brownish-black to reddish-brown colours, which often fade downwards. The shape of many spodic horizons is wavy, irregular, or broken. Spodic horizons may be (partially) cemented. Thin and relatively continuous cementations are indicated by the Placic qualifier and thicker and/or less continuous cementations by the Ortsteinic qualifier. Spodic horizons may extend further down in ribbon-like accumulations, which are not included in the calculation of the minimum thickness.

#### Relationships with some other diagnostics {#sec-spodh-reln}

There may be a [*hortic*](#sec-hortih), [*plaggic*](#sec-plaggh), [*terric*](#sec-terich) or [*umbric horizon*](#sec-umbrich) above the spodic horizon, with or without [*claric material*](#sec-claricm) in between.

Spodic horizons in volcanic materials may exhibit [*andic properties*](#sec-andicp) as well. Spodic horizons in other materials may exhibit some characteristics of the andic properties, but normally have a higher bulk density. For classification purposes, the presence of a spodic horizon, unless buried deeper than 50 cm, is given preference over the occurrence of [*andic properties*](#sec-andicp).

Some layers with [*andic properties*](#sec-andicp) resemble spodic horizons, if they are covered by relatively young, light-coloured volcanic ejecta that satisfy the requirements of [*claric material*](#sec-claricm). There is a [*lithic discontinuity*](#sec-lithd) in between, which excludes them from being spodic horizons. This can be further proven by the following analyses: The uppermost 2.5 cm of the spodic horizon have a C~py~/OC and a C~f~/C~py~ of ≥ 0.5. C~py~, C~f~ and OC are pyrophosphate-extractable C, fulvic acid C and organic C, respectively [@ito1991].

Similar to many spodic horizons, [*sombric horizons*](#sec-sombrh) also contain more organic matter than an overlying layer. They can be differentiated from each other by the clay mineralogy. Kaolinite usually dominates in [*sombric horizons*](#sec-sombrh), whereas the clay fraction of spodic horizons commonly contains significant amounts of vermiculite and Al-interlayered chlorite.

[*Plinthic horizons*](#sec-plinth), which contain large amounts of accumulated Fe, have less Fe~ox~ than spodic horizons.

### Terric horizon {#sec-terich}

#### General description {#sec-terich-desc}

A terric horizon (from Latin *terra*, earth) is a mineral surface horizon that develops through addition of [*mineral material*](#sec-minm) or a combination of [*mineral material*](#sec-minm) and organic residues, for example, fertile mineral soil, compost, calcareous beach sands, loess or mud. It may contain stones, randomly sorted and distributed. In most cases, it is built up gradually over a long period of time. Occasionally, terric horizons are created by single additions of material. Normally the added material is mixed with the original topsoil.

#### Diagnostic criteria {#sec-terich-diag}

A terric horizon is a surface horizon consisting of [*mineral material*](#sec-minm) and:

1.  shows evidence of addition of material substantially different from the environment, where it has been placed; ***and***
2.  contains, if any, \< 10% (by volume, related to the whole soil) artefacts; ***and***
3.  has ≥ 0.6% [*soil organic carbon*](#sec-soc); ***and***
4.  has a base saturation (by 1 *M* NH~4~OAc, pH 7) of ≥ 50%; ***and***
5.  shows evidence that the land surface has been raised; ***and***
6.  has a thickness of ≥ 20 cm.

#### Field identification {#sec-terich-flic}

Terric horizons show characteristics related to the source material, e.g. in colour. Buried soils may be observed at the base of the horizon although mixing can obscure the contact. Soils with a terric horizon show a raised surface that may be inferred either from field observation or from historical records. The terric horizon is not homogeneous, but subhorizons are thoroughly mixed. It commonly contains a small amount of [*artefacts*](#sec-artefm) such as pottery fragments, cultural debris and refuse, that are typically very small (\< 1 cm in diameter) and very abraded.

#### Relationships with some other diagnostics {#sec-terich-reln}

Some terric horizons may also fulfil the criteria of anthropogenic horizons with stronger alterations, like the [*hortic*](#sec-hortih), [*plaggic*](#sec-plaggh) or the [*pretic horizon*](#sec-preth). Most [*hortic horizons*](#sec-hortih) show more and most [*plaggic horizons*](#sec-plaggh) less soil animal activity than the terric horizon. The [*pretic horizons*](#sec-preth) contain black carbon. Some terric horizons may qualify as [*mollic*](#sec-mollh) horizon.

### Thionic horizon {#sec-thionh}

#### General description {#sec-thionh-desc}

A thionic horizon (from Greek *theion*, sulfur) is an extremely acid subsurface horizon in which sulfuric acid is formed through oxidation of sulfides.

#### Diagnostic criteria {#sec-thionh-diag}

A thionic horizon has:

1.  a pH (1:1 by mass in water, or in a minimum of water to permit measurement) of \< 4; ***and***
2.  one or more of the following:
    a.  accumulations of iron or aluminium sulfate or hydroxysulfate minerals, predominantly on or adjacent to surfaces of soil aggregates; ***or***
    b.  direct superposition on sulfidic material; ***or***
    c.  ≥ 0.05% water-soluble sulfate; ***and***
3.  a thickness of ≥ 15 cm.

#### Field identification {#sec-thionh-flid}

Thionic horizons generally exhibit pale yellow jarosite or yellowish-brown schwertmannite accumulations on or adjacent to surfaces of soil aggregates. Soil reaction is extremely acid; pH~water~ of 3.5 is quite common. While mostly associated with recent sulfidic coastal sediments, thionic horizons may also develop inland in [*sulfidic materials*](#sec-hypersm) that may be present either in natural deposits or in [*artefacts*](#sec-artefm) such as mine spoil.

#### Additional information {#sec-thionh-info}

Iron or aluminium sulfate or hydroxysulfate minerals include jarosite, natrojarosite, schwertmannite, sideronatrite and tamarugite. Thionic horizons may consist of organic or [*mineral material*](#sec-minm).

#### Relationships with some other diagnostics {#sec-thionh-reln}

A thionic horizon often underlies a horizon with strongly expressed [*stagnic properties*](#sec-stagnp).

### Tsitelic horizon {#sec-tsith}

#### General description {#sec-tsith-desc}

A tsitelic horizon (from Georgian *tsiteli*, red) shows a lateral accumulation of Fe. It is usually found on lower slopes or in depressions. Stagnosols and Planosols occur upslope in inclined positions and have lost reduced Fe by lateral subsurface water flow. Further down, the reduced Fe gets in contact with atmospheric oxygen, is oxidized and accumulates in subsurface horizons starting usually at shallow depths. They are rich in oxalate-extractable Fe, which gives the tsitelic horizons a homogeneous reddish colour.

#### Diagnostic criteria {#sec-tsith-diag}

A tsitelic horizon consists of [*mineral material*](#sec-minm) and

1.  has ≥ 1% Fe~ox~; ***and***
2.  has a ratio between Fe~ox~ and Fe~dith~ of ≥ 0.5; ***and***
3.  has Al~ox~ \< Fe~ox~; ***and***
4.  has a Munsell colour chroma of ≥ 4, moist; ***and***
5.  does not show reductimorphic features; ***and***
6.  does not form part of a [*limonic horizon*](#sec-limnh); ***and***
7.  has a thickness of ≥ 5 cm.

#### Field identification {#sec-tsith-flid}

The accumulation of ferrihydrites causes a homogeneous reddish colour and, if the horizon is fine-textured, a low bulk density and some thixotropy.

#### Relationships with some other diagnostics {#sec-tsith-reln}

Tsitelic horizons may resemble [*spodic horizons*](#sec-spodh) of Rustic Podzols but lack the translocation of Al that is required for [*spodic horizons*](#sec-spodh). If showing low bulk density and thixotropy, they may give the impression of [*andic properties*](#sec-andip), but they have neither a significant amount of allophanes and imogolites nor of Al-humus complexes. Contrary to most horizons with [*andic properties*](#sec-andip), tsitelic horizons show more Fe than Al in the oxalate extract. Layers with oximorphic features caused by [*gleyic properties*](#sec-gleyicp) may also look similar to tsitelic horizons. While in layers with [*gleyic properties*](#sec-gleyicp), the oxides are predominantly found at soil aggregate surfaces, the oxides in tsitelic horizons fill the entire soil matrix homogenously. Tsitelic horizons distinguish well from [*limonic horizons*](#sec-limnh), which are (at least partially) cemented.

### Umbric horizon {#sec-umbrich}

#### General description

An umbric horizon (from Latin *umbra*, shade) is a relatively thick, dark-coloured surface horizon with a low base saturation and a moderate to high content of organic matter.

#### Diagnostic criteria {#sec-umbrich-diag}

An umbric horizon is a surface horizon consisting of [*mineral material*](#sec-minm) and has:

1.  single or in combination, in ≥ 50% (by volume):
    a.  soil aggregate structure with an average aggregate size of ≤ 10 cm; ***or***
    b.  cloddy structure or other structural elements created by agricultural practices; ***and***
2.  ≥ 0.6% [*soil organic carbon*](#sec-soc); ***and***
3.  one or both of the following:
    a.  in ≥ 90% of the exposed area of the entire horizon or of the subhorizons below any plough layer, a Munsell colour value of ≤ 3 moist, and ≤ 5 dry, and a chroma of ≤ 3 moist; ***or***
    b.  all of the following:
        i.  a texture class of loamy sand or coarser; ***and***
        ii. in ≥ 90% of the exposed area of the entire horizon or of the subhorizons below any plough layer, a Munsell colour value of ≤ 5 and a chroma of ≤ 3, both moist; ***and***
        iii. ≥ 2.5% [*soil organic carbon*](#sec-soc);
4.  if a layer is present that corresponds to the parent material of the umbric horizon and that has a Munsell colour value of ≤ 4, moist, ≥ 0.6% (absolute) more [*soil organic carbon*](#sec-soc) than this layer; ***and***
5.  a base saturation (by 1 *M* NH~4~OAc, pH 7) of \< 50% on a weighted average; ***and***
6.  a thickness of one of the following:
    a.  ≥ 10 cm if directly overlying [*continuous rock*](#sec-contr), [*technic hard material*](#sec-techhm) or a [*cryic*](#sec-cryich), [*petroduric*](#sec-petdh)or [*petroplinthic horizon*](#sec-petplh); ***or***
    b.  ≥ 20 cm.

#### Field identification {#sec-umbrich-flid}

The main field characteristics of an umbric horizon are its dark colour and its structure. In general, umbric horizons tend to have a lesser grade of soil structure than [*mollic horizons*](#sec-mollh).

Most umbric horizons have an acid reaction (pH~water~ \< 5.5), which usually indicates a base saturation of \< 50%. An additional indication for strong acidity is a shallow, horizontal rooting pattern in the absence of a physical barrier.

#### Relationships with some other diagnostics {#sec-umbrich-reln}

The base saturation requirement sets the umbric horizon apart from the [*mollic horizon*](#sec-mollh), which is otherwise similar. The upper limit of the content of [*soil organic carbon*](#sec-soc) is 20%, which is the lower limit for [*organic material*](#sec-orgm).

Some [*irragric*](#sec-iragh) and [*plaggic horizons*](#sec-plaggh) may also qualify as umbric horizons.

### Vertic horizon {#sec-verth}

#### General description {#sec-verth-desc}

A vertic horizon (from Latin *vertere*, to turn) is a clay-rich subsurface horizon that, as a result of shrinking and swelling, has slickensides and wedge-shaped soil aggregates.

#### Diagnostic criteria {#sec-verth-diag}

A vertic horizon consists of [*mineral material*](#sec-minm) and has:

1.  ≥ 30% clay; ***and***
2.  one or both of the following:
    a.  a\. in ≥ 20% (by volume), wedge-shaped soil aggregates with a longitudinal axis tilted between ≥ 10° and ≤ 60° from the horizontal; ***or***
    b.  slickensides on ≥ 10% of the surfaces of soil aggregates; ***and***
3.  [*shrink-swell cracks*](#sec-shrswc); ***and***
4.  a thickness of ≥ 25 cm.

#### Field identification {#sec-verth-flid}

Vertic horizons are clay-rich and, when dry, often have a rupture-resistance class of at least hard. Polished, shiny surfaces with striations (slickensides), often at sharp angles, are distinctive.

Wedge-shaped soil aggregates and slickensides (see Annex 1, Chapter [8.4.10](annex-01-field-guide.qmd#sec-a1-struct) and [8.4.14](annex-01-field-guide.qmd#sec-a1-stress)) may not be immediately evident if the soil is moist. A decision about their presence can sometimes only be made after the soil has dried out. Wedge-shaped aggregates may be a second-level structure of larger angular blocky or prismatic elements, which should be carefully examined to see if wedge-shaped aggregates are present.

#### Additional information {#sec-verth-info}

The coefficient of linear extensibility (COLE, see Annex 2, [Chapter 9.6](annex-02-analytical-procedures.qmd#sec-a2-cole)) is usually ≥ 0.06.

#### Relationships with some other diagnostics {#sec-verth-reln}

Several other diagnostic horizons may also have high clay contents, e.g., the [*argic*](#sec-argich), [*natric*](#sec-natrh) and [*nitic horizon*](#sec-nitich). Most of them lack the characteristics typical for the vertic horizon. However, they may be laterally linked in the landscape with vertic horizons, the latter usually taking up the lowest position. Less pronounced swelling and shrinking of clay minerals leads to a [*protovertic horizon*](#sec-protvh).

## Diagnostic properties {#sec-diagp}

**Diagnostic properties** are characterized by a combination of attributes that reflect results of soil-forming processes or indicate specific conditions of soil formation. Their features can be observed or measured in the field or the laboratory and require a minimum or maximum expression to qualify as diagnostic. A minimum thickness is not part of the criteria.

### Abrupt textural difference {#sec-abtxdf}

#### General description

An abrupt textural difference (from Latin *abruptus*, broken away) is a very sharp increase in clay content within a limited depth range.

#### Diagnostic criteria {#sec-abtxdf-diag}

An abrupt textural difference refers to two superimposed layers consisting of [*mineral material*](#sec-minm) with all of the following:

1.  the underlying layer has all of the following:
    a.  ≥  15% clay; ***and***
    b.  a thickness of ≥ 7.5 cm; ***and***
2.  the underlying layer starts ≥ 10 cm from the mineral soil surface; ***and***
3.  the underlying layer has, compared to the overlying layer:
    a.  at least twice as much clay if the overlying layer has \< 20% clay; ***or***
    b.  ≥ 20% (absolute) more clay if the overlying layer has ≥ 20% clay; ***and***
4.  if the limit between the two layers is not even, the depth of the abrupt textural difference is, where the underlying layer reaches ≥ 50% of the total volume; ***and***
5.  a transitional layer, if present, has a thickness of ≤ 2 cm.

#### Additional information {#sec-abtxdf-info}

An example for an uneven limit between the two layers are [*retic properties*](#sec-reticp) in the underlying layer. Depending on the development of the [*retic properties*](#sec-reticp), the abrupt textural difference may be at the upper limit of the [*retic properties*](#sec-reticp) or further down (criterion 3).

### Albeluvic glossae {#sec-albgl}

#### General description {#sec-albgl-desc}

The term albeluvic glossae (from Latin *albus*, white, and *eluere*, to wash out, and Greek *glossa*, tongue) refers to penetrations of clay- and Fe-depleted material into an [*argic horizon*](#sec-argich). Albeluvic glossae occur along soil aggregate surfaces and form vertically continuous tongues. In horizontal sections, they exhibit a polygonal pattern.

#### Diagnostic criteria {#sec-albgl-diag}

Albeluvic glossae:

1.  refer to an [*argic horizon*](#sec-argich) and, if the [*argic horizon*](#sec-argich) is \< 30 cm thick, also to the underlying layers until 30 cm below the upper limit of the [*argic horizon*](#sec-argich); ***and***
2.  show [*retic properties*](#sec-reticp) in the [*argic horizon*](#sec-argich); ***and***
3.  have continuous tongues consisting of coarser-textured material, as defined in the [*retic properties*](#sec-reticp), that start at the upper limit of the [*argic horizon*](#sec-argich), with all of the following:
    a)  have a vertical extension of ≥ 30 cm; ***and***
    b)  have a horizontal extension of ≥ 1 cm; ***and***
    c)  occupy ≥ 10 and \< 90% of the exposed area.

#### Relationships with some other diagnostics {#sec-albgl-reln}

Albeluvic glossae are a special case of *retic properties*. In [*retic properties*](#sec-reticp), the coarser-textured parts may be thinner and are not necessarily vertically continuous. [*Retic properties*](#sec-reticp) may also be present in [*natric horizons*](#sec-natrh) whereas albeluvic glossae are defined only in [*argic horizons*](#sec-argich). The [*argic horizon*](#sec-argich) into which the albeluvic glossae penetrate may also fulfil the diagnostic criteria of a [*fragic horizon*](#sec-fragh). In undisturbed soils, the [*argic horizon*](#sec-argich) with the albeluvic glossae is typically overlain by an [*albic*](#sec-albich) or [*cambic horizon*](#sec-cambh). However, the overlying horizons may be lost due to erosion or ploughing.

### Andic properties {#sec-andicp}

#### General description {#sec-andicp-desc}

Andic properties (from Japanese *an*, dark, and *do*, soil) result from moderate weathering of mainly pyroclastic deposits. The presence of short-range-order minerals and/or organo-metallic complexes is characteristic for andic properties. These minerals and complexes are commonly part of the weathering sequence in pyroclastic deposits ([*tephric material*](#sec-tephrm) → [*vitric properties*](#sec-andicp) → andic properties). However, andic properties with organo-metallic complexes may also form in non-pyroclastic silicate-rich materials in cooltemperate and humid climates.

#### Diagnostic criteria {#sec-andicp-diag}

Andic properties require:

1.  a bulk density of ≤ 0.9 kg dm^-3^; ***and***
2.  an Al~ox~ + ½Fe~ox~ value of ≥ 2%; ***and***
3.  a phosphate retention of ≥ 85%.

#### Field identification {#sec-andicp-flid}

Andic properties may be identified using the sodium fluoride field test of Fieldes and Perrott [-@fieldes1966]. A pH in NaF of ≥ 9.5 indicates allophane and/or organo-aluminium complexes in carbonate-free soils. The test is indicative for most layers with andic properties, except for those very rich in organic matter. However, the same reaction occurs in [*spodic horizons*](#sec-spodh) and in certain acid clays that are rich in Al-interlayered clay minerals.

Andic layers may exhibit thixotropy, i.e. the soil material changes, under pressure or by rubbing, from a plastic solid into a liquefied stage and back into the solid condition.

#### Additional information {#sec-andicp-info}

Andic properties may be found at the soil surface or in the subsurface, commonly occurring as layers. Many surface layers with andic properties contain a high amount of organic matter (≥ 5%), are commonly very dark coloured (Munsell colour value and chroma of ≤ 3, moist), have a fluffy macrostructure, and in some places show thixotropy. They have a low bulk density and commonly have a silt loam or finer texture. Andic surface layers rich in organic matter may be very thick, having a thickness of ≥ 50 cm in some soils. Andic subsurface layers are generally somewhat lighter coloured.

In perhumid climates, humus-rich andic layers may contain more than twice the water content of samples that have been dried at 105 °C and rewetted (hydric characteristic).

For bulk density, the volume is determined after an undried soil sample has been desorbed at 33 kPa (no prior drying), and afterwards the weight is determined at 105 °C.

Two major types of andic properties are recognized: one in which allophane, imogolite and similar minerals are predominant (Silandic qualifier); and one in which Al complexed by organic acids prevails (Aluandic qualifier). The silandic property typically gives a strongly acid to neutral soil reaction and is a bit lighter coloured, while the aluandic property gives an extremely acid to acid reaction and a blackish colour.

Uncultivated, organic matter-rich surface layers with silandic properties typically have a pH~water~ of ≥ 4.5, while uncultivated surface layers with aluandic properties and rich in organic matter typically have a pH~water~ of \< 4.5. Generally, pH~water~ in silandic subsoil layers is ≥ 5.

#### Relationships with some other diagnostics {#sec-andicp-reln}

[*Vitric properties*](#sec-vitricp) are distinguished from andic properties by a lesser degree of weathering. This is evidenced by the presence of volcanic glasses and usually by a lower amount of short-range-order pedogenic minerals and/or organo-metallic complexes, as characterized by a lower amount of Al~ox~ and Fe~ox~, a higher bulk density, or a lower phosphate retention. The diagnostic criteria of the [*vitric*](#sec-vitricp) and [*andic properties*](#sec-andip) are adapted after Shoji et al. [-@shoji1996], Takahashi et al. [-@takahashi2004] and findings of the COST 622 Action [-@costassociation2004].

[Spodic horizons](#sec-spodh), which also contain complexes of oxides and organic substances, can exhibit andic properties as well. Andic properties may also be present in [*chernic*](#sec-chernh), [*mollic*](#sec-mollh) or [*umbric horizons*](#sec-umbrich).

### Anthric properties {#sec-andip}

#### General description {#sec-andip-desc}

Anthric properties (from Greek *anthropos*, human being) refer to human-made [*mollic*](#sec-mollh) or [*umbric horizons*](#sec-umbrich). Some of the *mollic horizons* with anthric properties are natural [*umbric horizons*](#sec-umbrich) transformed into *mollic horizons* by liming and fertilization. Thin, light-coloured or humus-poor mineral topsoil horizons may be transformed into [*umbric*](#sec-umbrich) or even [*mollic horizons*](#sec-mollh) by long-term cultivation (ploughing, liming, fertilization etc.). Another group of artificial [*mollic*](#sec-mollh) or [*umbric horizons*](#sec-umbrich) is created by ploughing organic surface layers into the mineral soil. In all these cases, the soil has very little animal activity, which is especially uncommon for soils with a [*mollic horizon*](#sec-mollh).

#### Diagnostic criteria {#sec-andip-diag}

Anthric properties:

1.  occur in soils with a [*mollic*](#sec-mollh) or [*umbric horizon*](#sec-umbrich); ***and***
2.  show evidence of human disturbance by one or more of the following:
    a.  an abrupt lower boundary at ploughing depth and ≥ 10% of the sand grains not coated by organic matter; ***or***
    b.  an abrupt lower boundary at ploughing depth and evidence of mixing of humus-richer and humus-poorer soil materials by ploughing; ***or***
    c.  lumps of applied lime; ***or***
    d.  ≥ 430 mg kg^-1^ P in the Mehlich-3 extract in the upper 20 cm; ***and***
3.  show \< 5% (by exposed area) of animal pores, coprolites or other traces of soil animal activity in one or both of the following depths:
    a.  in the lowermost 5 cm of the [*mollic*](#sec-mollh) or [*umbric horizon*](#sec-umbrich); ***or***
    b.  in a depth range of 5 cm below the plough layer, if present.

#### Field identification {#sec-andip-flid}

Signs of mixing or cultivation, evidence of liming (e.g. remnants of applied lime chunks), the dark colour and the almost complete absence of traces of soil animal activity are the main criteria for recognition. Incorporated humus-richer material may be established with the naked eye, using a 10x hand lens or using thin sections, depending on the degree of fragmentation/dispersion of the humus-richer material. The incorporated humus-richer material is typically weakly bound to the humus-poorer material, which is manifested by uncoated sand grains in a darker matrix throughout the mixed layer.

#### Additional information {#sec-andip-info}

430 mg kg^-1^ P in the Mehlich-3 extract roughly correspond to 654 mg kg^-1^ P or 1500 mg kg^-1^ P~2~O~5~ in 1% citric acid [@kabala2018], which was the requirement in former editions of WRB. The original idea of the anthric properties is derived from Krogh & Greve [-@krogh1999].

#### Relationships with some other diagnostics {#sec-andip-reln}

Anthric properties are an additional characteristic of some [*mollic*](#sec-mollh) or [*umbric horizons*](#sec-umbrich). [*Chernic horizons*](#sec-chernh) normally show a higher animal activity and do not have anthric properties.

### Continuous rock {#sec-contr}

#### Diagnostic criteria {#sec-contr-diag}

Continuous rock (from Latin *continuare*, to continue) is consolidated material, exclusive of cemented pedogenic horizons such as [*limonic*](#sec-limnh), [*petrocalcic*](#sec-petroh), [*petroduric*](#sec-petdh), [*petrogypsic*](#sec-petrgh), [*petroplinthic*](#sec-petplh) and [*spodic horizons*](#sec-spodh). Continuous rock is sufficiently consolidated to remain intact when an air-dried specimen, 25--30 mm on one side, is submerged in water for 1 hour. The material is considered continuous only if cracks occupy \< 10% (by volume) of the continuous rock, with no significant displacement of the rock having taken place.

### Gleyic properties {#sec-gleyicp}

#### General description {#sec-gleyicp-desc}

Gleyic properties (from Russian folk name *gley*, wet bluish clay) develop in layers that are saturated with groundwater (or were saturated in the past, if now drained) for a period that allows [*reducing conditions*](#sec-reducc) to occur (this may range from a few days in the tropics to a few weeks in other areas) and in the capillary fringe above them. There may be gleyic properties without the presence of groundwater in a clay-rich layer over a layer rich in sand or coarse fragments. In some soils with gleyic properties, the [*reducing conditions*](#sec-reducc) are caused by upward moving gases such as methane or carbon dioxide. If there are no more [*reducing conditions*](#sec-reducc), the gleyic properties are relict.

#### Diagnostic criteria {#sec-gleyicp-diag}

Gleyic properties refer to [*mineral material*](#sec-minm), show redoximorphic features and comprise one of the following:

1.  a layer with ≥ 95% (by exposed area) reductimorphic features that have the following Munsell colours, moist:
    a.  a hue of N, 10Y, GY, G, BG, B or PB; ***or***
    b.  a hue of 2.5Y or 5Y and a chroma of ≤ 2; ***or***
2.  a layer with \> 5% (by exposed area) oximorphic features that:
    a.  are predominantly on biopore walls and, if soil aggregates are present, predominantly on or adjacent to aggregate surfaces; ***and***
    b.  have a Munsell colour hue ≥ 2.5 units redder and a chroma ≥ 1 unit higher, moist, than the surrounding material or than the matrix of the directly underlying layer; ***or***
3.  a combination of two layers: a layer fulfilling diagnostic criterion 2 and a directly underlying layer fulfilling diagnostic criterion 1.

#### Field identification {#sec-gleyicp-flid}

Redoximorphic features are described in Annex 1 ([Chapter 8.4.20](annex-02-field-guide.qmd#sec-a2-redox)).

#### Additional information {#sec-gleyicp-info}

Gleyic properties result from a redox gradient between groundwater and the capillary fringe causing an uneven distribution of iron or manganese (hydr-)oxides. In the lower part of the soil and/or inside the soil aggregates, the oxides are either transformed into soluble Fe/Mn(II) compounds or they are translocated; both processes lead to the absence of colours that have a Munsell hue redder than 2.5Y. Translocated Fe and Mn compounds can be concentrated in the oxidized form (Fe\[III\], Mn\[IV\]) on soil aggregate surfaces or on biopore walls (rusty root channels), and towards the surface even in the matrix. Mn concentrations can be recognized by strong effervescence using a 10% H~2~O~2~ solution.

Reductimorphic features reflect permanently wet conditions. In loamy and clayey material, blue-green colours predominate owing to Fe(II, III) hydroxy salts (green rust). If the material is rich in sulfur (S), blackish colours prevail owing to colloidal iron sulfides such as greigite or mackinawite (easily recognized by smell, after applying 1 *M* HCl). In calcareous material, whitish colours are dominant owing to calcite and/or siderite. Sands are usually light grey to white in colour and also often impoverished in Fe and Mn. Bluish-green and black colours are unstable and often oxidize to a reddish brown colour within a few hours of exposure to air. The upper part of a reductimorphic layer may show up to 5% rusty colours, mainly around channels of burrowing animals or plant roots.

Oximorphic features reflect oxidizing conditions, as in the capillary fringe and in the surface horizons of soils with fluctuating groundwater levels. Specific colours indicate ferrihydrite (reddish brown), goethite (bright yellowish brown), lepidocrocite (orange), schwertmannite (dark orange) and jarosite (pale yellow). In loamy and clayey soils, the iron oxides/hydroxides are concentrated on soil aggregate surfaces and the walls of larger pores (e.g. old root channels).

In most cases, a layer fulfilling diagnostic criterion 2 overlies a layer fulfilling criterion 1. Some soils, including underwater soils (freshwater or seawater) and tidal soils have only a layer that fulfils diagnostic criterion 1 and no layer fulfilling criterion 2.

#### Relationships with some other diagnostics {#sec-gleyicp-reln}

Gleyic properties differ from [*stagnic properties*](#sec-stagnp). Gleyic properties are caused by an upward moving agent (mostly groundwater) that causes [*reducing conditions*](#sec-reducc) and that leads to an underlying strongly reduced layer and an overlying layer with oximorphic features on or adjacent to soil aggregate surfaces. (In some soils only one of these layers is present.) [*Stagnic properties*](#sec-stagnp) are caused by stagnation of an intruding agent (mostly rainwater) that causes [*reducing conditions*](#sec-reducc) and that leads to an overlying Fe-poor layer and an underlying layer with oximorphic features inside the soil aggregates. (In some soils, only one of these layers is present.)

### Lithic discontinuity {#sec-lithd}

#### General description {#sec-lithd-desc}

Lithic discontinuities (from Greek *lithos*, stone, and Latin *continuare*, to continue) represent significant differences in parent material within a soil. A lithic discontinuity can also denote different times of deposition. The different strata may have the same or a different mineralogy.

#### Diagnostic criteria {#sec-lithd-diag}

When comparing two directly superimposed layers consisting of [*mineral material*](#sec-minm), a lithic discontinuity requires one or more of the following:

1.  an abrupt difference in particle-size distribution that is not solely associated with a change in clay content resulting from soil formation; ***or***
2.  both of the following:
    a.  one or more of the following:
        i.  ≥ 10% coarse sand and ≥ 10% medium sand, ***and*** a difference of ≥ 25% in the ratio coarse sand to medium sand, ***and*** a difference of ≥ 5% (absolute) in the content of coarse sand and/or medium sand; ***or***
        ii. ≥ 10% coarse sand and ≥ 10% fine sand, ***and*** a difference of ≥ 25% in the ratio coarse sand to fine sand, ***and*** a difference of ≥ 5% (absolute) in the content of coarse sand and/or fine sand; ***or***
        iii. ≥ 10% medium sand and ≥ 10% fine sand, ***and*** a difference of ≥ 25% in the ratio medium sand to fine sand, ***and*** a difference of ≥ 5% (absolute) in the content of medium sand and/or fine sand; ***or***
        iv. ≥ 10% sand and ≥ 10% silt, ***and*** a difference of ≥ 25% in the ratio sand to silt, ***and*** a difference of ≥ 5% (absolute) in the content of sand and/or silt; ***and***
    b.  the differences do not result from original variation within the parent material in the form of patches of different particle-size fractions within a layer; ***or***
3.  the layers have coarse fragments with different lithology; ***or***
4.  a layer containing coarse fragments without weathering rinds overlying a layer containing coarse fragments with weathering rinds; ***or***
5.  a layer with angular coarse fragments overlying or underlying a layer with rounded coarse fragments; ***or***
6.  an overlying layer that has ≥ 10% (absolute, by volume, related to the whole soil) more coarse fragments than the underlying layer, unless the difference is created by animal activity; ***or***
7.  a lower amount of coarse fragments in the overlying layer that cannot be explained by advanced weathering in the overlying layer; ***or***
8.  abrupt differences in colour not resulting from soil formation; ***or***
9.  marked differences in size and shape of resistant minerals (as shown by micromorphological or mineralogical methods); ***or***
10. differences in the TiO~2~/ZrO~2~ ratios of the sand fraction by a factor of ≥ 2; ***or***
11. differences in CEC (by 1 *M* NH~4~OAc, pH 7) per kg clay by a factor of ≥ 2.

#### Additional information {#sec-lithd-info}

In some cases, a lithic discontinuity may be suggested by one of the following: a horizontal line of coarse fragments (stone line) overlying and underlying layers with lesser amounts of coarse fragments, or a decreasing percentage of coarse fragments with increasing depth. On the other hand, the sorting action of small fauna such as termites can produce similar effects in what would initially have been lithicly uniform parent material.

Diagnostic criterion 2 is illustrated by the following example:

Layer 1: 20% coarse sand, 10% medium sand → ratio coarse sand to medium sand: 2.\
Layer 2: 15% coarse sand, 10% medium sand → ratio coarse sand to medium sand: 1.5. Difference in ratios: 25%\
Difference in contents of coarse sand (absolute): 5%\
Difference in contents of medium sand (absolute): 0\
Result: between the two layers, there is a lithic discontinuity.

Generally, the mathematical formula for calculating differences in ratios is:\
ABS(ratio~i~-ratio~i+1~)/MAX(ratio~i~; ratio~i+1~)\*100

### Protocalcic properties {#sec-protcp}

#### General description

Protocalcic properties (from Greek *proton*, first, and Latin *calx*, lime) refer to carbonates that are derived from the soil solution and precipitated in the soil. They do not belong to the soil parent material or to other sources such as dust. They occur across the soil structure or fabric. These carbonates are called secondary carbonates. For protocalcic properties, they must be permanent and be present in significant quantities.

#### Diagnostic criteria {#sec-protcp-diag}

Protocalcic properties refer to accumulations of secondary carbonates, visible when moist, that

1.  occupy ≥ 5% of the exposed area (related to the fine earth plus accumulations of secondary carbonates of any size and any cementation class) with masses, nodules, concretions or filaments; ***or***
2.  cover ≥ 10% of the surfaces of soil aggregates or biopore walls; ***or***
3.  cover ≥ 10% of the underside surfaces of coarse fragments or of fragments of a cemented horizon.

#### Field identification {#sec-protcp-flid}

The identification of secondary carbonates is described in Annex 1 ([Chapter 8.4.25](annex-01-field-guide.qmd#sec-a1-carbs)).

#### Additional information {#sec-protcp-info}

Accumulations of secondary carbonates qualify as protocalcic properties only if they are permanent and do not come and go with changing moisture conditions. This should be checked by spraying some water on them.

#### Relationships with some other diagnostics {#sec-protcp-reln}

Accumulations of secondary carbonates with higher contents of calcium carbonate equivalent may qualify for a [*calcic horizon*](#sec-calch), or if continuously cemented with a cementation class of at least moderately cemented, for a [*petrocalcic horizon*](#sec-petroh). [*Calcaric material*](#sec-calcam) refers to the presence of carbonates in the entire fine earth, which usually includes primary carbonates.

### Protogypsic properties {#sec-protgp}

#### General description {#sec-protgp-desc}

Protogypsic properties (from Greek *proton*, first, and *gypsos*, gypsum) refer to gypsum that is derived from the soil solution and precipitated in the soil. It does not belong to the soil parent material or to other sources such as dust. This gypsum is called secondary gypsum.

#### Diagnostic criteria {#sec-protgp-diag}

Protogypsic properties refer to visible accumulations of secondary gypsum that occupy ≥ 1% of the exposed area (related to the fine earth plus accumulations of secondary gypsum of any size and any cementation class).

#### Field identification {#sec-protgp-flid}

The identification of secondary gypsum is described in Annex 1 ([Chapter 8.4.26](annex-01-field-guide.qmd#sec-a1-gypsum)).

#### Relationships with some other diagnostics {#sec-protgp-reln}

Accumulations of secondary gypsum with higher gypsum contents may qualify for a [*gypsic horizon*](#sec-gypsih), or if continuously cemented, for a [*petrogypsic horizon*](#sec-petrgh). [*Gypsiric material*](#sec-gyspicm) includes primary gypsum.

### Reducing conditions {#sec-reducc}

#### Diagnostic criteria {#sec-reducc-diag}

Reducing conditions (from Latin *reducere*, to draw back) show one or more of the following:

1.  a negative logarithm of the hydrogen partial pressure (rH, calculated as Eh·29^-1^ + 2·pH) of \< 20; ***or***
2.  the presence of free Fe^2+^, as shown on a freshly broken and smoothed surface of a field-wet soil by the appearance of a strong red colour after wetting it with 0.2% α,α-dipyridyl dissolved in 1 *N* ammonium acetate (NH~4~OAc), pH 7; ***or***
3.  the presence of iron sulfide; ***or***
4.  the presence of methane.

**Caution**: α,α-dipyridyl solution is toxic if swallowed and harmful if absorbed through skin or inhaled. It has to be used with care. In layers with a neutral or alkaline soil reaction it may not give the strong red colour.

### Retic properties {#sec-reticp}

#### General description {#sec-reticp-desc}

Retic properties (from Latin *rete*, net) describe the interfingering of coarser-textured [*claric material*](#sec-claricm) into a finer-textured [*argic*](#sec-argich) or [*natric horizon*](#sec-natrh). The interfingering coarser-textured [*claric material*](#sec-claricm) is characterized by a partial removal of clay minerals and iron oxides. There may be also coarser-textured [*claric material*](#sec-claricm) falling from the overlying horizon into cracks in the [*argic*](#sec-argich) or [*natric horizon*](#sec-natrh). The coarser-textured [*claric material*](#sec-claricm) is found as vertical, horizontal and inclined interfingerings between soil aggregates.

#### Diagnostic criteria {#sec-reticp-diag}

Retic properties refer to a combination of finer-textured parts and coarser-textured parts, both consisting of [*mineral material*](#sec-minm), within the same layer, with all of the following:

1.  the finer-textured parts belong to an [*argic*](#sec-argich) or [*natric horizon*](#sec-natrh); ***and***
2.  the coarser-textured parts consist of [*claric material*](#sec-claricm); ***and***
3.  the finer-textured parts have, compared with the coarser-textured parts, the following Munsell colour, moist:
    a.  a hue ≥ 2.5 units redder: ***or***
    b.  a value ≥ 1 unit lower; ***or***
    c.  a chroma ≥ 1 unit higher; ***and***
4.  the clay content of the finer-textured parts is higher compared with the coarser-textured parts, as specified for the [*argic*](#sec-argich) or [*natric horizon*](#sec-natrh), criterion 2.a; ***and***
5.  the coarser-textured parts are ≥ 0.5 cm wide; ***and***
6.  the coarser-textured parts start at the upper limit of the [*argic*](#sec-argich) or [*natric horizon*](#sec-natrh); ***and***
7.  the coarser-textured parts occupy areas ≥ 10 and \< 90% in both vertical and horizontal sections, within
    a.  the upper 30 cm of the [*argic*](#sec-argich) or [*natric horizon*](#sec-natrh); ***or***
    b.  the entire [*argic*](#sec-argich) or [*natric horizon*](#sec-natrh),\
        whichever is thinner; ***and***
8.  do not occur within a plough layer.

#### Relationships with some other diagnostics {#sec-reticp-reln}

Retic properties include the special case of [*albeluvic glossae*](#sec-albgl). The [*argic*](#sec-argich) or [*natric horizons*](#sec-natrh) that exhibit retic properties may also satisfy the requirements of a [*fragic horizon*](#sec-fragh). A layer with retic properties may also show [*stagnic properties*](#sec-stagnp) with or without [*reducing conditions*](#sec-reducc). In undisturbed soils, the [*argic*](#sec-argich) or [*natric horizon*](#sec-natrh) with the retic properties is typically overlain by an [*albic*](#sec-albich) or [*cambic horizon*](#sec-cambh). However, the overlying horizons may be lost due to erosion or ploughing.

### Shrink-swell cracks {#sec-shrswc}

#### General description {#sec-shrswc-desc}

Shrink-swell cracks open and close due to shrinking and swelling of clay minerals with changing water content of the soil. They may be evident only when the soil is dry. They control the infiltration and percolation of water, even if they are filled with material from the surface.

#### Diagnostic criteria {#sec-shrswc-diag}

Shrink-swell cracks occur in [*mineral material*](#sec-minm) and:

1.  open and close with changing water content of the soil; ***and***
2.  are ≥ 0.5 cm wide, when the soil is dry, with or without infillings of material from the surface.

#### Relationships with some other diagnostics {#sec-shrswc-reln}

Shrink-swell cracks are referred to in the diagnostic criteria of the [*protovertic horizon*](#sec-protvh), the [*vertic horizon*](#sec-verth) and in the [Key to the Reference Soil Groups](chapter-04.qmd#sec-key) (where reference is made to their depth requirements).

### Sideralic properties {#sec-siderp}

#### General description {#sec-siderp-desc}

Sideralic properties (from Greek *sideros*, iron, and Latin *alumen*, alum) refer to [*mineral material*](#sec-minm) that has a relatively low CEC.

#### Diagnostic criteria {#sec-siderp-diag}

Sideralic properties occur in [*mineral material*](#sec-minm) and require:

1.  one or both of the following:
    a.  ≥ 8% clay and a CEC (by 1 *M* NH~4~OAc, pH 7) of \< 24 cmol~c~ kg^-1^ clay; ***or***
    b.  a CEC (by 1 *M* NH~4~OAc, pH 7) of \< 2 cmol~c~ kg^-1^ soil; ***and***
2.  evidence of soil formation as defined in criterion 3 of the [*cambic horizon*](#sec-cambh).

#### Relationships with some other diagnostics {#sec-siderp-reln}

Sideralic properties are also present in [*ferralic horizons*](#sec-feralh).

### Stagnic properties {#sec-stagnp}

#### General description {#sec-stagnp-desc}

Stagnic properties (from Latin *stagnare*, to flood) form in layers that are, at least temporarily, saturated with stagnant water (or were saturated in the past, if now drained) for a period long enough that allows *reducing conditions* to occur (this may range from a few days in the tropics to a few weeks in other areas). In some soils with stagnic properties, the *reducing conditions* are caused by the intrusion of other liquids such as gasoline. If there are no more *reducing conditions*, the stagnic properties are relict.

#### Diagnostic criteria {#sec-stagnp-diag}

Stagnic properties refer to [*mineral material*](#sec-minm), show redoximorphic features and comprise one or more of the following:

1.  a layer that comprises reductimorphic features and soil material with the matrix colour and that shows both of the following:
    a.  the reductimorphic features are predominantly around biopores and, if soil aggregates are present, predominantly at the outer parts of the aggregates; ***and***
    b.  the reductimorphic features have, compared against the matrix colour, the following Munsell colours, moist: a value ≥ 1 unit higher and a chroma ≥ 1 unit lower;
2.  a layer that comprises oximorphic features and soil material with the matrix colour and that shows both of the following:
    a.  the oximorphic features are, if soil aggregates are present, predominantly inside the aggregates; ***and***
    b.  the oximorphic features are black, surrounded by lighter-coloured material, or have, compared against the matrix colour, the following Munsell colours, moist: a hue ≥ 2.5 units redder and a chroma ≥ 1 unit higher; ***or***
3.  a layer that comprises reductimorphic features and oximorphic features (with or without soil material with a matrix colour) and that shows all of the following:
    a.  the reductimorphic features are predominantly around biopores and, if soil aggregates are present, predominantly at the outer parts of the aggregates; ***and***
    b.  the oximorphic features are, if soil aggregates are present, predominantly inside the aggregates; ***and***
    c.  the oximorphic features are black, surrounded by lighter-coloured material, or have, compared against the reductimorphic features, one or more of the following Munsell colours, all moist:
        i.  a hue ≥ 5 units redder; ***or***
        ii. a chroma ≥ 4 units higher; ***or***
        iii. a hue ≥ 2.5 units redder and a chroma ≥ 2 units higher; ***or***
        iv. a hue ≥ 2.5 units redder, a value ≥ 1 unit lower and a chroma ≥ 1 unit higher; ***or***
4.  a layer with the colours of claric material in ≥ 95% of its exposed area, which is considered as reductimorphic feature, above an [*abrupt textural difference*](#sec-abtxdf) or above a layer with a bulk density of ≥ 1.5 kg dm^-1^; ***or***
5.  a combination of two layers: a layer with [*claric material*](#sec-claricm) in ≥ 95% of its exposed area, which is considered as reductimorphic feature, and a directly underlying layer fulfilling the diagnostic criteria 1, 2 or 3.

#### Field identification {#sec-stagnp-flic}

Redoximorphic features are described in Annex 1 ([Chapter 8.4.20](annex-02-field-guide.qmd#sec-a2-redox)).

#### Additional information {#sec-stagnp-info}

Stagnic properties result from a reduction of iron and/or manganese (hydr-)oxides around the larger pores. Mobilized Mn and Fe may be washed out laterally resulting in [*claric material*](#sec-claricm) (especially in the upper part of the profile that is coarser textured in many soils) or may migrate into the interiors of the soil aggregates where they are reoxidized (especially in the lower part of the profile).

If the stagnic properties are weakly expressed, the reductimorphic and oximorphic features cover only some parts of the exposed area, and the other parts show the original matrix colour that prevailed in the soil before the redox processes started. If the stagnic properties are strongly expressed, the entire exposed area of the fine earth shows either reductimorphic or oximorphic features.

#### Relationships with some other diagnostics {#sec-stagnp-reln}

Stagnic properties differ from [*gleyic properties*](#sec-gleyicp). Stagnic properties are caused by stagnation of an intruding agent (mostly rainwater) that causes [*reducing conditions*](#sec-reducc) and that leads to an overlying Fe-poor layer and an underlying layer with oximorphic features inside the soil aggregates. (In some soils, only one of these layers is present.) [*Gleyic properties*](#sec-gleyicp) are caused by an upward moving agent (mostly groundwater) that causes [*reducing conditions*](#sec-reducc) and that leads to an underlying strongly reduced layer and an overlying layer with oximorphic features on or adjacent to the soil aggregate surfaces. (In some soils, only one of these layers is present.)

### Takyric properties {#sec-takyrp}

#### General description {#sec-takyrp-desc}

Takyric properties (from Turkic languages *takyr*, barren land) are related to a fine-textured surface crust with a platy or massive structure. They occur under arid conditions in periodically flooded soils.

#### Diagnostic criteria {#sec-takyrp-diag}

Takyric properties refer to a surface crust consisting of [*mineral material*](#sec-minm) that has all of the following:

1.  a texture class of clay loam, silty clay loam, silty clay or clay; ***and***
2.  a platy or massive structure; ***and***
3.  polygonal cracks, ≥ 2 cm deep and with an average horizontal spacing of ≤ 20 cm, when the soil is dry; ***and***
4.  a rupture-resistance class of at least hard when dry and a plasticity of at least moderately plastic when moist; ***and***
5.  an electrical conductivity (EC~e~) of the saturation extract of
    a.  \< 4 dS m^-1^; ***or***
    b.  at least 1 dS m^-1^ less than that of the layer directly below the surface crust.

#### Field identification {#sec-takyrp-flid}

Takyric properties occur in depressions in arid regions, where surface water, rich in clay and silt but relatively low in soluble salts, accumulates and leaches salts out of the upper soil horizons. This causes clay dispersion and the formation of a thick, compact, fine-textured crust with prominent polygonal cracks when dry. The crust often contains ≥ 80% clay and silt. It is thick enough that it does not curl entirely upon drying.

#### Relationships with some other diagnostics {#sec-takyrp-reln}

Takyric properties occur in association with many diagnostic horizons, the most important ones being the [*natric*](#sec-natrh), [*salic*](#sec-salich), [*gypsic*](#sec-gypsih), [*calcic*](#sec-calch) and [*cambic horizons*](#sec-cambh). The low EC and low soluble-salt content of takyric properties set them apart from the [*salic horizon*](#sec-salich).

### Vitric properties {#sec-vitricp}

#### General description {#sec-vitricp-desc}

Vitric properties (from Latin *vitrum*, glass) apply to layers that contain glass from volcanic or industrial origin and that contain a limited amount of short-range-order minerals or organo-metallic complexes.

#### Diagnostic criteria {#sec-vitricp-diag}

Vitric properties require:

1.  in the fraction between \> 0.02 and ≤ 2 mm, ≥ 5% (by grain count) volcanic glass, glassy aggregates, other glass-coated primary minerals or glasses resulting from industrial processes; ***and***
2.  an Al~ox~ + ½Fe~ox~ value of ≥ 0.4%; ***and***
3.  a phosphate retention of ≥ 25%.

#### Field identification {#sec-vitricp-flid}

Vitric properties can occur in a surface layer. However, they can also occur under some tens of centimetres of recent pyroclastic deposits. Layers with vitric properties can have an appreciable amount of organic matter. The sand and coarse silt fractions of layers with vitric properties have a significant amount of unaltered or partially altered volcanic glass, glassy aggregates, other glass-coated primary minerals or glassses resulting from industiral processes (coarser fractions may be checked by using a 10x hand lens; finer fractions may be checked by using a microscope).

#### Relationships with some other diagnostics {#sec-vitricp-reln}

Vitric properties are, on the one hand, closely linked with [*andic properties*](#sec-andicp), into which they may eventually develop. For some time during this development, a layer may show both the amount of volcanic glasses required for the vitric properties and the characteristics of [*andic properties*](#sec-andicp). On the other hand, layers with vitric properties develop from [*tephric material*](#sec-tephrm). The diagnostic criteria of the vitric and [*andic properties*](#sec-andicp) are adapted after Shoji et al. [-@shoji1996], Takahashi et al. [-@takahashi2004] and findings of the COST 622 Action [-@costassociation2004].

[*Chernic*](#sec-chernh), [*mollic*](#sec-mollh) and [*umbric horizons*](#sec-umbrich) may exhibit vitric properties as well.

### Yermic properties {#sec-yermicp}

#### General description {#sec-yermicp-desc}

Yermic properties (from Spanish *yermo*, desert) are found on the mineral soil surface in deserts. They comprise features like desert pavement, desert varnish, ventifacts (windkanters), a platy structure and vesicular pores.

#### Diagnostic criteria {#sec-yermicp-diag}

Yermic properties occur in [*mineral material*](#sec-minm) and have one or both of the following:

1.  coarse surface fragments covering ≥ 20% of the soil surface (desert pavement), underlain by a soil layer with an abundance of coarse fragments half or less the abundance of coarse surface fragments, and one or more of the following:
    a.  ≥ 10% of the coarse fragments, \> 2 cm (greatest dimension), are varnished; ***or***
    b.  ≥ 10% of the coarse fragments, \> 2 cm (greatest dimension), are wind-shaped (ventifacts, windkanters); ***or***
    c.  a surface layer, ≥ 1 cm thick, with a platy structure; ***or***
    d.  a surface layer, ≥ 1 cm thick, with many vesicular pores; ***or***
2.  a surface layer, not compacted by human activity, ≥ 1 cm thick, with a platy structure and many vesicular pores.

#### Field identification {#sec-yermicp-flic}

The features of the yermic properties are described in Annex 1:\
desert pavement (Chapter 8.3.4)\
desert varnish and ventifacts (Chapter 8.3.5)\
platy structure (Chapter [8.4.10](annex-01-field-guide.qmd#sec-a1-struct))\
vesicular pores (Chapter 8.4.12) - to be diagnostic, the vesicular pores must be present in the abundance class 'many'.

If the texture is fine enough, the soil may show a polygonal network of desiccation cracks (Chapter 8.4.13), often filled with in-blown material, that extend into greater depths. In cold deserts, larger coarse fragments at the soil surface are often shattered by frost.

#### Relationships with some other diagnostics {#sec-yermicp-reln}

Yermic properties often occur in association with other diagnostics, characteristic for desert environments ([*salic*](#sec-salich), [*duric*](#sec-durich), [*gypsic*](#sec-gypsih), [*calcic*](#sec-calch) and [*cambic horizons*](#sec-cambh)). In very cold deserts (e.g. Antarctica), they may occur associated with [*cryic horizons*](#sec-cryich). Under these conditions, coarse cryoclastic material dominates, and there is little dust to be deflated and deposited by wind. Here, a dense pavement with varnish, ventifacts, aeolian sand layers and accumulations of soluble minerals may occur directly on loose deposits, without vesicular pores.

## Diagnostic materials {#sec-diagm}

**Diagnostic materials** are materials that significantly influence soil-forming processes. Their characteristics may be inherited from the parent material or may be the result of soil-forming processes. Diagnostic materials do not describe parent material; they describe soil material, and the characteristics refer (as for all diagnostics) to the fine earth, unless stated otherwise. Their features can be observed or measured in the field or the laboratory and require a minimum or maximum expression to qualify as diagnostic. A minimum thickness is not part of the criteria.

### Aeolic material {#sec-aeolicm}

#### General description {#sec-aeolicm-desc}

Aeolic material (from Greek *aiolos*, wind) describes material deposited by wind, typical in arid and semi-arid environments.

#### Diagnostic criteria {#sec-aeolicm-diag}

Aeolic material requires:

1.  evidence of wind deposition within 20 cm from the mineral soil surface by one or both of the following:
    a.  10% of the particles of medium and coarse sand are rounded or subangular and have a matt surface, in some layer or in in-blown material filling cracks; ***or***
    b.  aeroturbation (e.g. cross-bedding) in some layer; ***and***
2.  \< 1% [*soil organic carbon*](#sec-soc) from the mineral soil surface to a depth of 10 cm.

### Artefacts {#sec-artefm}

#### General description {#sec-artefm-desc}

Artefacts describe human-made, human-altered and human-excavated material. They may by physically altered (e.g. broken to pieces) but are chemically and mineralogically not or only poorly altered and still largely recognizable.

#### Diagnostic criteria {#sec-artefm-diag}

Artefacts (from Latin *ars*, art, and *factus*, made) are liquid or solid substances of any size that:

1.  are one or both of the following:
    a.  created or substantially modified by humans as part of industrial or artisanal manufacturing processes; ***or***
    b.  brought to the soil surface by human activity from a depth, where they were not influenced by surface processes, and deposited in an environment, where they do not commonly occur, with properties substantially different from the environment where they are placed; ***and***
2.  have substantially the same chemical and mineralogical properties as when first manufactured, modified or excavated.

#### Additional information {#sec-artefm-info}

Examples of artefacts are bricks, pottery, glass, crushed or dressed stone, wooden boards, industrial waste, plastic, garbage, processed oil products, bitumen, mine spoil and crude oil.

#### Relationships with some other diagnostics {#sec-artefm-reln}

[*Technic hard material*](#sec-techhm) and geomembranes, intact, fractured or composed, also fulfil the diagnostic criteria of artefacts.

### Calcaric material {#sec-calcam}

#### General description {#sec-calcam-desc}

Calcaric material (from Latin *calcarius*, containing lime) refers to material that contains ≥ 2% calcium carbonate equivalent. The carbonates are at least partially inherited from the parent material (primary carbonates).

#### Diagnostic criteria {#sec-calcam-diag}

Calcaric material shows visible effervescence with 1 *M* HCl throughout the fine earth.

#### Relationships with some other diagnostics {#sec-calcam-reln}

Calcaric material may also meet the diagnostic criteria of [*protocalcic properties*](#sec-protcp), which show discernible accumulations of secondary carbonates. [*Calcic*](#sec-calch) and [*petrocalcic horizons*](#sec-petroh) have higher contents of carbonates and also show secondary carbonates. *Petrocalcic horizons* are continuously cemented.

### Claric material {#sec-claricm}

#### General description {#sec-claricm-desc}

Claric material (from Latin *clarus*, bright) is light-coloured fine earth.

#### Diagnostic criteria {#sec-claricm-diag}

Claric material is [*mineral material*](#sec-minm) and:

1.  has in ≥ 90% of its exposed area a Munsell colour, dry, with one or both of the following:
    a.  a value of ≥ 7 and a chroma of ≤ 3; ***or***
    b.  a value of ≥ 5 and a chroma of ≤ 2; ***and***
2.  has in ≥ 90% of its exposed area a Munsell colour, moist, with one or more of the following:
    a.  a value of ≥ 6 and a chroma of ≤ 4; ***or***
    b.  a value of ≥ 5 and a chroma of ≤ 3; ***or***
    c.  a value of ≥ 4 and a chroma of ≤ 2; ***or***
    d.  all of the following:
        i.  a hue of 5YR or redder; ***and***
        ii. a value of ≥ 4 and a chroma of ≤ 3; ***and***
        iii. ≥ 25% of the sand and coarse silt grains are uncoated.

#### Field identification {#sec-claricm-flid}

Identification in the field depends on soil colours. In addition, a 10x hand lens may be used to ascertain that sand and coarse silt grains are free of coatings (criterion 2.d). Claric material may exhibit a considerable shift in chroma when wetted.

#### Additional information {#sec-claricm-info}

The presence of coatings around sand and coarse silt grains can be determined using an optical microscope for analysing thin sections. Uncoated grains usually show a very thin rim at their surface. Coatings may be of an organic nature, consist of iron oxides, or both, and are dark-coloured under translucent light. Iron coatings become reddish in colour under reflected light, while organic coatings remain brownish-black.

#### Relationships with some other diagnostics {#sec-claricm-reln}

The claric material is used as a diagnostic criterion in the definition of the [*spodic horizon*](#sec-spodh), the [*retic*](#sec-reticp) and the [*stagnic properties*](#sec-stagnp). A layer with claric material that has lost oxides and/or organic matter due to clay migration, podzolization or due to redox processes caused by stagnant water, forms an [*albic horizon*](#sec-albich).

### Dolomitic material {#sec-dolom}

#### Diagnostic criteria {#sec-dolom-diag}

Dolomitic material (named after the French geoscientist *Déodat de Dolomieu*) shows visible effervescence with heated 1 *M* HCl throughout the fine earth. It applies to material that contains ≥ 2% of a mineral that has a ratio CaCO~3~/MgCO~3~ \< 1.5. With non-heated HCl, it gives only a retarded and poorly visible effervescence.

### Fluvic material {#sec-fluvicm}

#### General description {#sec-fluvicm-desc}

Fluvic material (from Latin *fluvius*, river) refers to fluviatile, marine and lacustrine sediments that receive fresh material or have received it in the past and still show stratification. Fluvic material shows only little soil formation after deposition.

#### Diagnostic criteria {#sec-fluvicm-diag}

Fluvic material is [*mineral material*](#sec-minm) and:

1.  is of fluviatile, marine or lacustrine origin; ***and***
2.  has strata that are one or both of the following:
    a.  obvious (including stratification tilted by cryogenic alteration) in ≥ 25% (by volume, related to the whole soil) over a specified depth; ***or***
    b.  evidenced by a layer with all of the following:
        i.  ≥ 0.2% [*soil organic carbon*](#sec-soc); ***and***
        ii. a content of [*soil organic carbon*](#sec-soc) ≥ 25% (relative) and ≥ 0.2% (absolute) higher than in the overlying layer; ***and***
        iii. does not form part of a [*natric*](#sec-natrh) or [*spodic horizon*](#sec-spodh); ***and***
3.  has a single grain, a massive, a platy or a weak subangular blocky structure; ***and***
4.  is not cemented.

#### Field identification {#sec-fluvicm-flid}

Stratification may be reflected in different ways:

-   variation in texture and/or content or nature of coarse fragments
-   different colours related to the source materials
-   alternating lighter- and darker-coloured soil layers, indicating an irregular decrease in [*soil organic carbon*](#sec-soc) content with depth.

#### Relationships with some other diagnostics {#sec-fluvicm-reln}

Fluvic material is always associated with water bodies (e.g. rivers, lakes, the sea) and can therefore be distinguished from [*solimovic material*](#sec-solimvm). It may also fulfil the criteria of [*limnic material*](#sec-limnh).

### Gypsiric material {#sec-gyspicm}

#### Diagnostic criteria {#sec-gyspicm-diag}

Gypsiric material (from Greek *gypsos*, gypsum) is [*mineral material*](#sec-minm) that contains ≥ 5% gypsum that is not secondary gypsum.

#### Relationships with some other diagnostics {#sec-gyspicm-reln}

Gypsiric material may also meet the diagnostic criteria of [*protogypsic properties*](#sec-protgp), which show discernible accumulations of secondary gypsum. [*Gypsic*](#sec-gypsih) and [*petrogypsic horizons*](#sec-petrgh) also show secondary gypsum. [*Petrogypsic horizons*](#sec-petrgh) have high amounts of gypsum and are continuously cemented.

### Hypersulfidic material {#sec-hypersm}

#### General description {#sec-hypersm-desc}

Hypersulfidic material (from Greek *hyper*, over, and Latin *sulpur*, sulfur) contains inorganic sulfidic S and is capable of severe acidification as a result of the oxidation of inorganic sulfidic compounds contained within it. Hypersulfidic material is also known as 'potential acid sulfate soil'.

#### Diagnostic criteria {#sec-hypersm-diag}

Hypersulfidic material:

1.  has ≥ 0.01% inorganic sulfidic S; ***and***
2.  has a pH (1:1 by mass in water, or in a minimum of water to permit measurement) of ≥ 4; ***and***
3.  when a layer, 2--10 mm thick, is incubated aerobically at field capacity for 8 weeks, the pH drops to \< 4 and one or more of the following:
    a.  within these 8 weeks, the total pH decline is ≥ 0.5 pH units; ***or***
    b.  latest after these 8 weeks, the decrease in pH is only ≤ 0.1 pH units over a further period of 14 days; *or*
    c.  latest after these 8 weeks, the pH begins to increase again.

#### Field identification {#sec-hypersm-flid}

Hypersulfidic material is seasonally or permanently waterlogged or forms under largely anaerobic conditions. It has a Munsell colour hue of N, 5Y, 5GY, 5BG, or 5G, a value of ≤ 4, and a chroma of 1, all moist. If the soil is disturbed, an odour of hydrogen sulfide (rotten eggs) may be noticed. This is accentuated by application of 1 *M* HCl.

For a quick screening test that is not definitive, a 10 g sample treated with 50 ml of 30% H~2~O~2~ will show a fall in pH to ≤ 2.5. Final assessment depends on incubation testing.

**Caution**: H~2~O~2~ is a strong oxidant, and sulfides and organic matter will froth violently in a test tube that may become very hot.

#### Relationships with some other diagnostics {#sec-hypersm-reln}

Acidification of hypersulfidic material usually causes the development of a [*thionic horizon*](#sec-thionh). [*Hyposulfidic material*](#sec-hyposm) has the same criteria for inorganic sulfidic S and for the pH value but is not capable of severe acidification.

### Hyposulfidic material {#sec-hyposm}

#### General description {#sec-hyposm-desc}

Hyposulfidic material (from Greek *hypo*, under, and Latin *sulpur*, sulfur) contains inorganic sulfidic S and is not capable of severe acidification resulting from the oxidation of inorganic sulfidic compounds contained within it. Although oxidation does not lead to the formation of acid sulfate soils, hyposulfidic material is an important environmental hazard due to processes related to inorganic sulfides. Hyposulfidic material has a self-neutralizing capacity, usually due to the presence of calcium carbonate.

#### Diagnostic criteria {#sec-hyposm-diag}

Hyposulfidic material:

1.  as ≥ 0.01% inorganic sulfidic S ; ***and***
2.  has a pH (1:1 by mass in water, or in a minimum of water to permit measurement) of ≥ 4; ***and***
3.  does not consist of [*hypersulfidic material*](#sec-hypersm).

#### Field identification {#sec-hyposm-flid}

Hyposulfidic material forms in similar environments to [*hypersulfidic material*](#sec-hypersm) and morphologically may be indistinguishable from it. However, it is less likely to be coarse in texture. The hydrogen peroxide screening test (see [*hypersulfidic material*](#sec-hypersm)) may also be indicative, but final assessment depends on incubation testing. Field tests for fine earth carbonate may be used to indicate whether the soil has some self-neutralizing capacity.

#### Relationships with some other diagnostics {#sec-hyposm-reln}

Acidification of hyposulfidic material usually does not cause the development of a [*thionic horizon*](#sec-thionh). [Hypersulfidic material](#sec-hypersm) has the same criteria for inorganic sulfidic S and for the pH value but is capable of severe acidification.

### Limnic material {#sec-limnicm}

#### Diagnostic criteria {#sec-limnicm-diag}

Limnic material (from Greek *limnae*, pool) includes both organic and [*mineral material*](#sec-minm) and is one or more of the following:

1.  deposited in water by precipitation, possibly in combination with sedimentation; ***or***
2.  derived from algae; ***or***
3.  derived from aquatic plants and subsequently transported; ***or***
4.  derived from aquatic plants and subsequently modified by aquatic animals and/or microorganisms.

#### Field identification {#sec-limnicm-flid}

[*Limnic material*](#sec-limnicm) is formed as subaquatic deposits and usually stratified. (After drainage it may occur at the soil surface.) Four types of limnic material can be distinguished:

1.  *Coprogenous earth* or *sedimentary peat*: organic, identifiable through many faecal pellets and peat residues, Munsell colour value of ≤ 4, moist, slightly viscous water suspension, a non-plastic or slightly plastic plasticity type, shrinking upon drying, difficult to rewet after drying, and cracking along horizontal planes.
2.  *Diatomaceous earth*: mainly diatoms (siliceous), identifiable by irreversible changing of the matrix colour (Munsell colour value of 3 to 5 in field moist or wet condition) upon drying as a result of the irreversibly shrinkage of the organic coatings on diatoms (use 440x microscope).
3.  *Marl*: strongly calcareous, identifiable by a Munsell colour value of ≥ 5, moist, and a reaction with 1 *M* HCl. The colour of marl usually does not change irreversibly upon drying.
4.  *Gyttja*: small coprogenic aggregates, consisting of organic matter that has been strongly alterated by microorganisms, and minerals of predominantly clay to silt size, ≥ 0.5% [*soil organic carbon*](#sec-soc), a Munsell colour hue of 5Y, GY or G, moist, strong shrinkage after drainage and an rH value of ≥ 13.

### Mineral material {#sec-minm}

#### General description {#sec-minm-desc}

In mineral material (from Celtic *mine*, mineral), the properties of the fine earth are dominated by mineral components.

#### Diagnostic criteria {#sec-minm-diag}

Mineral material has

1.  \< 20% [*soil organic carbon*](#sec-soc) (related to the fine earth plus the dead plant remnants of any length and a diameter ≤ 5 mm); ***and***
2.  \< 35% (by volume, related to the whole soil) artefacts containing ≥ 20% organic carbon.

#### Relationships with some other diagnostics {#sec-minm-reln}

Material that has ≥ 20% [*soil organic carbon*](#sec-soc) is [*organic material*](#sec-orgm). Other material that has ≥ 35% (by volume, related to the whole soil) [*artefacts*](#sec-artefm) containing ≥ 20% organic carbon is [*organotechnic material*](#sec-orgtcm).

### Mulmic material {#sec-mulm}

#### General description {#sec-mulm-desc}

Mulmic material (from German *Mulm*, powdery detritus) is [*mineral material*](#sec-minm) developed from [*organic material*](#sec-orgm). If water-saturated [*organic material*](#sec-orgm) is drained, a fast decomposition starts. While the amount of mineral components remains constant, the amount of organic matter decreases, and the organic matter content eventually falls below 20%, resulting in [*mineral material*](#sec-minm).

#### Diagnostic criteria {#sec-mulm-diag}

Mulmic material is [*mineral material*](#sec-minm) that has developed from water-saturated [*organic material*](#sec-orgm) after drainage and that has:

1.  ≥ 8% [*soil organic carbon*](#sec-soc); ***and***
2.  single or in combination:
    a.  a single grain structure; ***or***
    b.  a subangular or angular blocky structure with an average aggregate size of ≤ 2 cm; ***and***
3.  a Munsell colour chroma of ≤ 2, moist.

### Organic material {#sec-orgm}

#### General description {#sec-orgm-desc}

Organic material (from Greek *organon*, tool) has large amounts of organic matter in the fine earth and/or contains many dead thin plant remnants. It may show different stages of decomposition. If still connected to living plants (e.g. *Sphagnum* mosses), it may even be completely undecomposed. If derived from fallen organic residues, it is decomposed to at least the extent that it is not loose and/or that recognizable dead plant tissues comprise ≤ 90% of the volume (related to the fine earth plus all dead plant remnants). Fallen organic residues with \> 90% recognizable dead plant tissues and still loose are called litter layer (see Chapter 2.1, General rules, and Annex 1, Chapters 8.3.1 and 8.3.2) and are not considered for classification in WRB. (Litter layers are temporally and spatially extremely variable in thickness). On the other hand, decomposition may be advanced until no recognizable dead plant tissues remain, and a homogeneous organic soil mass results. Organic material accumulates under both wet and dry conditions. The mineral component of the fine earth has a limited influence on soil properties.

#### Diagnostic criteria {#sec-orgm-diag}

Organic material

1.  has ≥ 20% [*soil organic carbon*](#sec-soc) (related to the fine earth plus the dead plant remnants of any length and a diameter ≤ 5 mm); ***and***
2.  one or more of the following
    a.  contains ≤ 90% (by volume, related to the fine earth plus all dead plant remnants) recognizable dead plant tissues ***or***
    b.  is not loose; ***or***
    c.  consists of dead plant material still connected to living plants.

#### Additional information {#sec-orgm-info}

20% organic carbon roughly correspond to 40% organic matter. The remaining up to 60% consist of mineral components and/or of organic components that meet the criteria of *artefacts*.

#### Relationships with some other diagnostics {#sec-orgm-reln}

[Soil organic carbon](#sec-soc) is organic carbon that does not meet the set of diagnostic criteria of *artefacts*. Material that has \< 20% [*soil organic carbon*](#sec-soc) is either *organotechnic* or [*mineral material*](#sec-minm). *Histic* and *folic horizons* consist of organic material.

### Organotechnic material {#sec-orgtcm}

#### General description {#sec-orgtcm-desc}

Organotechnic material (from Greek *organon*, tool, and *technae*, art) contains large amounts of organic *artefacts*. It contains relatively small amounts of [*soil organic carbon*](#sec-soc) (organic carbon that does not meet the set of diagnostic criteria of *artefacts*).

#### Diagnostic criteria {#sec-orgtcm-diag}

Organotechnic material has

1.  ≥ 35% (by volume, related to the whole soil) [*artefacts*](#sec-artefm) containing ≥ 20% organic carbon; ***and***
2.  \< 20% [*soil organic carbon*](#sec-soc) (related to the fine earth plus the dead plant remnants of any length and a diameter ≤ 5 mm).

#### Additional information {#sec-orgtcm-info}

Examples for organotechnic material are excavated coal, petroleum lenses, plastic, wooden boards and garbage like kitchen slops or baby nappies.

#### Relationships with some other diagnostics {#sec-orgtcm-reln}

Material with ≥ 20% [*soil organic carbon*](#sec-soc) is [*organic material*](#sec-orgm), irrespective of the other components. Material with \< 20% [*soil organic carbon*](#sec-soc) and lower amounts of organic [*artefacts*](#sec-artefm) is [*mineral material*](#sec-minm).

### Ornithogenic material {#sec-ornithm}

#### General description {#sec-ornithm-desc}

Ornithogenic material (from Greek *ornis*, bird, and *genesis*, origin) is material with strong influence of bird excrements. It often has a high content of coarse fragments that have been transported by birds.

#### Diagnostic criteria {#sec-ornithm-diag}

Ornithogenic material has:

1.  remnants of birds or bird activity (bones, feathers, and sorted coarse fragments of similar size); ***and***
2.  ≥ 750 mg kg^-1^ P in the Mehlich-3 extract.

#### Additional information {#sec-ornithm-info}

750 mg kg^-1^ P in the Mehlich-3 extract roughly correspond to 1090 mg kg^-1^ P or 2500 mg kg^-1^ P~2~O~5~ in 1% citric acid [@kabala2018], which was the requirement in former editions of WRB.

### Soil organic carbon {#sec-soc}

#### Diagnostic criteria {#sec-soc-diag}

Soil organic carbon (from Greek *organon*, tool, and Latin *carbo*, coal) is organic carbon that does not meet the set of diagnostic criteria of [*artefacts*](#sec-artefm).

#### Relationships with some other diagnostics {#sec-soc-reln}

For organic carbon meeting the criteria of [*artefacts*](#sec-artefm), the *Garbic* or the *Carbonic* qualifier may apply.

### Solimovic material {#sec-solimvm}

#### General description {#sec-solimvm-desc}

Solimovic material (from Latin *solum*, soil, and *movere*, to move) is a heterogeneous mixture of material that has moved downslope, suspended in water. It is dominated by material that underwent soil formation at its original place, e.g. organic matter accumulation or the formation of Fe oxides. It has been transported as a result of erosional wash or soil creep, and the transport may have been accelerated by land-use practices (e.g. deforestation, ploughing, downhill tillage, structure degradation). Solimovic material has been formed in relatively recent times (mostly Holocene). It normally accumulates in slope positions, in depressions or above a barrier on a low-grade slope. The barrier may be natural or human-made (e.g. hedge walls, terraces, benches). After deposition, there was no advanced soil formation.

#### Diagnostic criteria {#sec-solimvm-diag}

Solimovic material is [*mineral material*](#sec-minm) and:

1.  is found on slopes, footslopes, toeslopes, fans, in depressions, above barriers, along gullies or similar relief positions, originating from upslope positions where it was subject to diffuse erosion; ***and***
2.  is not of fluviatile, lacustrine, marine or mass movement origin; ***and***
3.  one or more of the following:
    a.  if burying a mineral soil, it has a lower bulk density than the uppermost layer of the buried soil; ***or***
    b.  has ≥ 0.6% [*soil organic carbon*](#sec-soc); ***or***
    c.  has a Munsell colour chroma of ≥ 3, moist; ***or***
    d.  contains artefacts and/or black carbon of any size; ***or***
    e.  has ≥ 100 mg kg^-1^ P in the Mehlich-3 extract; ***and***
4.  does not form part of a diagnostic horizon other than a [*cambic*](#sec-cambh), [*chernic*](#sec-chernh), [*mollic*](#sec-mollh) or [*umbric horizon*](#sec-umbrich).

#### Field identification {#sec-solimvm-flid}

The fine earth of solimovic material can be of any particle size. Some small coarse fragments may be included. Solimovic material is generally imperfectly sorted. It may show some gross stratification, but stratification is not a typical feature due to the diffuse or chaotic nature of the deposition process. Solimovic material tends to occupy gently sloping to moderately steep sloping (2-30%) areas. Black carbon or small [*artefacts*](#sec-artefm) such as pieces of bricks, ceramics and glass may be present in solimovic material. In many cases, solimovic material has a [*lithic discontinuity*](#sec-lithd) at its base.

The upper part of the solimovic material shows characteristics (fine earth texture, colour, pH and [*soil organic carbon*](#sec-soc) content) similar to the surface layer of the source in the neighbourhood. In extreme cases, the profile in the solimovic material mirrors the eroded soil profile of upward slope positions, with topsoil material buried under former subsoil material. Good indication in a landscape is varying colour of the soil surface between convex and concave positions.

#### Additional information {#sec-solimvm-info}

Accumulations by rapid mass movements such as in landslides, slumps or tree throws do not meet the set of diagnostic criteria of solimovic material.

In agricultural environments, solimovic material has mostly a high base saturation. If not natural, this is the result of liming or fertilization before and/or after having been eroded.

In former editions of WRB, the solimovic material was called colluvic material. However, the traditional use of the word 'colluvium' is so different between countries and national traditions and changed so much over time [@miller2020] that it is better to avoid this term and use a new one.

#### Relationships with some other diagnostics {#sec-solimvm-reln}

Solimovic material is not associated with perennial water bodies (e.g. rivers, lakes, the sea) and can therefore be distinguished from [*fluvic material*](#sec-fluvicm). However, in toeslope positions, [*fluvic*](#sec-fluvicm) and solimovic material may be sedimented alternatingly or grade into each other and may be difficult to differentiate.

Solimovic material is not purposefully added as, e.g., the soil material in [*terric horizons*](#sec-terich).

### Technic hard material {#sec-techhm}

#### General description {#sec-techhm-desc}

Technic hard material (from Greek *technae*, art) describes consolidated material, created or substantially modified by humans.

#### Diagnostic criteria {#sec-techhm-diag}

Technic hard material:

1.  is consolidated material resulting from industrial or artisanal processes; ***and***
2.  has properties substantially different from those of natural materials; ***and***
3.  is continuous or has free space covering \< 5% of its horizontal extension.

#### Additional information {#sec-techhm-info}

Examples of technic hard material are asphalt, concrete or a continuous layer of worked stones.

#### Relationships with some other diagnostics {#sec-techhm-reln}

Technic hard material, intact, fractured or composed, also fulfils the diagnostic criteria of artefacts.

### Tephric material {#sec-tephrm}

#### General description {#sec-tephrm-desc}

Tephric material (from Greek *tephra*, pile ash) has many glasses in the fine earth. These consist of tephra (i.e. unconsolidated, unweathered or only slightly weathered pyroclastic products of volcanic eruptions), of tephric deposits (i.e. tephra that has been reworked and mixed with material from other sources, which includes tephric loess, tephric blown sand and volcanogenic alluvium) or of glasses resulting from industrial processes (e.g. ashes from power stations combusting coal or lignite).

#### Diagnostic criteria {#sec-tephrm-diag}

Tephric material has:

1.  in the fraction between \> 0.02 and ≤ 2 mm, ≥ 30% (by grain count) volcanic glass, glassy aggregates, other glass-coated primary minerals or glasses resulting from industrial processes; ***and***
2.  no [*andic*](#sec-andicp) or [*vitric properties*](#sec-vitricp).

#### Additional information {#sec-tephrm-info}

Tephric material refers to the fine earth, but coarse fragments may also be present (including cinders, lapilli, pumice, pumice-like vesicular pyroclasts, blocks and volcanic bombs). The original description of the tephric material is based on Hewitt [-@hewitt1992], the amendment of [*artefacts*](#sec-artefm) is adapted from Uzarowicz et al. [-@uzarowicz2017].

#### Relationships with some other diagnostics {#sec-tephrm-reln}

Progressive weathering of tephric material will lead to the formation of [*vitric properties*](#sec-vitricp). Glasses resulting from industrial processes fulfil the criteria of [*artefacts*](#sec-artefm).
