# Stagnosols {#key-stagnosols .unnumbered}

::: grid
::: g-col-4
Other soils having:

1.  *stagnic properties*, in which the area of reductimorphic features plus the area of oximorphic features is ≥ one third (weighted average) of the area from the mineral soil surface to a depth of 60 cm or to *continuous rock*, whichever is shallower; *and*
2.  *reducing conditions* for some time during the year in some parts of the soil volume that has the reductimorphic features within 60 cm from the mineral soil surface or to *continuous rock*, whichever is shallower.
:::

::: g-col-8
| Principal Qualifiers                                             | Supplementary Qualifiers       |
|------------------------------------------------|------------------------|
| Reductic                                                         | Arenic/ Clayic/ Loamic/ Siltic |
| Thionic                                                          | Endoabruptic                   |
| Leptic                                                           | Alcalic                        |
| Hydragric/ Anthraquic/ Irragric/ Hortic/ Plaggic/ Pretic/ Terric | Aric                           |
| Histic                                                           | Cambic                         |
| Gleyic                                                           | Capillaric                     |
| Chernic/ Mollic/ Umbric                                          | Cohesic                        |
| Albic                                                            | Drainic                        |
| Fluvic                                                           | Ferralic/ Sideralic            |
| Vertic                                                           | Ferric                         |
| Glossic/ Retic                                                   | Folic                          |
| Acric/ Lixic/ Alic/ Luvic                                        | Fragic                         |
| Calcic                                                           | Gelic                          |
| Dolomitic/ Calcaric                                              | Gelistagnic                    |
| Dystric/ Eutric                                                  | Geric                          |
|                                                                  | Humic/ Ochric                  |
|                                                                  | Inclinic                       |
|                                                                  | Magnesic                       |
|                                                                  | Mochipic                       |
|                                                                  | Nechic                         |
|                                                                  | Nitic                          |
|                                                                  | Novic                          |
|                                                                  | Ornithic                       |
|                                                                  | Pyric                          |
|                                                                  | Raptic                         |
|                                                                  | Rhodic/ Chromic                |
|                                                                  | Skeletic                       |
|                                                                  | Sodic                          |
|                                                                  | Solimovic                      |
|                                                                  | Protospodic                    |
|                                                                  | Sulfidic                       |
|                                                                  | Technic/ Kalaic                |
|                                                                  | Toxic                          |
|                                                                  | Transportic                    |
|                                                                  | Turbic                         |
|                                                                  | Uterquic                       |
:::
:::
