# Anthrosols {#key-anthrosols .unnumbered}

::: grid
::: g-col-4
Other soils having:

1.  a *hortic*, *irragric*, *plaggic* or *terric* horizon, ≥ 50 cm thick; *or*
2.  an *anthraquic horizon* and an underlying *hydragric horizon* with a combined thickness of ≥ 50 cm; *or*
3.  a *pretic horizon*, the layers of which have a combined thickness of ≥ 50 cm, within 100 cm of the mineral soil surface.
:::

::: g-col-8
| Principal Qualifiers                                | Supplementary Qualifiers       |
|--------------------------------------------|---------------------------|
| Hydragric/ Irragric/ Hortic/ Plaggic/ Pretic/Terric | Arenic/ Clayic/ Loamic/ Siltic |
| Gleyic                                              | Glossic/ Retic                 |
| Stagnic                                             | Acric/ Lixic/ Alic/ Luvic      |
| Ferralic/ Sideralic                                 | Alcalic/ Dystric/ Eutric       |
| Andic                                               | Calcic                         |
|                                                     | Carbonic                       |
|                                                     | Dolomitic/ Calcaric            |
|                                                     | Drainic                        |
|                                                     | Escalic                        |
|                                                     | Fluvic                         |
|                                                     | Endoleptic/ Endothyric         |
|                                                     | Novic                          |
|                                                     | Oxyaquic                       |
|                                                     | Panpaic                        |
|                                                     | Pyric                          |
|                                                     | Salic                          |
|                                                     | Skeletic                       |
|                                                     | Sodic                          |
|                                                     | Spodic                         |
|                                                     | Technic/ Kalaic                |
|                                                     | Toxic                          |
|                                                     | Vertic                         |
|                                                     | Vitric                         |
:::
:::
