# Phaeozems {#key-phaeozems .unnumbered}

::: grid
::: g-col-4
Other soils having:

1.  a *mollic horizon*; *and*
2.  a base saturation (by 1 *M* NH~4~OAc, pH 7)[^chapter-04-19-phaeozems-1] of ≥ 50% throughout to a depth of 100 cm from the mineral soil surface or to a limiting layer, whichever is shallower.
:::

::: g-col-8
| Principal Qualifiers             | Supplementary Qualifiers       |
|----------------------------------|--------------------------------|
| Rendzic                          | Arenic/ Clayic/ Loamic/ Siltic |
| Chernic/ Someric                 | Abruptic                       |
| Mulmic                           | Albic                          |
| Petroduric/ Duric                | Andic                          |
| Petrocalcic                      | Anthric                        |
| Endocalcic                       | Aric                           |
| Leptic                           | Columnic                       |
| Irragric/ Hortic/ Pretic/ Terric | Densic                         |
| Gleyic                           | Ferralic/ Sideralic            |
| Stagnic                          | Folic                          |
| Fluvic                           | Fractic                        |
| Vertic                           | Humic                          |
| Greyzemic                        | Isolatic                       |
| Glossic/ Retic                   | Laxic                          |
| Lixic/ Luvic                     | Limonic                        |
| Cambic/ Brunic                   | Magnesic                       |
| Skeletic                         | Nechic                         |
| Vermic                           | Novic                          |
| Tonguic                          | Oxyaquic                       |
| Gypsiric                         | Pachic                         |
| Dolomitic/ Calcaric              | Panpaic/ Raptic                |
| Haplic                           | Pyric                          |
|                                  | Relocatic                      |
|                                  | Rhodic/ Chromic                |
|                                  | Salic                          |
|                                  | Sodic                          |
|                                  | Solimovic                      |
|                                  | Sombric                        |
|                                  | Technic/ Kalaic                |
|                                  | Tephric                        |
|                                  | Transportic                    |
|                                  | Turbic                         |
|                                  | Vitric                         |
:::
:::

[^chapter-04-19-phaeozems-1]: If the data for base saturation are not available, pH values may be used according to Annex 2 (Chapter 9.13).
