# About {.unnumbered}

### Citation

IUSS Working Group WRB. 2022. World Reference Base for Soil Resources. International soil classification system for naming soils and creating legends for soil maps. 4^th^ edition. International Union of Soil Sciences (IUSS), Vienna, Austria.

\
\
\
\
\
\

ISBN 979-8-9862451-1-9

First published: 22 July 2022. Update with minor corrections: 18 December 2022

Copyright: International Union of Soil Sciences®, Vienna, Austria.\
This is an open access document under the terms of the [Creative Commons Attribution License](https://creativecommons.org/licenses/by/4.0/legalcode), which permits use, distribution and reproduction in any medium, provided the original work is properly cited.

Cover by Stefaan Dondeyne\
From left to right: Rhodic Ferritic Nitisol (Brazil) \[photo: Sérgio Shimizu\]\
Stagnic Gleyic Solonchak (Mongolia) \[photo: Stefaan Dondeyne\]\
Mollic Vitric Silandic Andosol (Iceland) \[photo: Stefaan Dondeyne\]\
Eutric Glossic Stagnosol (Belgium) \[photo: Stefaan Dondeyne\]

------------------------------------------------------------------------

This is a Quarto version of the [original PDF publication](https://wrb.isric.org/files/WRB_fourth_edition_2022-12-18.pdf), available at the [WRB website](https://wrb.isric.org/) along with other supporting documentation and teaching materials. This version incorporates the published errata to 2022-12-18.
